arb-dir: lib/l10n
template-arb-file: ouds_flutter_en.arb
output-class: OudsLocalizations
output-dir: lib/l10n/gen/
output-localization-file: ouds_localizations.dart
synthetic-package: false
# Uncomment this line to find errors in l10n generation
#untranslated-messages-file: l10n_errors.txt

