//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange Compact brand tokens version 2.4.0
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_space_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class OrangeCompactSpaceSemanticTokens extends OudsSpaceSemanticTokens {
  @override
  double get columnGap2xlarge => DimensionRawTokens.dimension250;
  @override
  double get columnGap2xsmall => DimensionRawTokens.dimension50;
  @override
  double get columnGap3xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get columnGapLarge => DimensionRawTokens.dimension150;
  @override
  double get columnGapMedium => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get columnGapNone => DimensionRawTokens.dimension0;
  @override
  double get columnGapSmall => DimensionRawTokens.dimension100;
  @override
  double get columnGapXlarge => DimensionRawTokens.dimension200;
  @override
  double get columnGapXsmall => DimensionRawTokens.dimensionOutOfSystem150;
  @override
  double get fixed2xlarge => DimensionRawTokens.dimension500;
  @override
  double get fixed2xsmall => DimensionRawTokens.dimension50;
  @override
  double get fixed3xlarge => DimensionRawTokens.dimension600;
  @override
  double get fixed3xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get fixed4xlarge => DimensionRawTokens.dimension700;
  @override
  double get fixed5xlarge => DimensionRawTokens.dimension800;
  @override
  double get fixedLarge => DimensionRawTokens.dimension300;
  @override
  double get fixedMedium => DimensionRawTokens.dimension200;
  @override
  double get fixedNone => DimensionRawTokens.dimension0;
  @override
  double get fixedSmall => DimensionRawTokens.dimension150;
  @override
  double get fixedXlarge => DimensionRawTokens.dimension400;
  @override
  double get fixedXsmall => DimensionRawTokens.dimension100;
  @override
  double get inset2xlarge => DimensionRawTokens.dimension350;
  @override
  double get inset2xsmall => DimensionRawTokens.dimension50;
  @override
  double get inset3xlarge => DimensionRawTokens.dimension450;
  @override
  double get inset3xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get inset4xsmall => DimensionRawTokens.dimensionOutOfSystem25;
  @override
  double get insetLarge => DimensionRawTokens.dimension150;
  @override
  double get insetMedium => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get insetNone => DimensionRawTokens.dimension0;
  @override
  double get insetSmall => DimensionRawTokens.dimension100;
  @override
  double get insetXlarge => DimensionRawTokens.dimension250;
  @override
  double get insetXsmall => DimensionRawTokens.dimensionOutOfSystem150;
  @override
  double get paddingBlock2xlarge => DimensionRawTokens.dimension250;
  @override
  double get paddingBlock2xsmall => DimensionRawTokens.dimensionOutOfSystem150;
  @override
  double get paddingBlock3xlarge => DimensionRawTokens.dimension300;
  @override
  double get paddingBlock3xsmall => DimensionRawTokens.dimension50;
  @override
  double get paddingBlock4xlarge => DimensionRawTokens.dimension350;
  @override
  double get paddingBlock4xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get paddingBlockLarge => DimensionRawTokens.dimension150;
  @override
  double get paddingBlockMedium => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get paddingBlockNone => DimensionRawTokens.dimension0;
  @override
  double get paddingBlockSmall => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get paddingBlockXlarge => DimensionRawTokens.dimension200;
  @override
  double get paddingBlockXsmall => DimensionRawTokens.dimension100;
  @override
  double get paddingInline2xlarge => DimensionRawTokens.dimension250;
  @override
  double get paddingInline2xsmall => DimensionRawTokens.dimensionOutOfSystem150;
  @override
  double get paddingInline3xlarge => DimensionRawTokens.dimension300;
  @override
  double get paddingInline3xsmall => DimensionRawTokens.dimension50;
  @override
  double get paddingInline4xlarge => DimensionRawTokens.dimension350;
  @override
  double get paddingInline4xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get paddingInlineLarge => DimensionRawTokens.dimension150;
  @override
  double get paddingInlineMedium => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get paddingInlineNone => DimensionRawTokens.dimension0;
  @override
  double get paddingInlineSmall => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get paddingInlineXlarge => DimensionRawTokens.dimension200;
  @override
  double get paddingInlineXsmall => DimensionRawTokens.dimension100;
  @override
  double get rowGap2xsmall => DimensionRawTokens.dimension50;
  @override
  double get rowGap3xsmall => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get rowGapLarge => DimensionRawTokens.dimension150;
  @override
  double get rowGapMedium => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get rowGapNone => DimensionRawTokens.dimension0;
  @override
  double get rowGapSmall => DimensionRawTokens.dimension100;
  @override
  double get rowGapXsmall => DimensionRawTokens.dimensionOutOfSystem150;
  @override
  double get scaled2xlargeMobile => DimensionRawTokens.dimension450;
  @override
  double get scaled2xlargeTablet => DimensionRawTokens.dimension550;
  @override
  double get scaled2xsmallMobile => DimensionRawTokens.dimension50;
  @override
  double get scaled2xsmallTablet => DimensionRawTokens.dimension100;
  @override
  double get scaled3xlargeMobile => DimensionRawTokens.dimension550;
  @override
  double get scaled3xlargeTablet => DimensionRawTokens.dimension650;
  @override
  double get scaled3xsmallMobile => DimensionRawTokens.dimensionOutOfSystem50;
  @override
  double get scaled3xsmallTablet => DimensionRawTokens.dimension50;
  @override
  double get scaledLargeMobile => DimensionRawTokens.dimension250;
  @override
  double get scaledLargeTablet => DimensionRawTokens.dimension350;
  @override
  double get scaledMediumMobile => DimensionRawTokens.dimension150;
  @override
  double get scaledMediumTablet => DimensionRawTokens.dimension250;
  @override
  double get scaledNoneMobile => DimensionRawTokens.dimension0;
  @override
  double get scaledNoneTablet => DimensionRawTokens.dimension0;
  @override
  double get scaledSmallMobile => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get scaledSmallTablet => DimensionRawTokens.dimension150;
  @override
  double get scaledXlargeMobile => DimensionRawTokens.dimension350;
  @override
  double get scaledXlargeTablet => DimensionRawTokens.dimension450;
  @override
  double get scaledXsmallMobile => DimensionRawTokens.dimension100;
  @override
  double get scaledXsmallTablet => DimensionRawTokens.dimensionOutOfSystem250;
}
