//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange Compact brand tokens version 2.6.0
// Generated by Tokenator

import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_ai_semantic_tokens.dart';

class OrangeCompactColorAiSemanticTokens extends OudsColorAiSemanticTokens {
  const OrangeCompactColorAiSemanticTokens({
    super.aiPrimaryDark = OrangeColorRawTokens.colorOrange500,
    super.aiPrimaryLight = OrangeColorRawTokens.colorOrange550,
    super.aiQuaternaryDark = OrangeColorRawTokens.colorDecorativeSky400,
    super.aiQuaternaryLight = OrangeColorRawTokens.colorDecorativeSky400,
    super.aiSecondaryDark = OrangeColorRawTokens.colorDecorativeShockingPink200,
    super.aiSecondaryLight = OrangeColorRawTokens.colorDecorativeShockingPink200,
    super.aiTertiaryDark = OrangeColorRawTokens.colorDecorativeAmethyst400,
    super.aiTertiaryLight = OrangeColorRawTokens.colorDecorativeAmethyst400,
  });
}
