//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

<<<<<<<< HEAD:ouds_theme_orange_compact/lib/semantic/orangeCompact_border_semantic_tokens.dart
// Orange Compact brand tokens version 2.3.0
========
// Sosh brand tokens version 2.3.0
>>>>>>>> main:ouds_theme_sosh/lib/semantic/sosh_border_semantic_tokens.dart
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_border_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/border_raw_tokens.dart';

<<<<<<<< HEAD:ouds_theme_orange_compact/lib/semantic/orangeCompact_border_semantic_tokens.dart
class OrangeCompactBorderSemanticTokens extends OudsBorderSemanticTokens {
========
class SoshBorderSemanticTokens extends OudsBorderSemanticTokens {
>>>>>>>> main:ouds_theme_sosh/lib/semantic/sosh_border_semantic_tokens.dart
  @override
  double get radiusDefault => BorderRawTokens.borderRadius100;
  @override
  double get radiusLarge => BorderRawTokens.borderRadius300;
  @override
  double get radiusMedium => BorderRawTokens.borderRadius200;
  @override
  double get radiusNone => BorderRawTokens.borderRadius0;
  @override
  double get radiusPill => BorderRawTokens.borderRadius9999;
  @override
<<<<<<<< HEAD:ouds_theme_orange_compact/lib/semantic/orangeCompact_border_semantic_tokens.dart
  double get radiusSmall => BorderRawTokens.borderRadius100;
========
  double get radiusSmall => BorderRawTokens.borderRadius150;
>>>>>>>> main:ouds_theme_sosh/lib/semantic/sosh_border_semantic_tokens.dart
  @override
  String get styleDefault => BorderRawTokens.borderStyleSolid;
  @override
  String get styleDrag => BorderRawTokens.borderStyleDashed;
  @override
  double get widthDefault => BorderRawTokens.borderWidth50;
  @override
  double get widthFocus => BorderRawTokens.borderWidth125;
  @override
  double get widthFocusInset => BorderRawTokens.borderWidth50;
  @override
  double get widthMedium => BorderRawTokens.borderWidth75;
  @override
  double get widthNone => BorderRawTokens.borderWidth0;
  @override
  double get widthThick => BorderRawTokens.borderWidth100;
  @override
  double get widthThicker => BorderRawTokens.borderWidth150;
  @override
  double get widthThin => BorderRawTokens.borderWidth25;
}
