//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_button_tokens.dart';

class SoshButtonTokens extends OudsButtonTokens {
  final OudsProvidersTokens providersTokens;

  SoshButtonTokens(this.providersTokens);

  @override
  double get borderRadiusAiIconOnly => providersTokens.borderTokens.radiusPill;
  @override
  double get borderRadiusDefault => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusRounded => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusSocial => providersTokens.borderTokens.radiusPill;
  @override
  double get borderWidthAi => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthAiInteraction => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthDefault => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthDefaultInteraction => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthDefaultInteractionMono => providersTokens.borderTokens.widthNone;
  @override
  Color get colorBgAiDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgAiEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgAiFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgAiHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgAiLoading => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgAiPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgBrandEnabled => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.surfaceBrandSecondary, providersTokens.colorScheme.surfaceBrandTertiary);
  @override
  Color get colorBgBrandFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBgBrandHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBgBrandLoading => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPrimaryMedium, providersTokens.colorScheme.repositorySecondaryLower);
  @override
  Color get colorBgBrandPressed => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPrimaryMedium, providersTokens.colorScheme.repositorySecondaryLower);
  @override
  Color get colorBgDefaultDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultLoading => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgMinimalFocus => providersTokens.colorScheme.actionSupportFocus;
  @override
  Color get colorBgMinimalHover => providersTokens.colorScheme.actionSupportHover;
  @override
  Color get colorBgMinimalPressed => providersTokens.colorScheme.actionSupportPressed;
  @override
  Color get colorBorderAiDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBorderAiEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderAiFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderAiHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderAiLoading => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderAiPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderDefaultDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBorderDefaultEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorBorderDefaultFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBorderDefaultHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBorderDefaultLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorBorderDefaultPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentAiDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentAiEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentAiFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentAiHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentAiLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorContentAiPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentBrandEnabled => providersTokens.colorScheme.contentOnBrandSecondary;
  @override
  Color get colorContentBrandFocus => providersTokens.colorScheme.contentOnActionFocus;
  @override
  Color get colorContentBrandHover => providersTokens.colorScheme.contentOnActionHover;
  @override
  Color get colorContentBrandLoading => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralMutedWhite, providersTokens.colorScheme.repositoryNeutralEmphasizedBlack);
  @override
  Color get colorContentBrandPressed => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralMutedWhite, providersTokens.colorScheme.repositoryNeutralEmphasizedBlack);
  @override
  Color get colorContentDefaultDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentDefaultEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentDefaultFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentDefaultHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentDefaultLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorContentDefaultPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentMinimalDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentMinimalEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentMinimalFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentMinimalHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentMinimalLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorContentMinimalPressed => providersTokens.colorScheme.actionPressed;
  @override
  double get sizeIconDefault => providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeIconOnlyDefault => providersTokens.sizeTokens.iconWithLabelLargeSizeSmall;
  @override
  double get sizeIconOnlySmall => providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeIconSmall => providersTokens.sizeTokens.iconWithLabelMediumSizeSmall;
  @override
  double get sizeMaxWidthHeightIconOnlyDefault => providersTokens.sizeTokens.minInteractiveAreaDefault;
  @override
  double get sizeMaxWidthHeightIconOnlySmall => providersTokens.sizeTokens.minInteractiveAreaSmall;
  @override
  double get sizeMinHeightDefault => providersTokens.sizeTokens.minInteractiveAreaDefault;
  @override
  double get sizeMinHeightSmall => providersTokens.sizeTokens.minInteractiveAreaSmall;
  @override
  double get sizeMinWidthDefault => providersTokens.sizeTokens.minInteractiveAreaDefault;
  @override
  double get sizeMinWidthSmall => providersTokens.sizeTokens.minInteractiveAreaSmall;
  @override
  double get sizeProgressIndicatorDefault => providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeProgressIndicatorSmall => providersTokens.sizeTokens.iconWithLabelMediumSizeSmall;
  @override
  double get spaceColumnGapChevronDefault => providersTokens.spaceTokens.columnGapXsmall;
  @override
  double get spaceColumnGapChevronSmall => providersTokens.spaceTokens.columnGap2xsmall;
  @override
  double get spaceColumnGapIconChevronDefault => providersTokens.spaceTokens.columnGap2xsmall;
  @override
  double get spaceColumnGapIconChevronSmall => providersTokens.spaceTokens.columnGap3xsmall;
  @override
  double get spaceColumnGapIconDefault => providersTokens.spaceTokens.columnGapSmall;
  @override
  double get spaceColumnGapIconSmall => providersTokens.spaceTokens.columnGapXsmall;
  @override
  double get spaceInsetIconOnlyDefault => providersTokens.spaceTokens.insetMedium;
  @override
  double get spaceInsetIconOnlySmall => providersTokens.spaceTokens.insetSmall;
  @override
  double get spaceInsetProgressIndicartorOnlyDefault => providersTokens.spaceTokens.inset4xsmall;
  @override
  double get spaceInsetProgressIndicartorOnlySmall => providersTokens.spaceTokens.inset4xsmall;
  @override
  double get spacePaddingBlockDefault => providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingBlockSmall => providersTokens.spaceTokens.paddingBlockSmall;
  @override
  double get spacePaddingInlineChevronEndDefault => providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spacePaddingInlineChevronEndSmall => providersTokens.spaceTokens.paddingInlineMedium;
  @override
  double get spacePaddingInlineChevronStartDefault => providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spacePaddingInlineChevronStartSmall => providersTokens.spaceTokens.paddingInlineMedium;
  @override
  double get spacePaddingInlineEndIconStartDefault => providersTokens.spaceTokens.paddingInline3xlarge;
  @override
  double get spacePaddingInlineEndIconStartSmall => providersTokens.spaceTokens.paddingInline2xlarge;
  @override
  double get spacePaddingInlineIconNoneDefault => providersTokens.spaceTokens.paddingInline4xlarge;
  @override
  double get spacePaddingInlineIconNoneSmall => providersTokens.spaceTokens.paddingInline2xlarge;
  @override
  double get spacePaddingInlineIconStartDefault => providersTokens.spaceTokens.paddingInlineXlarge;
  @override
  double get spacePaddingInlineIconStartSmall => providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spacePaddingInlineStartIconEndDefault => providersTokens.spaceTokens.paddingInline3xlarge;
  @override
  double get spacePaddingInlineStartIconEndSmall => providersTokens.spaceTokens.paddingInline2xlarge;
}
