//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 1.2.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_tag_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class SoshTagTokens extends OudsTagTokens {
  @override
  double get borderRadius => providersTokens.borderTokens.radiusPill;
  @override
  double get sizeIconDefault => providersTokens.sizeTokens.iconWithLabelMediumSizeSm;
  @override
  double get sizeIconSmall => providersTokens.sizeTokens.iconWithLabelSmallSizeSm;
  @override
  double get sizeMinHeightDefault => DimensionRawTokens.dimension400;
  @override
  double get sizeMinHeightInteractiveArea => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinHeightSmall => DimensionRawTokens.dimension300;
  @override
  double get sizeMinWidthDefault => DimensionRawTokens.dimension600;
  @override
  double get sizeMinWidthSmall => DimensionRawTokens.dimension550;
  @override
  double get spaceColumnGapDefault => providersTokens.spaceTokens.columnGap2xs;
  @override
  double get spaceColumnGapSmall => providersTokens.spaceTokens.columnGap2xs;
  @override
  double get spaceInsetDefaultAsset => providersTokens.spaceTokens.inset3xs;
  @override
  double get spaceInsetSmallAsset => providersTokens.spaceTokens.inset4xs;
  @override
  double get spacePaddingBlockDefault => providersTokens.spaceTokens.paddingBlockXs;
  @override
  double get spacePaddingBlockSmall => providersTokens.spaceTokens.paddingBlock2xs;
  @override
  double get spacePaddingInlineDefault => providersTokens.spaceTokens.paddingInlineMd;
  @override
  double get spacePaddingInlineDefaultAsset => providersTokens.spaceTokens.paddingInlineXs;
  @override
  double get spacePaddingInlineSmall => providersTokens.spaceTokens.paddingInlineSm;
  @override
  double get spacePaddingInlineSmallAsset => providersTokens.spaceTokens.paddingInline2xs;
}
