//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.0.1
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_inputTag_tokens.dart';

class SoshInputTagTokens extends OudsInputTagTokens {
  final OudsProvidersTokens providersTokens;

  SoshInputTagTokens(this.providersTokens);

  @override
  double get borderWidthDefault => providersTokens.borderTokens.widthThin;
  @override
  double get borderWidthDefaultInteraction => providersTokens.borderTokens.widthDefault;
  @override
  Color get colorBgEnabled => providersTokens.colorScheme.actionSupportEnabled;
  @override
  Color get colorBgFocus => providersTokens.colorScheme.actionSupportFocus;
  @override
  Color get colorBgHover => providersTokens.colorScheme.actionSupportHover;
  @override
  Color get colorBgPressed => providersTokens.colorScheme.actionSupportPressed;
  @override
  Color get colorBorderEnabled => providersTokens.colorScheme.borderDefault;
  @override
  Color get colorBorderFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBorderHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBorderPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentEnabled => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorContentFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentPressed => providersTokens.colorScheme.actionPressed;
}
