//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.2.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_checkbox_tokens.dart';

class SoshCheckboxTokens extends OudsCheckboxTokens {
  final OudsProvidersTokens providersTokens;

  SoshCheckboxTokens(this.providersTokens);

  @override
  double get borderRadius => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderWidthSelected => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthSelectedFocus => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthSelectedHover => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthSelectedPressed => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthUnselected => providersTokens.borderTokens.widthThin;
  @override
  double get borderWidthUnselectedFocus => providersTokens.borderTokens.widthMedium;
  @override
  double get borderWidthUnselectedHover => providersTokens.borderTokens.widthMedium;
  @override
  double get borderWidthUnselectedPressed => providersTokens.borderTokens.widthMedium;
  @override
  double get sizeIndicator => providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeMaxHeight => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinHeight => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinWidth => providersTokens.sizeTokens.minInteractiveArea;
}
