//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.4.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_global_raw_tokens/effect_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_bar_tokens.dart';

class SoshBarTokens extends OudsBarTokens {
  final OudsProvidersTokens providersTokens;

  SoshBarTokens(this.providersTokens);

  @override
  double get borderRadiusCurrentIndicatorCustomBottom => providersTokens.borderTokens.radiusPill;
  @override
  double get borderRadiusCurrentIndicatorCustomTop => providersTokens.borderTokens.radiusDefault;
  @override
  Color get colorBgOpaque => providersTokens.colorScheme.bgSecondary;
  @override
  Color get colorBgTranslucentDark => ColorRawTokens.colorOpacityBlueDuckDark960800;
  @override
  Color get colorBgTranslucentLight => ColorRawTokens.colorOpacityWhite800;
  @override
  Color get colorBorderBadge => providersTokens.colorScheme.bgSecondary;
  @override
  Color get colorContentOnIosAccent => providersTokens.colorScheme.contentOnActionSelected;
  @override
  Color get colorContentSelectedEnabled => providersTokens.colorScheme.actionSelected;
  @override
  Color get colorContentSelectedFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentSelectedHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentSelectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentUnselectedEnabled => providersTokens.colorScheme.contentMuted;
  @override
  Color get colorContentUnselectedFocus => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorContentUnselectedHover => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorContentUnselectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorCurrentIndicatorAndroidSelectedDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidSelectedEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidSelectedFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidSelectedHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidSelectedPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidUnselectedDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidUnselectedFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidUnselectedHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorAndroidUnselectedPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorCurrentIndicatorCustomSelectedEnabled => providersTokens.colorScheme.actionSelected;
  @override
  Color get colorCurrentIndicatorCustomSelectedFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorCurrentIndicatorCustomSelectedHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorCurrentIndicatorCustomSelectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorIosAccent => providersTokens.colorScheme.actionSelected;
  @override
  int get effectBgBlur => EffectRawTokens.effectBlur320;
  @override
  double get opacityCurrentIndicatorCustom => providersTokens.opacityTokens.opaque;
  @override
  double get sizeHeightCurrentIndicatorCustom => DimensionRawTokens.dimensionOutOfSystem75;
  @override
  double get sizeWidthCurrentIndicatorCustomBottom => DimensionRawTokens.dimension300;
  @override
  double get sizeWidthCurrentIndicatorCustomTop => DimensionRawTokens.dimension500;
}
