//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_icon_tokens.dart';

class SoshIconTokens extends OudsIconTokens {
  final OudsProvidersTokens providersTokens;

  SoshIconTokens(this.providersTokens);

  @override
  Color get colorContentStatusWarningExternalShape => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryWarningMedium, providersTokens.colorScheme.repositoryWarningLow);
  @override
  Color get colorContentStatusWarningInternalShape => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryWarningHigh, providersTokens.colorScheme.opacityTransparent);
  @override
  Color get colorContentStatusWarningInverseExternalShape => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryWarningLow, providersTokens.colorScheme.repositoryWarningMedium);
  @override
  Color get colorContentStatusWarningInverseInternalShape => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.opacityTransparent, providersTokens.colorScheme.repositoryWarningHigh);
}
