//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_alert_tokens.dart';

class SoshAlertTokens extends OudsAlertTokens {
  final OudsProvidersTokens providersTokens;

  SoshAlertTokens(this.providersTokens);

  @override
  double get borderRadiusDefault => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusRounded => providersTokens.borderTokens.radiusLarge;
  @override
  double get borderWidth => providersTokens.borderTokens.widthNone;
  @override
  double get sizeIcon => providersTokens.sizeTokens.iconWithLabelLargeSizeSmall;
  @override
  double get sizeMinHeight => providersTokens.sizeTokens.minInteractiveAreaDefault;
  @override
  double get sizeMinHeightBottomActionPlacement => DimensionRawTokens.dimension1250;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension2000;
  @override
  double get spaceColumnGap => providersTokens.spaceTokens.columnGapMedium;
  @override
  double get spaceColumnGapAction => providersTokens.spaceTokens.columnGapSmall;
  @override
  double get spacePaddingBlock => providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingInline => providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spaceRowGap => providersTokens.spaceTokens.rowGapSmall;
  @override
  double get spaceRowGapAction => providersTokens.spaceTokens.rowGap2xsmall;
  @override
  double get spaceRowGapBullet => providersTokens.spaceTokens.rowGapNone;
}
