//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 1.3.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_button_tokens.dart';

class SoshButtonTokens extends OudsButtonTokens {
  final OudsProvidersTokens providersTokens;

  SoshButtonTokens(this.providersTokens);

  @override
  double get borderRadius => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderWidthDefault => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthDefaultInteraction => providersTokens.borderTokens.widthDefault;
  @override
  double get borderWidthDefaultInteractionMono => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthMinimal => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthMinimalInteraction => providersTokens.borderTokens.widthNone;
  @override
  Color get colorBgDefaultDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultLoading => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgDefaultPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgMinimalDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgMinimalEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgMinimalFocus => providersTokens.colorScheme.actionSupportFocus;
  @override
  Color get colorBgMinimalHover => providersTokens.colorScheme.actionSupportHover;
  @override
  Color get colorBgMinimalLoading => providersTokens.colorScheme.actionSupportLoading;
  @override
  Color get colorBgMinimalPressed => providersTokens.colorScheme.actionSupportPressed;
  @override
  Color get colorBorderDefaultDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBorderDefaultEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorBorderDefaultFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBorderDefaultHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBorderDefaultLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorBorderDefaultPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorBorderMinimalDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderMinimalEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderMinimalFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderMinimalHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderMinimalLoading => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderMinimalPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorContentDefaultDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentDefaultEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentDefaultFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentDefaultHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentDefaultLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorContentDefaultPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentMinimalDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentMinimalEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentMinimalFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentMinimalHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentMinimalLoading => providersTokens.colorScheme.actionLoading;
  @override
  Color get colorContentMinimalPressed => providersTokens.colorScheme.actionPressed;
  @override
  double get sizeIcon => providersTokens.sizeTokens.iconWithLabelLargeSizeXs;
  @override
  double get sizeIconOnly => providersTokens.sizeTokens.iconWithLabelLargeSizeSm;
  @override
  double get sizeLoader => providersTokens.sizeTokens.iconWithLabelLargeSizeXs;
  @override
  double get sizeMaxHeightIconOnly => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinHeight => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinWidth => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get spaceColumnGapChevron => providersTokens.spaceTokens.columnGapXs;
  @override
  double get spaceColumnGapIcon => providersTokens.spaceTokens.columnGapSm;
  @override
  double get spaceColumnGapIconChevron => providersTokens.spaceTokens.columnGap2xs;
  @override
  double get spaceInsetIconOnly => providersTokens.spaceTokens.insetMd;
  @override
  double get spacePaddingBlock => providersTokens.spaceTokens.paddingBlockMd;
  @override
  double get spacePaddingInlineChevronEnd => providersTokens.spaceTokens.paddingInlineLg;
  @override
  double get spacePaddingInlineChevronStart => providersTokens.spaceTokens.paddingInlineLg;
  @override
  double get spacePaddingInlineEndIconStart => providersTokens.spaceTokens.paddingInline3xl;
  @override
  double get spacePaddingInlineIconNone => providersTokens.spaceTokens.paddingInline4xl;
  @override
  double get spacePaddingInlineIconStart => providersTokens.spaceTokens.paddingInlineXl;
  @override
  double get spacePaddingInlineStartIconEnd => providersTokens.spaceTokens.paddingInline3xl;
}
