//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.1.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_badge_tokens.dart';

class SoshBadgeTokens extends OudsBadgeTokens {
  final OudsProvidersTokens providersTokens;

  SoshBadgeTokens(this.providersTokens);

  @override
  double get sizeLarge => DimensionRawTokens.dimension250;
  @override
  double get sizeMedium => DimensionRawTokens.dimension200;
  @override
  double get sizeSmall => DimensionRawTokens.dimension150;
  @override
  double get sizeXsmall => DimensionRawTokens.dimension100;
  @override
  double get spaceInset => DimensionRawTokens.dimensionOutOfSystem75;
  @override
  double get spacePaddingInlineLarge => providersTokens.spaceTokens.paddingInline2xsmall;
  @override
  double get spacePaddingInlineMedium => providersTokens.spaceTokens.paddingInline3xsmall;
}
