//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 1.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_textInput_tokens.dart';

class SoshTextInputTokens extends OudsTextInputTokens {
  final OudsProvidersTokens providersTokens;

  SoshTextInputTokens(this.providersTokens);

  @override
  double get borderRadiusDefault => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusRounded => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderWidthDefault => providersTokens.borderTokens.widthThin;
  @override
  double get borderWidthFocus => providersTokens.borderTokens.widthMedium;
  @override
  Color get colorBorderEnabled => providersTokens.colorScheme.borderDefault;
  @override
  Color get colorBorderFocus => providersTokens.colorScheme.borderEmphasized;
  @override
  Color get colorBorderHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBorderLoading => providersTokens.colorScheme.borderEmphasized;
  @override
  double get sizeCountrySelectorFlagHeight => providersTokens.sizeTokens.iconWithLabelLargeSizeXs;
  @override
  double get sizeLabelMaxHeight => DimensionRawTokens.dimension600;
  @override
  double get sizeLeadingIcon => providersTokens.sizeTokens.iconWithLabelLargeSizeSm;
  @override
  double get sizeMaxWidth => DimensionRawTokens.dimension4000;
  @override
  double get sizeMinHeight => DimensionRawTokens.dimension750;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension2500;
  @override
  double get sizeVerticalDividerHeight => DimensionRawTokens.dimension250;
  @override
  double get spaceColumnGapDefault => providersTokens.spaceTokens.columnGapMd;
  @override
  double get spaceColumnGapInlineText => providersTokens.spaceTokens.columnGapXs;
  @override
  double get spaceColumnGapTrailingErrorAction => providersTokens.spaceTokens.columnGapXs;
  @override
  double get spacePaddingBlockDefault => providersTokens.spaceTokens.paddingBlock2xs;
  @override
  double get spacePaddingBlockTopHelperText => providersTokens.spaceTokens.paddingBlockXs;
  @override
  double get spacePaddingInlineCountrySelectorEnd => providersTokens.spaceTokens.paddingInlineXs;
  @override
  double get spacePaddingInlineCountrySelectorStart => providersTokens.spaceTokens.paddingInlineSm;
  @override
  double get spacePaddingInlineDefault => providersTokens.spaceTokens.paddingInlineLg;
  @override
  double get spacePaddingInlineTrailingAction => providersTokens.spaceTokens.paddingInline2xs;
  @override
  double get spaceRowGapLabelInput => providersTokens.spaceTokens.rowGapNone;
}
