//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 1.2.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_chip_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class SoshChipTokens extends OudsChipTokens {
  @override
  Color get badgeColorBg => providersTokens.colorScheme.contentOnActionEnabled;
  @override
  Color get badgeColorContent => providersTokens.colorScheme.contentDefault;
  @override
  double get borderRadius => providersTokens.borderTokens.radiusPill;
  @override
  double get borderWidthSelected => providersTokens.borderTokens.widthNone;
  @override
  double get borderWidthUnselected => providersTokens.borderTokens.widthThin;
  @override
  double get borderWidthUnselectedInteraction => providersTokens.borderTokens.widthDefault;
  @override
  Color get colorBgSelectedDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBgSelectedEnabled => providersTokens.colorScheme.actionSelected;
  @override
  Color get colorBgSelectedFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBgSelectedHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBgSelectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorBgUnselectedDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgUnselectedEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgUnselectedFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgUnselectedHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBgUnselectedPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderSelectedDisabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderSelectedEnabled => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderSelectedFocus => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderSelectedHover => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderSelectedPressed => providersTokens.colorScheme.opacityTransparent;
  @override
  Color get colorBorderUnselectedDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBorderUnselectedEnabled => providersTokens.colorScheme.borderEmphasized;
  @override
  Color get colorBorderUnselectedFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBorderUnselectedHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBorderUnselectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentSelectedDisabled => providersTokens.colorScheme.contentOnActionDisabled;
  @override
  Color get colorContentSelectedEnabled => providersTokens.colorScheme.contentOnActionSelected;
  @override
  Color get colorContentSelectedFocus => providersTokens.colorScheme.contentOnActionFocus;
  @override
  Color get colorContentSelectedHover => providersTokens.colorScheme.contentOnActionHover;
  @override
  Color get colorContentSelectedPressed => providersTokens.colorScheme.contentOnActionPressed;
  @override
  Color get colorContentSelectedTickEnabled => providersTokens.colorScheme.contentOnActionSelected;
  @override
  Color get colorContentUnselectedDisabled => providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorContentUnselectedEnabled => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorContentUnselectedFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentUnselectedHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentUnselectedPressed => providersTokens.colorScheme.actionPressed;
  @override
  double get sizeIcon => providersTokens.sizeTokens.iconWithLabelMediumSizeSm;
  @override
  double get sizeMinHeight => DimensionRawTokens.dimension400;
  @override
  double get sizeMinHeightInteractiveArea => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension650;
  @override
  double get spaceColumnGapBadgeArrow => providersTokens.spaceTokens.columnGap2xs;
  @override
  double get spaceColumnGapIcon => providersTokens.spaceTokens.columnGapXs;
  @override
  double get spacePaddingBlock => providersTokens.spaceTokens.paddingBlockXs;
  @override
  double get spacePaddingBlockIconOnly => providersTokens.spaceTokens.paddingBlockSm;
  @override
  double get spacePaddingInlineArrowEnd => providersTokens.spaceTokens.paddingInlineXs;
  @override
  double get spacePaddingInlineBadgeStart => providersTokens.spaceTokens.paddingInline4xs;
  @override
  double get spacePaddingInlineIcon => providersTokens.spaceTokens.paddingInlineSm;
  @override
  double get spacePaddingInlineIconNone => providersTokens.spaceTokens.paddingInlineLg;
}
