name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - app
  - ouds_core
  - ouds_global_raw_tokens
  - ouds_theme_contract
  - ouds_theme_orange
  - ouds_theme_sosh
  - ouds_accessibility_plugin
  - ouds_theme_wireframe
  - ouds_theme_orange_compact
dependencies:
  flutter_svg: ^2.2.3
