name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - app
  - ouds_core
  - ouds_global_raw_tokens
  - ouds_theme_contract
  - ouds_theme_orange
  - ouds_theme_orange_country
  - ouds_theme_white_label
dependencies:
  flutter_svg: ^2.2.0
