//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Android system tokens version 1.2.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsMaterialColorTokens {
  final Color backgroundDark;
  final Color backgroundLight;
  final Color errorContainerDark;
  final Color errorContainerLight;
  final Color errorDark;
  final Color errorLight;
  final Color inverseOnSurfaceDark;
  final Color inverseOnSurfaceLight;
  final Color inversePrimaryDark;
  final Color inversePrimaryLight;
  final Color inverseSurfaceDark;
  final Color inverseSurfaceLight;
  final Color onBackgroundDark;
  final Color onBackgroundLight;
  final Color onErrorContainerDark;
  final Color onErrorContainerLight;
  final Color onErrorDark;
  final Color onErrorLight;
  final Color onPrimaryContainerDark;
  final Color onPrimaryContainerLight;
  final Color onPrimaryDark;
  final Color onPrimaryFixedDark;
  final Color onPrimaryFixedLight;
  final Color onPrimaryFixedVariantDark;
  final Color onPrimaryFixedVariantLight;
  final Color onPrimaryLight;
  final Color onSecondaryContainerDark;
  final Color onSecondaryContainerLight;
  final Color onSecondaryDark;
  final Color onSecondaryFixedDark;
  final Color onSecondaryFixedLight;
  final Color onSecondaryFixedVariantDark;
  final Color onSecondaryFixedVariantLight;
  final Color onSecondaryLight;
  final Color onSurfaceDark;
  final Color onSurfaceLight;
  final Color onSurfaceVariantDark;
  final Color onSurfaceVariantLight;
  final Color onTertiaryContainerDark;
  final Color onTertiaryContainerLight;
  final Color onTertiaryDark;
  final Color onTertiaryFixedDark;
  final Color onTertiaryFixedLight;
  final Color onTertiaryFixedVariantDark;
  final Color onTertiaryFixedVariantLight;
  final Color onTertiaryLight;
  final Color outlineDark;
  final Color outlineLight;
  final Color outlineVariantDark;
  final Color outlineVariantLight;
  final Color primaryContainerDark;
  final Color primaryContainerLight;
  final Color primaryDark;
  final Color primaryFixedDark;
  final Color primaryFixedDimDark;
  final Color primaryFixedDimLight;
  final Color primaryFixedLight;
  final Color primaryLight;
  final Color scrimDark;
  final Color scrimLight;
  final Color secondaryContainerDark;
  final Color secondaryContainerLight;
  final Color secondaryDark;
  final Color secondaryFixedDark;
  final Color secondaryFixedDimDark;
  final Color secondaryFixedDimLight;
  final Color secondaryFixedLight;
  final Color secondaryLight;
  final Color surfaceBrightDark;
  final Color surfaceBrightLight;
  final Color surfaceDark;
  final Color surfaceDimDark;
  final Color surfaceDimLight;
  final Color surfaceLight;
  final Color surfaceTintDark;
  final Color surfaceTintLight;
  final Color surfaceVariantDark;
  final Color surfaceVariantLight;
  final Color surfContainerDark;
  final Color surfContainerHighDark;
  final Color surfContainerHighestDark;
  final Color surfContainerHighestLight;
  final Color surfContainerHighLight;
  final Color surfContainerLight;
  final Color surfContainerLowDark;
  final Color surfContainerLowestDark;
  final Color surfContainerLowestLight;
  final Color surfContainerLowLight;
  final Color tertiaryContainerDark;
  final Color tertiaryContainerLight;
  final Color tertiaryDark;
  final Color tertiaryFixedDark;
  final Color tertiaryFixedDimDark;
  final Color tertiaryFixedDimLight;
  final Color tertiaryFixedLight;
  final Color tertiaryLight;

  const OudsMaterialColorTokens({
    required this.backgroundDark,
    required this.backgroundLight,
    required this.errorContainerDark,
    required this.errorContainerLight,
    required this.errorDark,
    required this.errorLight,
    required this.inverseOnSurfaceDark,
    required this.inverseOnSurfaceLight,
    required this.inversePrimaryDark,
    required this.inversePrimaryLight,
    required this.inverseSurfaceDark,
    required this.inverseSurfaceLight,
    required this.onBackgroundDark,
    required this.onBackgroundLight,
    required this.onErrorContainerDark,
    required this.onErrorContainerLight,
    required this.onErrorDark,
    required this.onErrorLight,
    required this.onPrimaryContainerDark,
    required this.onPrimaryContainerLight,
    required this.onPrimaryDark,
    required this.onPrimaryFixedDark,
    required this.onPrimaryFixedLight,
    required this.onPrimaryFixedVariantDark,
    required this.onPrimaryFixedVariantLight,
    required this.onPrimaryLight,
    required this.onSecondaryContainerDark,
    required this.onSecondaryContainerLight,
    required this.onSecondaryDark,
    required this.onSecondaryFixedDark,
    required this.onSecondaryFixedLight,
    required this.onSecondaryFixedVariantDark,
    required this.onSecondaryFixedVariantLight,
    required this.onSecondaryLight,
    required this.onSurfaceDark,
    required this.onSurfaceLight,
    required this.onSurfaceVariantDark,
    required this.onSurfaceVariantLight,
    required this.onTertiaryContainerDark,
    required this.onTertiaryContainerLight,
    required this.onTertiaryDark,
    required this.onTertiaryFixedDark,
    required this.onTertiaryFixedLight,
    required this.onTertiaryFixedVariantDark,
    required this.onTertiaryFixedVariantLight,
    required this.onTertiaryLight,
    required this.outlineDark,
    required this.outlineLight,
    required this.outlineVariantDark,
    required this.outlineVariantLight,
    required this.primaryContainerDark,
    required this.primaryContainerLight,
    required this.primaryDark,
    required this.primaryFixedDark,
    required this.primaryFixedDimDark,
    required this.primaryFixedDimLight,
    required this.primaryFixedLight,
    required this.primaryLight,
    required this.scrimDark,
    required this.scrimLight,
    required this.secondaryContainerDark,
    required this.secondaryContainerLight,
    required this.secondaryDark,
    required this.secondaryFixedDark,
    required this.secondaryFixedDimDark,
    required this.secondaryFixedDimLight,
    required this.secondaryFixedLight,
    required this.secondaryLight,
    required this.surfaceBrightDark,
    required this.surfaceBrightLight,
    required this.surfaceDark,
    required this.surfaceDimDark,
    required this.surfaceDimLight,
    required this.surfaceLight,
    required this.surfaceTintDark,
    required this.surfaceTintLight,
    required this.surfaceVariantDark,
    required this.surfaceVariantLight,
    required this.surfContainerDark,
    required this.surfContainerHighDark,
    required this.surfContainerHighestDark,
    required this.surfContainerHighestLight,
    required this.surfContainerHighLight,
    required this.surfContainerLight,
    required this.surfContainerLowDark,
    required this.surfContainerLowestDark,
    required this.surfContainerLowestLight,
    required this.surfContainerLowLight,
    required this.tertiaryContainerDark,
    required this.tertiaryContainerLight,
    required this.tertiaryDark,
    required this.tertiaryFixedDark,
    required this.tertiaryFixedDimDark,
    required this.tertiaryFixedDimLight,
    required this.tertiaryFixedLight,
    required this.tertiaryLight,
  });
}
