//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Android system tokens version 1.0.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OudsMaterialColorTokens {
  Color backgroundDark = ColorRawTokens.colorFunctionalGrayDark880;
  Color backgroundLight = ColorRawTokens.colorFunctionalWhite;
  Color errorContainerDark = ColorRawTokens.colorFunctionalScarlet900;
  Color errorContainerLight = ColorRawTokens.colorFunctionalScarlet100;
  Color errorDark = ColorRawTokens.colorFunctionalScarlet300;
  Color errorLight = ColorRawTokens.colorFunctionalScarlet600;
  Color inverseOnSurfaceDark = ColorRawTokens.colorFunctionalBlack;
  Color inverseOnSurfaceLight = ColorRawTokens.colorFunctionalWhite;
  Color inversePrimaryDark = ColorRawTokens.colorFunctionalBlack;
  Color inversePrimaryLight = ColorRawTokens.colorFunctionalWhite;
  Color inverseSurfaceDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color inverseSurfaceLight = ColorRawTokens.colorFunctionalGrayDark720;
  Color onBackgroundDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onBackgroundLight = ColorRawTokens.colorFunctionalBlack;
  Color onErrorContainerDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onErrorContainerLight = ColorRawTokens.colorFunctionalBlack;
  Color onErrorDark = ColorRawTokens.colorFunctionalBlack;
  Color onErrorLight = ColorRawTokens.colorFunctionalWhite;
  Color onPrimaryContainerDark = ColorRawTokens.colorFunctionalBlack;
  Color onPrimaryContainerLight = ColorRawTokens.colorFunctionalWhite;
  Color onPrimaryDark = ColorRawTokens.colorFunctionalBlack;
  Color onPrimaryFixedDark = ColorRawTokens.colorFunctionalWhite;
  Color onPrimaryFixedLight = ColorRawTokens.colorFunctionalWhite;
  Color onPrimaryFixedVariantDark = ColorRawTokens.colorOpacityWhite640;
  Color onPrimaryFixedVariantLight = ColorRawTokens.colorOpacityWhite640;
  Color onPrimaryLight = ColorRawTokens.colorFunctionalGrayLight160;
  Color onSecondaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onSecondaryContainerLight = ColorRawTokens.colorFunctionalBlack;
  Color onSecondaryDark = ColorRawTokens.colorFunctionalBlack;
  Color onSecondaryFixedDark = ColorRawTokens.colorFunctionalWhite;
  Color onSecondaryFixedLight = ColorRawTokens.colorFunctionalWhite;
  Color onSecondaryFixedVariantDark = ColorRawTokens.colorOpacityWhite640;
  Color onSecondaryFixedVariantLight = ColorRawTokens.colorOpacityWhite640;
  Color onSecondaryLight = ColorRawTokens.colorFunctionalGrayLight160;
  Color onSurfaceDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onSurfaceLight = ColorRawTokens.colorFunctionalBlack;
  Color onSurfaceVariantDark = ColorRawTokens.colorOpacityWhite640;
  Color onSurfaceVariantLight = ColorRawTokens.colorOpacityBlack680;
  Color onTertiaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onTertiaryContainerLight = ColorRawTokens.colorFunctionalBlack;
  Color onTertiaryDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color onTertiaryFixedDark = ColorRawTokens.colorFunctionalBlack;
  Color onTertiaryFixedLight = ColorRawTokens.colorFunctionalBlack;
  Color onTertiaryFixedVariantDark = ColorRawTokens.colorOpacityBlack680;
  Color onTertiaryFixedVariantLight = ColorRawTokens.colorOpacityBlack680;
  Color onTertiaryLight = ColorRawTokens.colorFunctionalBlack;
  Color outlineDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color outlineLight = ColorRawTokens.colorFunctionalBlack;
  Color outlineVariantDark = ColorRawTokens.colorOpacityWhite200;
  Color outlineVariantLight = ColorRawTokens.colorOpacityBlack200;
  Color primaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color primaryContainerLight = ColorRawTokens.colorFunctionalBlack;
  Color primaryDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color primaryFixedDark = ColorRawTokens.colorFunctionalBlack;
  Color primaryFixedDimDark = ColorRawTokens.colorFunctionalBlack;
  Color primaryFixedDimLight = ColorRawTokens.colorFunctionalBlack;
  Color primaryFixedLight = ColorRawTokens.colorFunctionalBlack;
  Color primaryLight = ColorRawTokens.colorFunctionalBlack;
  Color scrimDark = ColorRawTokens.colorFunctionalBlack;
  Color scrimLight = ColorRawTokens.colorFunctionalBlack;
  Color secondaryContainerDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color secondaryContainerLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color secondaryDark = ColorRawTokens.colorFunctionalGrayLight160;
  Color secondaryFixedDark = ColorRawTokens.colorFunctionalBlack;
  Color secondaryFixedDimDark = ColorRawTokens.colorFunctionalBlack;
  Color secondaryFixedDimLight = ColorRawTokens.colorFunctionalBlack;
  Color secondaryFixedLight = ColorRawTokens.colorFunctionalBlack;
  Color secondaryLight = ColorRawTokens.colorFunctionalBlack;
  Color surfaceBrightDark = ColorRawTokens.colorFunctionalGrayDark640;
  Color surfaceBrightLight = ColorRawTokens.colorFunctionalWhite;
  Color surfaceDark = ColorRawTokens.colorFunctionalGrayDark880;
  Color surfaceDimDark = ColorRawTokens.colorFunctionalBlack;
  Color surfaceDimLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfaceLight = ColorRawTokens.colorFunctionalWhite;
  Color surfaceTintDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfaceTintLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfaceVariantDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfaceVariantLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfContainerDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfContainerHighDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfContainerHighestDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfContainerHighestLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfContainerHighLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfContainerLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color surfContainerLowDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfContainerLowestDark = ColorRawTokens.colorFunctionalGrayDark720;
  Color surfContainerLowestLight = ColorRawTokens.colorFunctionalWhite;
  Color surfContainerLowLight = ColorRawTokens.colorFunctionalWhite;
  Color tertiaryContainerDark = ColorRawTokens.colorFunctionalGrayDark880;
  Color tertiaryContainerLight = ColorRawTokens.colorFunctionalWhite;
  Color tertiaryDark = ColorRawTokens.colorFunctionalGrayDark880;
  Color tertiaryFixedDark = ColorRawTokens.colorFunctionalWhite;
  Color tertiaryFixedDimDark = ColorRawTokens.colorFunctionalGrayLight80;
  Color tertiaryFixedDimLight = ColorRawTokens.colorFunctionalGrayLight80;
  Color tertiaryFixedLight = ColorRawTokens.colorFunctionalWhite;
  Color tertiaryLight = ColorRawTokens.colorFunctionalWhite;
}
