//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsMaterialColorTokens {
  final Color primaryLight;
  final Color primaryDark;
  final Color onPrimaryLight;
  final Color onPrimaryDark;
  final Color primaryContainerLight;
  final Color primaryContainerDark;
  final Color onPrimaryContainerLight;
  final Color onPrimaryContainerDark;
  final Color secondaryLight;
  final Color secondaryDark;
  final Color onSecondaryLight;
  final Color onSecondaryDark;
  final Color secondaryContainerLight;
  final Color secondaryContainerDark;
  final Color onSecondaryContainerLight;
  final Color onSecondaryContainerDark;
  final Color tertiaryLight;
  final Color tertiaryDark;
  final Color onTertiaryLight;
  final Color onTertiaryDark;
  final Color tertiaryContainerLight;
  final Color tertiaryContainerDark;
  final Color onTertiaryContainerLight;
  final Color onTertiaryContainerDark;
  final Color errorLight;
  final Color errorDark;
  final Color onErrorLight;
  final Color onErrorDark;
  final Color errorContainerLight;
  final Color errorContainerDark;
  final Color onErrorContainerLight;
  final Color onErrorContainerDark;
  final Color primaryFixedLight;
  final Color primaryFixedDark;
  final Color primaryFixedDimLight;
  final Color primaryFixedDimDark;
  final Color onPrimaryFixedLight;
  final Color onPrimaryFixedDark;
  final Color onPrimaryFixedVariantLight;
  final Color onPrimaryFixedVariantDark;
  final Color secondaryFixedLight;
  final Color secondaryFixedDark;
  final Color secondaryFixedDimLight;
  final Color secondaryFixedDimDark;
  final Color onSecondaryFixedLight;
  final Color onSecondaryFixedDark;
  final Color onSecondaryFixedVariantLight;
  final Color onSecondaryFixedVariantDark;
  final Color tertiaryFixedLight;
  final Color tertiaryFixedDark;
  final Color tertiaryFixedDimLight;
  final Color tertiaryFixedDimDark;
  final Color onTertiaryFixedLight;
  final Color onTertiaryFixedDark;
  final Color onTertiaryFixedVariantLight;
  final Color onTertiaryFixedVariantDark;
  final Color surfaceDimLight;
  final Color surfaceDimDark;
  final Color surfaceLight;
  final Color surfaceDark;
  final Color surfaceBrightLight;
  final Color surfaceBrightDark;
  final Color onSurfaceLight;
  final Color onSurfaceDark;
  final Color onSurfaceVariantLight;
  final Color onSurfaceVariantDark;
  final Color surfContainerLowestLight;
  final Color surfContainerLowestDark;
  final Color surfContainerLowLight;
  final Color surfContainerLowDark;
  final Color surfContainerLight;
  final Color surfContainerDark;
  final Color surfContainerHighLight;
  final Color surfContainerHighDark;
  final Color surfContainerHighestLight;
  final Color surfContainerHighestDark;
  final Color inverseSurfaceLight;
  final Color inverseSurfaceDark;
  final Color inverseOnSurfaceLight;
  final Color inverseOnSurfaceDark;
  final Color inversePrimaryLight;
  final Color inversePrimaryDark;
  final Color outlineLight;
  final Color outlineDark;
  final Color outlineVariantLight;
  final Color outlineVariantDark;
  final Color scrimLight;
  final Color scrimDark;
  final Color backgroundLight;
  final Color backgroundDark;
  final Color onBackgroundLight;
  final Color onBackgroundDark;
  final Color surfaceVariantLight;
  final Color surfaceVariantDark;
  final Color surfaceTintLight;
  final Color surfaceTintDark;

  const OudsMaterialColorTokens({
    required this.primaryLight,
    required this.primaryDark,
    required this.onPrimaryLight,
    required this.onPrimaryDark,
    required this.primaryContainerLight,
    required this.primaryContainerDark,
    required this.onPrimaryContainerLight,
    required this.onPrimaryContainerDark,
    required this.secondaryLight,
    required this.secondaryDark,
    required this.onSecondaryLight,
    required this.onSecondaryDark,
    required this.secondaryContainerLight,
    required this.secondaryContainerDark,
    required this.onSecondaryContainerLight,
    required this.onSecondaryContainerDark,
    required this.tertiaryLight,
    required this.tertiaryDark,
    required this.onTertiaryLight,
    required this.onTertiaryDark,
    required this.tertiaryContainerLight,
    required this.tertiaryContainerDark,
    required this.onTertiaryContainerLight,
    required this.onTertiaryContainerDark,
    required this.errorLight,
    required this.errorDark,
    required this.onErrorLight,
    required this.onErrorDark,
    required this.errorContainerLight,
    required this.errorContainerDark,
    required this.onErrorContainerLight,
    required this.onErrorContainerDark,
    required this.primaryFixedLight,
    required this.primaryFixedDark,
    required this.primaryFixedDimLight,
    required this.primaryFixedDimDark,
    required this.onPrimaryFixedLight,
    required this.onPrimaryFixedDark,
    required this.onPrimaryFixedVariantLight,
    required this.onPrimaryFixedVariantDark,
    required this.secondaryFixedLight,
    required this.secondaryFixedDark,
    required this.secondaryFixedDimLight,
    required this.secondaryFixedDimDark,
    required this.onSecondaryFixedLight,
    required this.onSecondaryFixedDark,
    required this.onSecondaryFixedVariantLight,
    required this.onSecondaryFixedVariantDark,
    required this.tertiaryFixedLight,
    required this.tertiaryFixedDark,
    required this.tertiaryFixedDimLight,
    required this.tertiaryFixedDimDark,
    required this.onTertiaryFixedLight,
    required this.onTertiaryFixedDark,
    required this.onTertiaryFixedVariantLight,
    required this.onTertiaryFixedVariantDark,
    required this.surfaceDimLight,
    required this.surfaceDimDark,
    required this.surfaceLight,
    required this.surfaceDark,
    required this.surfaceBrightLight,
    required this.surfaceBrightDark,
    required this.onSurfaceLight,
    required this.onSurfaceDark,
    required this.onSurfaceVariantLight,
    required this.onSurfaceVariantDark,
    required this.surfContainerLowestLight,
    required this.surfContainerLowestDark,
    required this.surfContainerLowLight,
    required this.surfContainerLowDark,
    required this.surfContainerLight,
    required this.surfContainerDark,
    required this.surfContainerHighLight,
    required this.surfContainerHighDark,
    required this.surfContainerHighestLight,
    required this.surfContainerHighestDark,
    required this.inverseSurfaceLight,
    required this.inverseSurfaceDark,
    required this.inverseOnSurfaceLight,
    required this.inverseOnSurfaceDark,
    required this.inversePrimaryLight,
    required this.inversePrimaryDark,
    required this.outlineLight,
    required this.outlineDark,
    required this.outlineVariantLight,
    required this.outlineVariantDark,
    required this.scrimLight,
    required this.scrimDark,
    required this.backgroundLight,
    required this.backgroundDark,
    required this.onBackgroundLight,
    required this.onBackgroundDark,
    required this.surfaceVariantLight,
    required this.surfaceVariantDark,
    required this.surfaceTintLight,
    required this.surfaceTintDark,
  });
}
