//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe core tokens version 1.3.0
// Generated by Tokenator

import 'package:flutter/material.dart';

class WireframeColorRawTokens {
  static const colorFlame50 = Color(0xfffef7ee);
  static const colorFlame100 = Color(0xfffdedd7);
  static const colorFlame200 = Color(0xfffbd7ad);
  static const colorFlame300 = Color(0xfff8ba79);
  static const colorFlame400 = Color(0xfff5a15d);
  static const colorFlame500 = Color(0xfff0741f);
  static const colorFlame600 = Color(0xffe15a15);
  static const colorFlame700 = Color(0xffbb4413);
  static const colorFlame800 = Color(0xff953717);
  static const colorFlame900 = Color(0xff782f16);
  static const colorFlame950 = Color(0xff411509);
  static const colorFunctionalGrayDark80 = Color(0xff5e7197);
  static const colorFunctionalGrayDark160 = Color(0xff56688a);
  static const colorFunctionalGrayDark240 = Color(0xff4e5e7e);
  static const colorFunctionalGrayDark320 = Color(0xff475571);
  static const colorFunctionalGrayDark400 = Color(0xff3f4b64);
  static const colorFunctionalGrayDark480 = Color(0xff374258);
  static const colorFunctionalGrayDark560 = Color(0xff2f384b);
  static const colorFunctionalGrayDark640 = Color(0xff272f3f);
  static const colorFunctionalGrayDark720 = Color(0xff1f2632);
  static const colorFunctionalGrayDark800 = Color(0xff181c26);
  static const colorFunctionalGrayDark880 = Color(0xff101319);
  static const colorFunctionalGrayDark960 = Color(0xff08090d);
  static const colorFunctionalGrayLight80 = Color(0xfff7f8fa);
  static const colorFunctionalGrayLight160 = Color(0xffe9ecf1);
  static const colorFunctionalGrayLight240 = Color(0xffd9dee7);
  static const colorFunctionalGrayLight320 = Color(0xffcdd3e0);
  static const colorFunctionalGrayLight400 = Color(0xffc0c8d8);
  static const colorFunctionalGrayLight480 = Color(0xffb4bdd0);
  static const colorFunctionalGrayLight560 = Color(0xffa7b2c8);
  static const colorFunctionalGrayLight640 = Color(0xff9ba7c0);
  static const colorFunctionalGrayLight720 = Color(0xff8e9cb8);
  static const colorFunctionalGrayLight800 = Color(0xff8191b1);
  static const colorFunctionalGrayLight880 = Color(0xff7586a9);
  static const colorFunctionalGrayLight960 = Color(0xff687ba1);
  static const colorOpacityBlack0 = Color(0x0005052e);
  static const colorOpacityBlack40 = Color(0x0a05052e);
  static const colorOpacityBlack80 = Color(0x1405052e);
  static const colorOpacityBlack120 = Color(0x1f05052e);
  static const colorOpacityBlack160 = Color(0x2905052e);
  static const colorOpacityBlack200 = Color(0x3305052e);
  static const colorOpacityBlack240 = Color(0x3d05052e);
  static const colorOpacityBlack280 = Color(0x4705052e);
  static const colorOpacityBlack320 = Color(0x5205052e);
  static const colorOpacityBlack360 = Color(0x5c05052e);
  static const colorOpacityBlack400 = Color(0x6605052e);
  static const colorOpacityBlack440 = Color(0x7005052e);
  static const colorOpacityBlack480 = Color(0x7a05052e);
  static const colorOpacityBlack520 = Color(0x8505052e);
  static const colorOpacityBlack560 = Color(0x8f05052e);
  static const colorOpacityBlack600 = Color(0x9905052e);
  static const colorOpacityBlack640 = Color(0xa305052e);
  static const colorOpacityBlack680 = Color(0xad05052e);
  static const colorOpacityBlack720 = Color(0xb805052e);
  static const colorOpacityBlack760 = Color(0xc205052e);
  static const colorOpacityBlack800 = Color(0xcc05052e);
  static const colorOpacityBlack840 = Color(0xd605052e);
  static const colorOpacityBlack880 = Color(0xe005052e);
  static const colorOpacityBlack920 = Color(0xeb05052e);
  static const colorOpacityBlack960 = Color(0xf505052e);
  static const colorOpacityGrayDark800800 = Color(0xcc181c26);
  static const colorOpacityGrayLight80800 = Color(0xccf7f8fa);
  static const colorOpacityRoyalBlue0 = Color(0x002055e5);
  static const colorOpacityRoyalBlue40 = Color(0x0a2055e5);
  static const colorOpacityRoyalBlue80 = Color(0x142055e5);
  static const colorOpacityRoyalBlue120 = Color(0x1f2055e5);
  static const colorOpacityRoyalBlue160 = Color(0x292055e5);
  static const colorOpacityRoyalBlue200 = Color(0x332055e5);
  static const colorOpacityRoyalBlue240 = Color(0x3d2055e5);
  static const colorOpacityRoyalBlue280 = Color(0x472055e5);
  static const colorOpacityRoyalBlue320 = Color(0x522055e5);
  static const colorOpacityRoyalBlue360 = Color(0x5c2055e5);
  static const colorOpacityRoyalBlue400 = Color(0x662055e5);
  static const colorOpacityRoyalBlue440 = Color(0x702055e5);
  static const colorOpacityRoyalBlue480 = Color(0x7a2055e5);
  static const colorOpacityRoyalBlue520 = Color(0x852055e5);
  static const colorOpacityRoyalBlue560 = Color(0x8f2055e5);
  static const colorOpacityRoyalBlue600 = Color(0x992055e5);
  static const colorOpacityRoyalBlue640 = Color(0xa32055e5);
  static const colorOpacityRoyalBlue680 = Color(0xad2055e5);
  static const colorOpacityRoyalBlue720 = Color(0xb82055e5);
  static const colorOpacityRoyalBlue760 = Color(0xc22055e5);
  static const colorOpacityRoyalBlue800 = Color(0xcc2055e5);
  static const colorOpacityRoyalBlue840 = Color(0xd62055e5);
  static const colorOpacityRoyalBlue880 = Color(0xe02055e5);
  static const colorOpacityRoyalBlue920 = Color(0xeb2055e5);
  static const colorOpacityRoyalBlue960 = Color(0xf52055e5);
  static const colorOpacityRustyRed80 = Color(0x14db2345);
  static const colorOpacityRustyRed680 = Color(0xad8e1532);
  static const colorOpacityWhite0 = Color(0x00eff5ff);
  static const colorOpacityWhite40 = Color(0x0aeff5ff);
  static const colorOpacityWhite80 = Color(0x14eff5ff);
  static const colorOpacityWhite120 = Color(0x1feff5ff);
  static const colorOpacityWhite160 = Color(0x29eff5ff);
  static const colorOpacityWhite200 = Color(0x33eff5ff);
  static const colorOpacityWhite240 = Color(0x3deff5ff);
  static const colorOpacityWhite280 = Color(0x47eff5ff);
  static const colorOpacityWhite320 = Color(0x52eff5ff);
  static const colorOpacityWhite360 = Color(0x5ceff5ff);
  static const colorOpacityWhite400 = Color(0x66eff5ff);
  static const colorOpacityWhite440 = Color(0x70eff5ff);
  static const colorOpacityWhite480 = Color(0x7aeff5ff);
  static const colorOpacityWhite520 = Color(0x85eff5ff);
  static const colorOpacityWhite560 = Color(0x8feff5ff);
  static const colorOpacityWhite600 = Color(0x99eff5ff);
  static const colorOpacityWhite640 = Color(0xa3eff5ff);
  static const colorOpacityWhite680 = Color(0xadeff5ff);
  static const colorOpacityWhite720 = Color(0xb8eff5ff);
  static const colorOpacityWhite760 = Color(0xc2eff5ff);
  static const colorOpacityWhite800 = Color(0xcceff5ff);
  static const colorOpacityWhite840 = Color(0xd6eff5ff);
  static const colorOpacityWhite880 = Color(0xe0eff5ff);
  static const colorOpacityWhite920 = Color(0xebeff5ff);
  static const colorOpacityWhite960 = Color(0xf5eff5ff);
  static const colorRoyalBlue50 = Color(0xffeff5ff);
  static const colorRoyalBlue100 = Color(0xffdce9fd);
  static const colorRoyalBlue200 = Color(0xffc1d8fc);
  static const colorRoyalBlue300 = Color(0xff96c1fa);
  static const colorRoyalBlue400 = Color(0xff649ff6);
  static const colorRoyalBlue500 = Color(0xff407bf1);
  static const colorRoyalBlue600 = Color(0xff2055e5);
  static const colorRoyalBlue700 = Color(0xff2248d3);
  static const colorRoyalBlue800 = Color(0xff223cab);
  static const colorRoyalBlue900 = Color(0xff213787);
  static const colorRoyalBlue950 = Color(0xff1f2d6b);
  static const colorRoyalBlue1000 = Color(0xff182353);
  static const colorRustyRed50 = Color(0xfffff1f1);
  static const colorRustyRed100 = Color(0xfffee5e6);
  static const colorRustyRed200 = Color(0xfffccfd2);
  static const colorRustyRed300 = Color(0xfffa9ea6);
  static const colorRustyRed400 = Color(0xfff66f7d);
  static const colorRustyRed500 = Color(0xffee455b);
  static const colorRustyRed600 = Color(0xffdb2345);
  static const colorRustyRed700 = Color(0xffb81839);
  static const colorRustyRed800 = Color(0xff8e1532);
  static const colorRustyRed900 = Color(0xff681229);
  static const colorRustyRed950 = Color(0xff4a0717);
  static const colorRustyRed1000 = Color(0xff380513);
}