//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 1.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_surface_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class WireframeColorSurfaceSemanticTokens extends OudsColorSurfaceSemanticTokens {
  const WireframeColorSurfaceSemanticTokens({
    super.surfaceBrandPrimaryDark = WireframeColorRawTokens.colorRoyalBlue300,
    super.surfaceBrandPrimaryLight = WireframeColorRawTokens.colorRoyalBlue600,
    super.surfaceBrandSecondaryDark = WireframeColorRawTokens.colorRustyRed400,
    super.surfaceBrandSecondaryLight = WireframeColorRawTokens.colorRustyRed600,
    super.surfaceBrandTertiaryDark = const Color(0x00ff0000),
    super.surfaceBrandTertiaryLight = const Color(0x00ff0000),
    super.surfaceStatusAccentEmphasizedDark = WireframeColorRawTokens.colorRustyRed300,
    super.surfaceStatusAccentEmphasizedLight = WireframeColorRawTokens.colorRustyRed600,
    super.surfaceStatusAccentMutedDark = WireframeColorRawTokens.colorRustyRed900,
    super.surfaceStatusAccentMutedLight = WireframeColorRawTokens.colorOpacityRustyRed,
    super.surfaceStatusInfoEmphasizedDark = ColorRawTokens.colorFunctionalDodgerBlue300,
    super.surfaceStatusInfoEmphasizedLight = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.surfaceStatusInfoMutedDark = ColorRawTokens.colorFunctionalDodgerBlue900,
    super.surfaceStatusInfoMutedLight = ColorRawTokens.colorOpacityDodgerBlue,
    super.surfaceStatusNegativeEmphasizedDark = ColorRawTokens.colorFunctionalScarlet300,
    super.surfaceStatusNegativeEmphasizedLight = ColorRawTokens.colorFunctionalScarlet600,
    super.surfaceStatusNegativeMutedDark = ColorRawTokens.colorFunctionalScarlet900,
    super.surfaceStatusNegativeMutedLight = ColorRawTokens.colorOpacityScarlet,
    super.surfaceStatusNeutralEmphasizedDark = WireframeColorRawTokens.colorOpacityWhite920,
    super.surfaceStatusNeutralEmphasizedLight = WireframeColorRawTokens.colorOpacityBlack920,
    super.surfaceStatusNeutralMutedDark = WireframeColorRawTokens.colorOpacityWhite80,
    super.surfaceStatusNeutralMutedLight = WireframeColorRawTokens.colorOpacityBlack40,
    super.surfaceStatusPositiveEmphasizedDark = ColorRawTokens.colorFunctionalMalachite300,
    super.surfaceStatusPositiveEmphasizedLight = ColorRawTokens.colorFunctionalMalachite500,
    super.surfaceStatusPositiveMutedDark = ColorRawTokens.colorFunctionalMalachite900,
    super.surfaceStatusPositiveMutedLight = ColorRawTokens.colorOpacityMalachite,
    super.surfaceStatusWarningEmphasizedDark = ColorRawTokens.colorFunctionalSun300,
    super.surfaceStatusWarningEmphasizedLight = ColorRawTokens.colorFunctionalSun500,
    super.surfaceStatusWarningMutedDark = ColorRawTokens.colorFunctionalSun900,
    super.surfaceStatusWarningMutedLight = ColorRawTokens.colorOpacitySun,
  });
}
