//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.1.0
// Generated by Tokenator

import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_action_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class WireframeColorActionSemanticTokens extends OudsColorActionSemanticTokens {
  const WireframeColorActionSemanticTokens({
    super.actionDisabledDark = WireframeColorRawTokens.colorOpacityWhite200,
    super.actionDisabledLight = WireframeColorRawTokens.colorOpacityBlack200,
    super.actionEnabledDark = WireframeColorRawTokens.colorRoyalBlue300,
    super.actionEnabledLight = WireframeColorRawTokens.colorRoyalBlue600,
    super.actionFocusDark = WireframeColorRawTokens.colorRoyalBlue200,
    super.actionFocusLight = WireframeColorRawTokens.colorRoyalBlue800,
    super.actionHighlightedDark = WireframeColorRawTokens.colorFunctionalGrayLight160,
    super.actionHighlightedLight = WireframeColorRawTokens.colorRoyalBlue800,
    super.actionHoverDark = WireframeColorRawTokens.colorRoyalBlue200,
    super.actionHoverLight = WireframeColorRawTokens.colorRoyalBlue800,
    super.actionLoadingDark = WireframeColorRawTokens.colorRoyalBlue100,
    super.actionLoadingLight = WireframeColorRawTokens.colorRoyalBlue900,
    super.actionNegativeEnabledDark = ColorRawTokens.colorFunctionalScarlet300,
    super.actionNegativeEnabledLight = ColorRawTokens.colorFunctionalScarlet600,
    super.actionNegativeFocusDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeFocusLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeHoverDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeHoverLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeLoadingDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativeLoadingLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionNegativePressedDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativePressedLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionPressedDark = WireframeColorRawTokens.colorRoyalBlue100,
    super.actionPressedLight = WireframeColorRawTokens.colorRoyalBlue900,
    super.actionSelectedDark = WireframeColorRawTokens.colorRoyalBlue300,
    super.actionSelectedLight = WireframeColorRawTokens.colorRoyalBlue600,
    super.actionSupportDisabledDark = WireframeColorRawTokens.colorOpacityWhite40,
    super.actionSupportDisabledLight = WireframeColorRawTokens.colorOpacityBlack40,
    super.actionSupportEnabledDark = WireframeColorRawTokens.colorOpacityWhite40,
    super.actionSupportEnabledLight = WireframeColorRawTokens.colorOpacityBlack40,
    super.actionSupportFocusDark = WireframeColorRawTokens.colorOpacityWhite80,
    super.actionSupportFocusLight = WireframeColorRawTokens.colorOpacityBlack80,
    super.actionSupportHoverDark = WireframeColorRawTokens.colorOpacityWhite80,
    super.actionSupportHoverLight = WireframeColorRawTokens.colorOpacityBlack80,
    super.actionSupportLoadingDark = WireframeColorRawTokens.colorOpacityWhite120,
    super.actionSupportLoadingLight = WireframeColorRawTokens.colorOpacityBlack120,
    super.actionSupportPressedDark = WireframeColorRawTokens.colorOpacityWhite120,
    super.actionSupportPressedLight = WireframeColorRawTokens.colorOpacityBlack120,
    super.actionVisitedDark = ColorRawTokens.colorFunctionalAmethyst400,
    super.actionVisitedLight = ColorRawTokens.colorFunctionalAmethyst600,
  });
}
