//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.0.0
// Generated by Tokenator

import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_overlay_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class WireframeColorOverlaySemanticTokens extends OudsColorOverlaySemanticTokens {
  const WireframeColorOverlaySemanticTokens({
    super.overlayDragDark = WireframeColorRawTokens.colorOpacityWhite80,
    super.overlayDragLight = WireframeColorRawTokens.colorOpacityBlack40,
    super.overlayDropdownDark = WireframeColorRawTokens.colorFunctionalGrayDark560,
    super.overlayDropdownLight = ColorRawTokens.colorFunctionalWhite,
    super.overlayModalDark = WireframeColorRawTokens.colorFunctionalGrayDark720,
    super.overlayModalLight = ColorRawTokens.colorFunctionalWhite,
    super.overlayTooltipDark = WireframeColorRawTokens.colorFunctionalGrayDark560,
    super.overlayTooltipLight = WireframeColorRawTokens.colorFunctionalGrayDark720,
  });
}
