//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.0.1
// Generated by Tokenator

import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_opacity_semantic_tokens.dart';

class WireframeColorOpacitySemanticTokens extends OudsColorOpacitySemanticTokens {
  const WireframeColorOpacitySemanticTokens({
    super.opacityLowerDark = WireframeColorRawTokens.colorOpacityWhite80,
    super.opacityLowerLight = WireframeColorRawTokens.colorOpacityBlack80,
    super.opacityLowestDark = WireframeColorRawTokens.colorOpacityWhite40,
    super.opacityLowestLight = WireframeColorRawTokens.colorOpacityBlack40,
    super.opacityTransparentDark = WireframeColorRawTokens.colorOpacityWhite0,
    super.opacityTransparentLight = WireframeColorRawTokens.colorOpacityBlack0,
  });
}
