//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.2.0
// Generated by Tokenator

import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_bg_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class WireframeColorBgSemanticTokens extends OudsColorBgSemanticTokens {
  const WireframeColorBgSemanticTokens({
    super.bgInverseHighDark = WireframeColorRawTokens.colorFunctionalGrayLight160,
    super.bgInverseHighLight = WireframeColorRawTokens.colorFunctionalGrayDark800,
    super.bgInverseLowDark = WireframeColorRawTokens.colorFunctionalGrayDark720,
    super.bgInverseLowLight = WireframeColorRawTokens.colorFunctionalGrayDark800,
    super.bgPrimaryDark = WireframeColorRawTokens.colorFunctionalGrayDark880,
    super.bgPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.bgSecondaryDark = WireframeColorRawTokens.colorFunctionalGrayDark800,
    super.bgSecondaryLight = WireframeColorRawTokens.colorFunctionalGrayLight80,
    super.bgTertiaryDark = WireframeColorRawTokens.colorRustyRed1000,
    super.bgTertiaryLight = WireframeColorRawTokens.colorRustyRed50,
  });
}
