//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.6.0
// Generated by Tokenator

import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_ai_semantic_tokens.dart';

class WireframeColorAiSemanticTokens extends OudsColorAiSemanticTokens {
  const WireframeColorAiSemanticTokens({
    super.aiPrimaryDark = WireframeColorRawTokens.colorRoyalBlue600,
    super.aiPrimaryLight = WireframeColorRawTokens.colorRoyalBlue300,
    super.aiQuaternaryDark = WireframeColorRawTokens.colorRoyalBlue300,
    super.aiQuaternaryLight = WireframeColorRawTokens.colorRoyalBlue600,
    super.aiSecondaryDark = WireframeColorRawTokens.colorRoyalBlue300,
    super.aiSecondaryLight = WireframeColorRawTokens.colorRoyalBlue600,
    super.aiTertiaryDark = WireframeColorRawTokens.colorRoyalBlue600,
    super.aiTertiaryLight = WireframeColorRawTokens.colorRoyalBlue300,
  });
}
