//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.4.0
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_effect_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/effect_raw_tokens.dart';

class WireframeEffectSemanticTokens extends OudsEffectSemanticTokens {
  @override
  int get blurDrag => EffectRawTokens.effectBlur480;
}
