//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange Business Tools brand tokens version 2.3.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_font_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/font_raw_tokens.dart';

class OrangeBusinessToolsFontSemanticTokens extends OudsFontSemanticTokens {
  @override
  double get letterSpacingBodyLargeMobile => FontRawTokens.fontLetterSpacing200;
  @override
  double get letterSpacingBodyLargeTablet => FontRawTokens.fontLetterSpacing200;
  @override
  double get letterSpacingBodyMediumMobile => FontRawTokens.fontLetterSpacing175;
  @override
  double get letterSpacingBodyMediumTablet => FontRawTokens.fontLetterSpacing175;
  @override
  double get letterSpacingBodySmallMobile => FontRawTokens.fontLetterSpacing150;
  @override
  double get letterSpacingBodySmallTablet => FontRawTokens.fontLetterSpacing150;
  @override
  double get letterSpacingDisplayLargeMobile => FontRawTokens.fontLetterSpacing750;
  @override
  double get letterSpacingDisplayLargeTablet => FontRawTokens.fontLetterSpacing750;
  @override
  double get letterSpacingDisplayMediumMobile => FontRawTokens.fontLetterSpacing650;
  @override
  double get letterSpacingDisplayMediumTablet => FontRawTokens.fontLetterSpacing650;
  @override
  double get letterSpacingDisplaySmallMobile => FontRawTokens.fontLetterSpacing550;
  @override
  double get letterSpacingDisplaySmallTablet => FontRawTokens.fontLetterSpacing550;
  @override
  double get letterSpacingHeadingLargeMobile => FontRawTokens.fontLetterSpacing350;
  @override
  double get letterSpacingHeadingLargeTablet => FontRawTokens.fontLetterSpacing350;
  @override
  double get letterSpacingHeadingMediumMobile => FontRawTokens.fontLetterSpacing300;
  @override
  double get letterSpacingHeadingMediumTablet => FontRawTokens.fontLetterSpacing300;
  @override
  double get letterSpacingHeadingSmallMobile => FontRawTokens.fontLetterSpacing250;
  @override
  double get letterSpacingHeadingSmallTablet => FontRawTokens.fontLetterSpacing250;
  @override
  double get letterSpacingHeadingXlargeMobile => FontRawTokens.fontLetterSpacing450;
  @override
  double get letterSpacingHeadingXlargeTablet => FontRawTokens.fontLetterSpacing450;
  @override
  double get letterSpacingLabelLarge => FontRawTokens.fontLetterSpacing200;
  @override
  double get letterSpacingLabelMedium => FontRawTokens.fontLetterSpacing175;
  @override
  double get letterSpacingLabelSmall => FontRawTokens.fontLetterSpacing150;
  @override
  double get letterSpacingLabelXlarge => FontRawTokens.fontLetterSpacing250;
  @override
  double get lineHeightBodyLargeMobile => FontRawTokens.fontLineHeight350;
  @override
  double get lineHeightBodyLargeTablet => FontRawTokens.fontLineHeight350;
  @override
  double get lineHeightBodyMediumMobile => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightBodyMediumTablet => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightBodySmallMobile => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightBodySmallTablet => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightDisplayLargeMobile => FontRawTokens.fontLineHeight950;
  @override
  double get lineHeightDisplayLargeTablet => FontRawTokens.fontLineHeight950;
  @override
  double get lineHeightDisplayMediumMobile => FontRawTokens.fontLineHeight850;
  @override
  double get lineHeightDisplayMediumTablet => FontRawTokens.fontLineHeight850;
  @override
  double get lineHeightDisplaySmallMobile => FontRawTokens.fontLineHeight750;
  @override
  double get lineHeightDisplaySmallTablet => FontRawTokens.fontLineHeight750;
  @override
  double get lineHeightHeadingLargeMobile => FontRawTokens.fontLineHeight550;
  @override
  double get lineHeightHeadingLargeTablet => FontRawTokens.fontLineHeight550;
  @override
  double get lineHeightHeadingMediumMobile => FontRawTokens.fontLineHeight450;
  @override
  double get lineHeightHeadingMediumTablet => FontRawTokens.fontLineHeight450;
  @override
  double get lineHeightHeadingSmallMobile => FontRawTokens.fontLineHeight450;
  @override
  double get lineHeightHeadingSmallTablet => FontRawTokens.fontLineHeight450;
  @override
  double get lineHeightHeadingXlargeMobile => FontRawTokens.fontLineHeight650;
  @override
  double get lineHeightHeadingXlargeTablet => FontRawTokens.fontLineHeight650;
  @override
  double get lineHeightLabelLarge => FontRawTokens.fontLineHeight350;
  @override
  double get lineHeightLabelMedium => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightLabelSmall => FontRawTokens.fontLineHeight250;
  @override
  double get lineHeightLabelXlarge => FontRawTokens.fontLineHeight450;
  @override
  double get sizeBodyLargeMobile => FontRawTokens.fontSize200;
  @override
  double get sizeBodyLargeTablet => FontRawTokens.fontSize200;
  @override
  double get sizeBodyMediumMobile => FontRawTokens.fontSize175;
  @override
  double get sizeBodyMediumTablet => FontRawTokens.fontSize175;
  @override
  double get sizeBodySmallMobile => FontRawTokens.fontSize150;
  @override
  double get sizeBodySmallTablet => FontRawTokens.fontSize150;
  @override
  double get sizeDisplayLargeMobile => FontRawTokens.fontSize750;
  @override
  double get sizeDisplayLargeTablet => FontRawTokens.fontSize750;
  @override
  double get sizeDisplayMediumMobile => FontRawTokens.fontSize650;
  @override
  double get sizeDisplayMediumTablet => FontRawTokens.fontSize650;
  @override
  double get sizeDisplaySmallMobile => FontRawTokens.fontSize550;
  @override
  double get sizeDisplaySmallTablet => FontRawTokens.fontSize550;
  @override
  double get sizeHeadingLargeMobile => FontRawTokens.fontSize350;
  @override
  double get sizeHeadingLargeTablet => FontRawTokens.fontSize350;
  @override
  double get sizeHeadingMediumMobile => FontRawTokens.fontSize300;
  @override
  double get sizeHeadingMediumTablet => FontRawTokens.fontSize300;
  @override
  double get sizeHeadingSmallMobile => FontRawTokens.fontSize250;
  @override
  double get sizeHeadingSmallTablet => FontRawTokens.fontSize250;
  @override
  double get sizeHeadingXlargeMobile => FontRawTokens.fontSize450;
  @override
  double get sizeHeadingXlargeTablet => FontRawTokens.fontSize450;
  @override
  double get sizeLabelLarge => FontRawTokens.fontSize200;
  @override
  double get sizeLabelMedium => FontRawTokens.fontSize175;
  @override
  double get sizeLabelSmall => FontRawTokens.fontSize150;
  @override
  double get sizeLabelXlarge => FontRawTokens.fontSize250;
  @override
  FontWeight get weightBodyDefault => FontRawTokens.fontWeight400;
  @override
  FontWeight get weightBodyModerate => FontRawTokens.fontWeight500;
  @override
  FontWeight get weightBodyStrong => FontRawTokens.fontWeight700;
  @override
  FontWeight get weightDisplay => FontRawTokens.fontWeight700;
  @override
  FontWeight get weightHeading => FontRawTokens.fontWeight700;
  @override
  FontWeight get weightLabelDefault => FontRawTokens.fontWeight400;
  @override
  FontWeight get weightLabelModerate => FontRawTokens.fontWeight500;
  @override
  FontWeight get weightLabelStrong => FontRawTokens.fontWeight700;
  @override
  FontWeight get weightSystemDefault => FontRawTokens.fontWeight400;
  @override
  FontWeight get weightSystemModerate => FontRawTokens.fontWeight500;
  @override
  FontWeight get weightSystemStrong => FontRawTokens.fontWeight700;
}
