// 
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Software description: Flutter library of reusable graphical components
// 

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

class ColorRawTokens {
  static const colorFunctionalWhite = Color(0xffffffff);
  static const colorFunctionalBlack = Color(0xff000000);
  static const colorFunctionalGrayLight80 = Color(0xfff4f4f4);
  static const colorFunctionalGrayLight160 = Color(0xffeeeeee);
  static const colorFunctionalGrayLight240 = Color(0xffe0e0e0);
  static const colorFunctionalGrayLight320 = Color(0xffd6d6d6);
  static const colorFunctionalGrayLight400 = Color(0xffcccccc);
  static const colorFunctionalGrayLight480 = Color(0xffc2c2c2);
  static const colorFunctionalGrayLight560 = Color(0xffbbbbbb);
  static const colorFunctionalGrayLight640 = Color(0xffadadad);
  static const colorFunctionalGrayLight720 = Color(0xffa3a3a3);
  static const colorFunctionalGrayLight800 = Color(0xff999999);
  static const colorFunctionalGrayLight880 = Color(0xff8f8f8f);
  static const colorFunctionalGrayLight960 = Color(0xff858585);
  static const colorFunctionalGrayDark80 = Color(0xff7a7a7a);
  static const colorFunctionalGrayDark160 = Color(0xff707070);
  static const colorFunctionalGrayDark240 = Color(0xff666666);
  static const colorFunctionalGrayDark320 = Color(0xff5c5c5c);
  static const colorFunctionalGrayDark400 = Color(0xff555555);
  static const colorFunctionalGrayDark480 = Color(0xff444444);
  static const colorFunctionalGrayDark560 = Color(0xff3d3d3d);
  static const colorFunctionalGrayDark640 = Color(0xff333333);
  static const colorFunctionalGrayDark720 = Color(0xff272727);
  static const colorFunctionalGrayDark800 = Color(0xff1f1f1f);
  static const colorFunctionalGrayDark880 = Color(0xff141414);
  static const colorFunctionalGrayDark960 = Color(0xff0a0a0a);
  static const colorFunctionalScarlet100 = Color(0xffffe5e6);
  static const colorFunctionalScarlet200 = Color(0xffffb2b3);
  static const colorFunctionalScarlet300 = Color(0xffff8081);
  static const colorFunctionalScarlet400 = Color(0xffff4d4e);
  static const colorFunctionalScarlet500 = Color(0xffff1a1b);
  static const colorFunctionalScarlet600 = Color(0xffdb0002);
  static const colorFunctionalScarlet700 = Color(0xffb20002);
  static const colorFunctionalScarlet800 = Color(0xff800001);
  static const colorFunctionalScarlet900 = Color(0xff4d0001);
  static const colorFunctionalSun100 = Color(0xfffff7d6);
  static const colorFunctionalSun200 = Color(0xffffed99);
  static const colorFunctionalSun300 = Color(0xffffe270);
  static const colorFunctionalSun400 = Color(0xffffd73d);
  static const colorFunctionalSun500 = Color(0xffffd000);
  static const colorFunctionalSun600 = Color(0xffd6aa00);
  static const colorFunctionalSun700 = Color(0xffa38200);
  static const colorFunctionalSun800 = Color(0xff665100);
  static const colorFunctionalSun900 = Color(0xff3d3100);
  static const colorFunctionalMalachite100 = Color(0xffedfcf0);
  static const colorFunctionalMalachite200 = Color(0xffc1f6ca);
  static const colorFunctionalMalachite300 = Color(0xff94f0a4);
  static const colorFunctionalMalachite400 = Color(0xff67e97e);
  static const colorFunctionalMalachite500 = Color(0xff3de35a);
  static const colorFunctionalMalachite600 = Color(0xff1ecd3c);
  static const colorFunctionalMalachite700 = Color(0xff17a02f);
  static const colorFunctionalMalachite800 = Color(0xff0e621d);
  static const colorFunctionalMalachite900 = Color(0xff0a4715);
  static const colorFunctionalDodgerBlue100 = Color(0xfff0faff);
  static const colorFunctionalDodgerBlue200 = Color(0xffbde7ff);
  static const colorFunctionalDodgerBlue300 = Color(0xff8ad5ff);
  static const colorFunctionalDodgerBlue400 = Color(0xff57c3ff);
  static const colorFunctionalDodgerBlue500 = Color(0xff26b2ff);
  static const colorFunctionalDodgerBlue600 = Color(0xff009bf0);
  static const colorFunctionalDodgerBlue700 = Color(0xff007abd);
  static const colorFunctionalDodgerBlue800 = Color(0xff00598a);
  static const colorFunctionalDodgerBlue900 = Color(0xff003857);
  static const colorOpacityScarlet = Color(0x14ea0305);
  static const colorOpacitySun = Color(0x29ffd000);
  static const colorOpacityMalachite = Color(0x1f3de35a);
  static const colorOpacityDodgerBlue = Color(0x1426b2ff);
  static const colorOpacityBlack0 = Color(0x00000000);
  static const colorOpacityBlack40 = Color(0x0a000000);
  static const colorOpacityBlack80 = Color(0x14000000);
  static const colorOpacityBlack120 = Color(0x1f000000);
  static const colorOpacityBlack160 = Color(0x29000000);
  static const colorOpacityBlack200 = Color(0x33000000);
  static const colorOpacityBlack240 = Color(0x3d000000);
  static const colorOpacityBlack280 = Color(0x47000000);
  static const colorOpacityBlack320 = Color(0x52000000);
  static const colorOpacityBlack360 = Color(0x5c000000);
  static const colorOpacityBlack400 = Color(0x66000000);
  static const colorOpacityBlack440 = Color(0x70000000);
  static const colorOpacityBlack480 = Color(0x7a000000);
  static const colorOpacityBlack520 = Color(0x85000000);
  static const colorOpacityBlack560 = Color(0x8f000000);
  static const colorOpacityBlack600 = Color(0x99000000);
  static const colorOpacityBlack640 = Color(0xa3000000);
  static const colorOpacityBlack680 = Color(0xad000000);
  static const colorOpacityBlack720 = Color(0xb8000000);
  static const colorOpacityBlack760 = Color(0xc2000000);
  static const colorOpacityBlack800 = Color(0xcc000000);
  static const colorOpacityBlack840 = Color(0xd6000000);
  static const colorOpacityBlack880 = Color(0xe0000000);
  static const colorOpacityBlack920 = Color(0xeb000000);
  static const colorOpacityBlack960 = Color(0xf5000000);
  static const colorOpacityWhite0 = Color(0x00ffffff);
  static const colorOpacityWhite40 = Color(0x0affffff);
  static const colorOpacityWhite80 = Color(0x14ffffff);
  static const colorOpacityWhite120 = Color(0x1fffffff);
  static const colorOpacityWhite160 = Color(0x29ffffff);
  static const colorOpacityWhite200 = Color(0x33ffffff);
  static const colorOpacityWhite240 = Color(0x3dffffff);
  static const colorOpacityWhite280 = Color(0x47ffffff);
  static const colorOpacityWhite320 = Color(0x52ffffff);
  static const colorOpacityWhite360 = Color(0x5cffffff);
  static const colorOpacityWhite400 = Color(0x66ffffff);
  static const colorOpacityWhite440 = Color(0x70ffffff);
  static const colorOpacityWhite480 = Color(0x7affffff);
  static const colorOpacityWhite520 = Color(0x85ffffff);
  static const colorOpacityWhite560 = Color(0x8fffffff);
  static const colorOpacityWhite600 = Color(0x99ffffff);
  static const colorOpacityWhite640 = Color(0xa3ffffff);
  static const colorOpacityWhite680 = Color(0xadffffff);
  static const colorOpacityWhite720 = Color(0xb8ffffff);
  static const colorOpacityWhite760 = Color(0xc2ffffff);
  static const colorOpacityWhite800 = Color(0xccffffff);
  static const colorOpacityWhite840 = Color(0xd6ffffff);
  static const colorOpacityWhite880 = Color(0xe0ffffff);
  static const colorOpacityWhite920 = Color(0xebffffff);
  static const colorOpacityWhite960 = Color(0xf5ffffff);
}