// 
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Software description: Flutter library of reusable graphical components
// 

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

class DimensionRawTokens {
  static const dimensionBase = 4;
  static const dimension0 = dimensionBase * 0.0; // 0px
  static const dimension50 = dimensionBase * 1.0; // 4px
  static const dimension100 = dimensionBase * 2.0; // 8px
  static const dimension150 = dimensionBase * 3.0; // 12px
  static const dimension200 = dimensionBase * 4.0; // 16px
  static const dimension250 = dimensionBase * 5.0; // 20px
  static const dimension300 = dimensionBase * 6.0; // 24px
  static const dimension350 = dimensionBase * 7.0; // 28px
  static const dimension400 = dimensionBase * 8.0; // 32px
  static const dimension450 = dimensionBase * 9.0; // 36px
  static const dimension500 = dimensionBase * 10.0; // 40px
  static const dimension550 = dimensionBase * 11.0; // 44px
  static const dimension600 = dimensionBase * 12.0; // 48px
  static const dimension650 = dimensionBase * 13.0; // 52px
  static const dimension700 = dimensionBase * 14.0; // 56px
  static const dimension750 = dimensionBase * 15.0; // 60px
  static const dimension800 = dimensionBase * 16.0; // 64px
  static const dimension850 = dimensionBase * 17.0; // 68px
  static const dimension900 = dimensionBase * 18.0; // 72px
  static const dimension1000 = dimensionBase * 20.0; // 80px
  static const dimension1200 = dimensionBase * 24.0; // 96px
  static const dimension1250 = dimensionBase * 25.0; // 100px
  static const dimension1400 = dimensionBase * 28.0; // 112px
  static const dimension1600 = dimensionBase * 32.0; // 128px
  static const dimension1800 = dimensionBase * 36.0; // 144px
  static const dimension2000 = dimensionBase * 40.0; // 160px
  static const dimension3000 = dimensionBase * 80.0; // 320px
  static const dimension4000 = dimensionBase * 120.0; // 480px
  static const dimension5000 = dimensionBase * 140.0; // 560px
  static const dimension6000 = dimensionBase * 160.0; // 640px
  static const dimension7000 = dimensionBase * 180.0; // 720px
  static const dimension9000 = dimensionBase * 220.0; // 880px
  static const dimension11000 = dimensionBase * 260.0; // 1040px
  static const dimensionOutOfSystem25 = dimensionBase * 0.25; // 1px
  static const dimensionOutOfSystem50 = dimensionBase * 0.5; // 2px
  static const dimensionOutOfSystem75 = dimensionBase * 0.75; // 3px
  static const dimensionOutOfSystem150 = dimensionBase * 1.5; // 6px
  static const dimensionOutOfSystem250 = dimensionBase * 2.5; // 10px
}