//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS core tokens version 1.9.0
// Generated by Tokenator

class EffectRawTokens {
  static const effectBlur160 = 16;
  static const effectBlur320 = 32;
}