// 
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Software description: Flutter library of reusable graphical components
// 

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

class ElevationRawTokens {
  static const elevation0 = 0.0;
  static const elevation1 = 1.0;
  static const elevation2 = 3.0;
  static const elevation3 = 6.0;
  static const elevation4 = 8.0;
  static const elevation5 = 12.0;
}