// 
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Software description: Flutter library of reusable graphical components
// 

// Tokens version 0.7.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class GridRawTokens {
  static const gridColumnCount100 = 1;
  static const gridColumnCount200 = 2;
  static const gridColumnCount400 = 4;
  static const gridColumnCount600 = 6;
  static const gridColumnCount800 = 8;
  static const gridColumnCount1000 = 10;
  static const gridColumnCount1200 = 12;
  static const gridMaxWidthCompact = 599;
  static const gridMaxWidthExtraCompact = 389;
  static const gridMaxWidthMedium = 1200;
  static const gridMinWidthCompact = 390;
  static const gridMinWidthExtraCompact = 320;
  static const gridMinWidthMedium = 600;
  static const gridColumnGap10 = DimensionRawTokens.dimensionBase * 0.25; // 1
  static const gridColumnGap100 = DimensionRawTokens.dimensionBase * 2.0; // 8
  static const gridColumnGap200 = DimensionRawTokens.dimensionBase * 4.0; // 16
  static const gridColumnGap300 = DimensionRawTokens.dimensionBase * 5.0; // 20
  static const gridColumnGap400 = DimensionRawTokens.dimensionBase * 6.0; // 24
  static const gridColumnGap600 = DimensionRawTokens.dimensionBase * 8.0; // 32
  static const gridColumnGap800 = DimensionRawTokens.dimensionBase * 10.0; // 40
  static const gridMargin100 = DimensionRawTokens.dimensionBase * 4.0; // 16
  static const gridMargin300 = DimensionRawTokens.dimensionBase * 6.0; // 24
  static const gridMargin400 = DimensionRawTokens.dimensionBase * 7.0; // 28
  static const gridMargin500 = DimensionRawTokens.dimensionBase * 8.0; // 32
  static const gridMargin600 = DimensionRawTokens.dimensionBase * 9.0; // 36
  static const gridMargin700 = DimensionRawTokens.dimensionBase * 10.0; // 40
  static const gridMargin1000 = DimensionRawTokens.dimensionBase * 13.0; // 52
  static const gridMargin1100 = DimensionRawTokens.dimensionBase * 14.0; // 56
  static const gridMargin1700 = DimensionRawTokens.dimensionBase * 20.0; // 80
  static const gridMargin2500 = DimensionRawTokens.dimensionBase * 28.0; // 112
}