// 
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Software description: Flutter library of reusable graphical components
// 

// Tokens version 0.5.0
// Generated by Tokenator

class OpacityRawTokens {
    static const opacity0 = 0.0;
    static const opacity40 = 0.04;
    static const opacity80 = 0.08;
    static const opacity120 = 0.12;
    static const opacity160 = 0.16;
    static const opacity200 = 0.2;
    static const opacity240 = 0.24;
    static const opacity280 = 0.28;
    static const opacity320 = 0.32;
    static const opacity360 = 0.36;
    static const opacity400 = 0.4;
    static const opacity440 = 0.44;
    static const opacity480 = 0.48;
    static const opacity520 = 0.52;
    static const opacity560 = 0.56;
    static const opacity600 = 0.6;
    static const opacity640 = 0.64;
    static const opacity680 = 0.68;
    static const opacity720 = 0.72;
    static const opacity760 = 0.76;
    static const opacity800 = 0.8;
    static const opacity880 = 0.88;
    static const opacity920 = 0.92;
    static const opacity960 = 0.96;
    static const opacity1000 = 1.0;
}