//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.9.0
// Generated by Tokenator

import 'package:flutter/material.dart';
  
abstract class OudsColorDecorativeSemanticTokens {
  final Color decorativeAccent1DefaultLight;
  final Color decorativeAccent1EmphasizedLight;
  final Color decorativeAccent1MutedLight;
  final Color decorativeAccent1DefaultDark;
  final Color decorativeAccent1EmphasizedDark;
  final Color decorativeAccent1MutedDark;
  final Color decorativeAccent2DefaultLight;
  final Color decorativeAccent2EmphasizedLight;
  final Color decorativeAccent2MutedLight;
  final Color decorativeAccent2DefaultDark;
  final Color decorativeAccent2EmphasizedDark;
  final Color decorativeAccent2MutedDark;
  final Color decorativeAccent3DefaultLight;
  final Color decorativeAccent3EmphasizedLight;
  final Color decorativeAccent3MutedLight;
  final Color decorativeAccent3DefaultDark;
  final Color decorativeAccent3EmphasizedDark;
  final Color decorativeAccent3MutedDark;
  final Color decorativeAccent4DefaultLight;
  final Color decorativeAccent4EmphasizedLight;
  final Color decorativeAccent4MutedLight;
  final Color decorativeAccent4DefaultDark;
  final Color decorativeAccent4EmphasizedDark;
  final Color decorativeAccent4MutedDark;
  final Color decorativeAccent5DefaultLight;
  final Color decorativeAccent5EmphasizedLight;
  final Color decorativeAccent5MutedLight;
  final Color decorativeAccent5DefaultDark;
  final Color decorativeAccent5EmphasizedDark;
  final Color decorativeAccent5MutedDark;
  final Color decorativeBrandPrimaryLight;
  final Color decorativeBrandSecondaryLight;
  final Color decorativeBrandTertiaryLight;
  final Color decorativeBrandPrimaryDark;
  final Color decorativeBrandSecondaryDark;
  final Color decorativeBrandTertiaryDark;
  final Color decorativeNeutralEmphasizedHigherLight;
  final Color decorativeNeutralEmphasizedLowLight;
  final Color decorativeNeutralEmphasizedLowerLight;
  final Color decorativeNeutralEmphasizedLowestLight;
  final Color decorativeNeutralEmphasizedHigherDark;
  final Color decorativeNeutralEmphasizedLowDark;
  final Color decorativeNeutralEmphasizedLowerDark;
  final Color decorativeNeutralEmphasizedLowestDark;
  final Color decorativeNeutralMutedHighLight;
  final Color decorativeNeutralMutedHigherLight;
  final Color decorativeNeutralMutedHighestLight;
  final Color decorativeNeutralMutedLowLight;
  final Color decorativeNeutralMutedLowerLight;
  final Color decorativeNeutralMutedLowestLight;
  final Color decorativeNeutralMutedMediumLight;
  final Color decorativeNeutralMutedHighDark;
  final Color decorativeNeutralMutedHigherDark;
  final Color decorativeNeutralMutedHighestDark;
  final Color decorativeNeutralMutedLowDark;
  final Color decorativeNeutralMutedLowerDark;
  final Color decorativeNeutralMutedLowestDark;
  final Color decorativeNeutralMutedMediumDark;
  final Color decorativeSkinTint100Light;
  final Color decorativeSkinTint200Light;
  final Color decorativeSkinTint300Light;
  final Color decorativeSkinTint400Light;
  final Color decorativeSkinTint500Light;
  final Color decorativeSkinTint600Light;
  final Color decorativeSkinTint700Light;
  final Color decorativeSkinTint800Light;
  final Color decorativeSkinTint900Light;
  final Color decorativeSkinTint100Dark;
  final Color decorativeSkinTint200Dark;
  final Color decorativeSkinTint300Dark;
  final Color decorativeSkinTint400Dark;
  final Color decorativeSkinTint500Dark;
  final Color decorativeSkinTint600Dark;
  final Color decorativeSkinTint700Dark;
  final Color decorativeSkinTint800Dark;
  final Color decorativeSkinTint900Dark;

  const OudsColorDecorativeSemanticTokens({
    required this.decorativeAccent1DefaultLight,
    required this.decorativeAccent1EmphasizedLight,
    required this.decorativeAccent1MutedLight,
    required this.decorativeAccent1DefaultDark,
    required this.decorativeAccent1EmphasizedDark,
    required this.decorativeAccent1MutedDark,
    required this.decorativeAccent2DefaultLight,
    required this.decorativeAccent2EmphasizedLight,
    required this.decorativeAccent2MutedLight,
    required this.decorativeAccent2DefaultDark,
    required this.decorativeAccent2EmphasizedDark,
    required this.decorativeAccent2MutedDark,
    required this.decorativeAccent3DefaultLight,
    required this.decorativeAccent3EmphasizedLight,
    required this.decorativeAccent3MutedLight,
    required this.decorativeAccent3DefaultDark,
    required this.decorativeAccent3EmphasizedDark,
    required this.decorativeAccent3MutedDark,
    required this.decorativeAccent4DefaultLight,
    required this.decorativeAccent4EmphasizedLight,
    required this.decorativeAccent4MutedLight,
    required this.decorativeAccent4DefaultDark,
    required this.decorativeAccent4EmphasizedDark,
    required this.decorativeAccent4MutedDark,
    required this.decorativeAccent5DefaultLight,
    required this.decorativeAccent5EmphasizedLight,
    required this.decorativeAccent5MutedLight,
    required this.decorativeAccent5DefaultDark,
    required this.decorativeAccent5EmphasizedDark,
    required this.decorativeAccent5MutedDark,
    required this.decorativeBrandPrimaryLight,
    required this.decorativeBrandSecondaryLight,
    required this.decorativeBrandTertiaryLight,
    required this.decorativeBrandPrimaryDark,
    required this.decorativeBrandSecondaryDark,
    required this.decorativeBrandTertiaryDark,
    required this.decorativeNeutralEmphasizedHigherLight,
    required this.decorativeNeutralEmphasizedLowLight,
    required this.decorativeNeutralEmphasizedLowerLight,
    required this.decorativeNeutralEmphasizedLowestLight,
    required this.decorativeNeutralEmphasizedHigherDark,
    required this.decorativeNeutralEmphasizedLowDark,
    required this.decorativeNeutralEmphasizedLowerDark,
    required this.decorativeNeutralEmphasizedLowestDark,
    required this.decorativeNeutralMutedHighLight,
    required this.decorativeNeutralMutedHigherLight,
    required this.decorativeNeutralMutedHighestLight,
    required this.decorativeNeutralMutedLowLight,
    required this.decorativeNeutralMutedLowerLight,
    required this.decorativeNeutralMutedLowestLight,
    required this.decorativeNeutralMutedMediumLight,
    required this.decorativeNeutralMutedHighDark,
    required this.decorativeNeutralMutedHigherDark,
    required this.decorativeNeutralMutedHighestDark,
    required this.decorativeNeutralMutedLowDark,
    required this.decorativeNeutralMutedLowerDark,
    required this.decorativeNeutralMutedLowestDark,
    required this.decorativeNeutralMutedMediumDark,
    required this.decorativeSkinTint100Light,
    required this.decorativeSkinTint200Light,
    required this.decorativeSkinTint300Light,
    required this.decorativeSkinTint400Light,
    required this.decorativeSkinTint500Light,
    required this.decorativeSkinTint600Light,
    required this.decorativeSkinTint700Light,
    required this.decorativeSkinTint800Light,
    required this.decorativeSkinTint900Light,
    required this.decorativeSkinTint100Dark,
    required this.decorativeSkinTint200Dark,
    required this.decorativeSkinTint300Dark,
    required this.decorativeSkinTint400Dark,
    required this.decorativeSkinTint500Dark,
    required this.decorativeSkinTint600Dark,
    required this.decorativeSkinTint700Dark,
    required this.decorativeSkinTint800Dark,
    required this.decorativeSkinTint900Dark,
  });
}
