//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.6.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorAiSemanticTokens {
  final Color aiPrimaryDark;
  final Color aiPrimaryLight;
  final Color aiQuaternaryDark;
  final Color aiQuaternaryLight;
  final Color aiSecondaryDark;
  final Color aiSecondaryLight;
  final Color aiTertiaryDark;
  final Color aiTertiaryLight;

  const OudsColorAiSemanticTokens({
    required this.aiPrimaryDark,
    required this.aiPrimaryLight,
    required this.aiQuaternaryDark,
    required this.aiQuaternaryLight,
    required this.aiSecondaryDark,
    required this.aiSecondaryLight,
    required this.aiTertiaryDark,
    required this.aiTertiaryLight,
  });
}
