//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsFontSemanticTokens {
  late FontWeight weightSystemDefault;
  late FontWeight weightSystemStrong;
  late FontWeight weightDisplay;
  late FontWeight weightHeading;
  late FontWeight weightBodyDefault;
  late FontWeight weightBodyStrong;
  late FontWeight weightLabelDefault;
  late FontWeight weightLabelStrong;
  late double sizeDisplayLargeMobile;
  late double sizeDisplayLargeTablet;
  late double sizeDisplayMediumMobile;
  late double sizeDisplayMediumTablet;
  late double sizeDisplaySmallMobile;
  late double sizeDisplaySmallTablet;
  late double sizeHeadingXlargeMobile;
  late double sizeHeadingXlargeTablet;
  late double sizeHeadingLargeMobile;
  late double sizeHeadingLargeTablet;
  late double sizeHeadingMediumMobile;
  late double sizeHeadingMediumTablet;
  late double sizeHeadingSmallMobile;
  late double sizeHeadingSmallTablet;
  late double sizeBodyLargeMobile;
  late double sizeBodyLargeTablet;
  late double sizeBodyMediumMobile;
  late double sizeBodyMediumTablet;
  late double sizeBodySmallMobile;
  late double sizeBodySmallTablet;
  late double sizeLabelXlarge;
  late double sizeLabelLarge;
  late double sizeLabelMedium;
  late double sizeLabelSmall;
  late double lineHeightDisplayLargeMobile;
  late double lineHeightDisplayLargeTablet;
  late double lineHeightDisplayMediumMobile;
  late double lineHeightDisplayMediumTablet;
  late double lineHeightDisplaySmallMobile;
  late double lineHeightDisplaySmallTablet;
  late double lineHeightHeadingXlargeMobile;
  late double lineHeightHeadingXlargeTablet;
  late double lineHeightHeadingLargeMobile;
  late double lineHeightHeadingLargeTablet;
  late double lineHeightHeadingMediumMobile;
  late double lineHeightHeadingMediumTablet;
  late double lineHeightHeadingSmallMobile;
  late double lineHeightHeadingSmallTablet;
  late double lineHeightBodyLargeMobile;
  late double lineHeightBodyLargeTablet;
  late double lineHeightBodyMediumMobile;
  late double lineHeightBodyMediumTablet;
  late double lineHeightBodySmallMobile;
  late double lineHeightBodySmallTablet;
  late double lineHeightLabelXlarge;
  late double lineHeightLabelLarge;
  late double lineHeightLabelMedium;
  late double lineHeightLabelSmall;
  late double letterSpacingDisplayLargeMobile;
  late double letterSpacingDisplayLargeTablet;
  late double letterSpacingDisplayMediumMobile;
  late double letterSpacingDisplayMediumTablet;
  late double letterSpacingDisplaySmallMobile;
  late double letterSpacingDisplaySmallTablet;
  late double letterSpacingHeadingXlargeMobile;
  late double letterSpacingHeadingXlargeTablet;
  late double letterSpacingHeadingLargeMobile;
  late double letterSpacingHeadingLargeTablet;
  late double letterSpacingHeadingMediumMobile;
  late double letterSpacingHeadingMediumTablet;
  late double letterSpacingHeadingSmallMobile;
  late double letterSpacingHeadingSmallTablet;
  late double letterSpacingBodyLargeMobile;
  late double letterSpacingBodyLargeTablet;
  late double letterSpacingBodyMediumMobile;
  late double letterSpacingBodyMediumTablet;
  late double letterSpacingBodySmallMobile;
  late double letterSpacingBodySmallTablet;
  late double letterSpacingLabelXlarge;
  late double letterSpacingLabelLarge;
  late double letterSpacingLabelMedium;
  late double letterSpacingLabelSmall;
}
