//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.9.0
// Generated by Tokenator

import 'package:flutter/material.dart';
  
abstract class OudsColorAlwaysSemanticTokens {
  final Color alwaysBlackLight;
  final Color alwaysOnBlackLight;
  final Color alwaysOnWhiteLight;
  final Color alwaysWhiteLight;
  final Color alwaysBlackDark;
  final Color alwaysOnBlackDark;
  final Color alwaysOnWhiteDark;
  final Color alwaysWhiteDark;

  const OudsColorAlwaysSemanticTokens({
    required this.alwaysBlackLight,
    required this.alwaysOnBlackLight,
    required this.alwaysOnWhiteLight,
    required this.alwaysWhiteLight,
    required this.alwaysBlackDark,
    required this.alwaysOnBlackDark,
    required this.alwaysOnWhiteDark,
    required this.alwaysWhiteDark,
  });
}
