//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

abstract class OudsSpaceSemanticTokens {
  late double scaledNoneMobile;
  late double scaledNoneTablet;
  late double scaled3xsMobile;
  late double scaled3xsTablet;
  late double scaled2xsMobile;
  late double scaled2xsTablet;
  late double scaledXsMobile;
  late double scaledXsTablet;
  late double scaledSmMobile;
  late double scaledSmTablet;
  late double scaledMdMobile;
  late double scaledMdTablet;
  late double scaledLgMobile;
  late double scaledLgTablet;
  late double scaledXlMobile;
  late double scaledXlTablet;
  late double scaled2xlMobile;
  late double scaled2xlTablet;
  late double scaled3xlMobile;
  late double scaled3xlTablet;
  late double fixedNone;
  late double fixed3xs;
  late double fixed2xs;
  late double fixedXs;
  late double fixedSm;
  late double fixedMd;
  late double fixedLg;
  late double fixedXl;
  late double fixed2xl;
  late double fixed3xl;
  late double fixed4xl;
  late double fixed5xl;
  late double paddingInlineNone;
  late double paddingInline4xs;
  late double paddingInline3xs;
  late double paddingInline2xs;
  late double paddingInlineXs;
  late double paddingInlineSm;
  late double paddingInlineMd;
  late double paddingInlineLg;
  late double paddingInlineXl;
  late double paddingInline2xl;
  late double paddingInline3xl;
  late double paddingInline4xl;
  late double paddingBlockNone;
  late double paddingBlock3xs;
  late double paddingBlock2xs;
  late double paddingBlockXs;
  late double paddingBlockSm;
  late double paddingBlockMd;
  late double paddingBlockLg;
  late double paddingBlockXl;
  late double paddingBlock2xl;
  late double paddingBlock3xl;
  late double paddingBlock4xl;
  late double insetNone;
  late double inset4xs;
  late double inset3xs;
  late double inset2xs;
  late double insetXs;
  late double insetSm;
  late double insetMd;
  late double insetLg;
  late double insetXl;
  late double inset2xl;
  late double inset3xl;
  late double columnGapNone;
  late double columnGap3xs;
  late double columnGap2xs;
  late double columnGapXs;
  late double columnGapSm;
  late double columnGapMd;
  late double columnGapLg;
  late double columnGapXl;
  late double columnGap2xl;
  late double rowGapNone;
  late double rowGap3xs;
  late double rowGap2xs;
  late double rowGapXs;
  late double rowGapSm;
  late double rowGapMd;
  late double rowGapLg;
}
