//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorOverlaySemanticTokens {
  final Color overlayDefaultDark;
  final Color overlayDefaultLight;
  final Color overlayDragDark;
  final Color overlayDragLight;
  final Color overlayEmphasizedDark;
  final Color overlayEmphasizedLight;
  final Color overlayModalDark;
  final Color overlayModalLight;

  const OudsColorOverlaySemanticTokens({
    required this.overlayDefaultDark,
    required this.overlayDefaultLight,
    required this.overlayDragDark,
    required this.overlayDragLight,
    required this.overlayEmphasizedDark,
    required this.overlayEmphasizedLight,
    required this.overlayModalDark,
    required this.overlayModalLight,
  });
}
