//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorActionSemanticTokens {
  final Color actionDisabledDark;
  final Color actionDisabledLight;
  final Color actionEnabledDark;
  final Color actionEnabledLight;
  final Color actionFocusDark;
  final Color actionFocusLight;
  final Color actionHighlightedDark;
  final Color actionHighlightedLight;
  final Color actionHoverDark;
  final Color actionHoverLight;
  final Color actionLoadingDark;
  final Color actionLoadingLight;
  final Color actionNegativeEnabledDark;
  final Color actionNegativeEnabledLight;
  final Color actionNegativeFocusDark;
  final Color actionNegativeFocusLight;
  final Color actionNegativeHoverDark;
  final Color actionNegativeHoverLight;
  final Color actionNegativeLoadingDark;
  final Color actionNegativeLoadingLight;
  final Color actionNegativePressedDark;
  final Color actionNegativePressedLight;
  final Color actionPressedDark;
  final Color actionPressedLight;
  final Color actionSelectedDark;
  final Color actionSelectedLight;
  final Color actionSupportEnabledDark;
  final Color actionSupportEnabledLight;
  final Color actionSupportFocusDark;
  final Color actionSupportFocusLight;
  final Color actionSupportHoverDark;
  final Color actionSupportHoverLight;
  final Color actionSupportLoadingDark;
  final Color actionSupportLoadingLight;
  final Color actionSupportPressedDark;
  final Color actionSupportPressedLight;
  final Color actionVisitedDark;
  final Color actionVisitedLight;

  const OudsColorActionSemanticTokens({
    required this.actionDisabledDark,
    required this.actionDisabledLight,
    required this.actionEnabledDark,
    required this.actionEnabledLight,
    required this.actionFocusDark,
    required this.actionFocusLight,
    required this.actionHighlightedDark,
    required this.actionHighlightedLight,
    required this.actionHoverDark,
    required this.actionHoverLight,
    required this.actionLoadingDark,
    required this.actionLoadingLight,
    required this.actionNegativeEnabledDark,
    required this.actionNegativeEnabledLight,
    required this.actionNegativeFocusDark,
    required this.actionNegativeFocusLight,
    required this.actionNegativeHoverDark,
    required this.actionNegativeHoverLight,
    required this.actionNegativeLoadingDark,
    required this.actionNegativeLoadingLight,
    required this.actionNegativePressedDark,
    required this.actionNegativePressedLight,
    required this.actionPressedDark,
    required this.actionPressedLight,
    required this.actionSelectedDark,
    required this.actionSelectedLight,
    required this.actionSupportEnabledDark,
    required this.actionSupportEnabledLight,
    required this.actionSupportFocusDark,
    required this.actionSupportFocusLight,
    required this.actionSupportHoverDark,
    required this.actionSupportHoverLight,
    required this.actionSupportLoadingDark,
    required this.actionSupportLoadingLight,
    required this.actionSupportPressedDark,
    required this.actionSupportPressedLight,
    required this.actionVisitedDark,
    required this.actionVisitedLight,
  });
}
