//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorSurfaceSemanticTokens {
  final Color surfaceBrandPrimaryLight;
  final Color surfaceBrandPrimaryDark;
  final Color surfaceBrandSecondaryLight;
  final Color surfaceBrandSecondaryDark;
  final Color surfaceBrandTertiaryLight;
  final Color surfaceBrandTertiaryDark;
  final Color surfaceStatusNeutralMutedLight;
  final Color surfaceStatusNeutralMutedDark;
  final Color surfaceStatusNeutralEmphasizedLight;
  final Color surfaceStatusNeutralEmphasizedDark;
  final Color surfaceStatusPositiveMutedLight;
  final Color surfaceStatusPositiveMutedDark;
  final Color surfaceStatusPositiveEmphasizedLight;
  final Color surfaceStatusPositiveEmphasizedDark;
  final Color surfaceStatusInfoMutedLight;
  final Color surfaceStatusInfoMutedDark;
  final Color surfaceStatusInfoEmphasizedLight;
  final Color surfaceStatusInfoEmphasizedDark;
  final Color surfaceStatusWarningMutedLight;
  final Color surfaceStatusWarningMutedDark;
  final Color surfaceStatusWarningEmphasizedLight;
  final Color surfaceStatusWarningEmphasizedDark;
  final Color surfaceStatusNegativeMutedLight;
  final Color surfaceStatusNegativeMutedDark;
  final Color surfaceStatusNegativeEmphasizedLight;
  final Color surfaceStatusNegativeEmphasizedDark;
  final Color surfaceStatusAccentMutedLight;
  final Color surfaceStatusAccentMutedDark;
  final Color surfaceStatusAccentEmphasizedLight;
  final Color surfaceStatusAccentEmphasizedDark;

  const OudsColorSurfaceSemanticTokens({
    required this.surfaceBrandPrimaryLight,
    required this.surfaceBrandPrimaryDark,
    required this.surfaceBrandSecondaryLight,
    required this.surfaceBrandSecondaryDark,
    required this.surfaceBrandTertiaryLight,
    required this.surfaceBrandTertiaryDark,
    required this.surfaceStatusNeutralMutedLight,
    required this.surfaceStatusNeutralMutedDark,
    required this.surfaceStatusNeutralEmphasizedLight,
    required this.surfaceStatusNeutralEmphasizedDark,
    required this.surfaceStatusPositiveMutedLight,
    required this.surfaceStatusPositiveMutedDark,
    required this.surfaceStatusPositiveEmphasizedLight,
    required this.surfaceStatusPositiveEmphasizedDark,
    required this.surfaceStatusInfoMutedLight,
    required this.surfaceStatusInfoMutedDark,
    required this.surfaceStatusInfoEmphasizedLight,
    required this.surfaceStatusInfoEmphasizedDark,
    required this.surfaceStatusWarningMutedLight,
    required this.surfaceStatusWarningMutedDark,
    required this.surfaceStatusWarningEmphasizedLight,
    required this.surfaceStatusWarningEmphasizedDark,
    required this.surfaceStatusNegativeMutedLight,
    required this.surfaceStatusNegativeMutedDark,
    required this.surfaceStatusNegativeEmphasizedLight,
    required this.surfaceStatusNegativeEmphasizedDark,
    required this.surfaceStatusAccentMutedLight,
    required this.surfaceStatusAccentMutedDark,
    required this.surfaceStatusAccentEmphasizedLight,
    required this.surfaceStatusAccentEmphasizedDark,
  });
}
