//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.7.0
// Generated by Tokenator

import 'package:flutter/material.dart';
  
abstract class OudsColorOpacitySemanticTokens {
  final Color opacityLowerLight;
  final Color opacityLowestLight;
  final Color opacityTransparentLight;
  final Color opacityLowerDark;
  final Color opacityLowestDark;
  final Color opacityTransparentDark;

  const OudsColorOpacitySemanticTokens({
    required this.opacityLowerLight,
    required this.opacityLowestLight,
    required this.opacityTransparentLight,
    required this.opacityLowerDark,
    required this.opacityLowestDark,
    required this.opacityTransparentDark,
  });
}
