//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

abstract class OudsGridSemanticTokens {
  late double compactColumnGap;
  late double compactMargin;
  late int compactMaxWidth;
  late int compactMinWidth;
  late double extraCompactColumnGap;
  late double extraCompactMargin;
  late int extraCompactMaxWidth;
  late int extraCompactMinWidth;
  late double mediumColumnGap;
  late double mediumMargin;
  late int mediumMaxWidth;
  late int mediumMinWidth;
}
