//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorOpacitySemanticTokens {
  final Color opacityLowerDark;
  final Color opacityLowerLight;
  final Color opacityLowestDark;
  final Color opacityLowestLight;
  final Color opacityTransparentDark;
  final Color opacityTransparentLight;

  const OudsColorOpacitySemanticTokens({
    required this.opacityLowerDark,
    required this.opacityLowerLight,
    required this.opacityLowestDark,
    required this.opacityLowestLight,
    required this.opacityTransparentDark,
    required this.opacityTransparentLight,
  });
}
