//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

abstract class OudsBorderSemanticTokens {
  late double widthNone;
  late double widthDefault;
  late double widthThin;
  late double widthMedium;
  late double widthThick;
  late double widthThicker;
  late double widthFocus;
  late double widthFocusInset;
  late double radiusNone;
  late double radiusDefault;
  late double radiusSmall;
  late double radiusMedium;
  late double radiusLarge;
  late double radiusPill;
  late String styleDefault;
  late String styleDrag;
}
