//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.2.0
// Generated by Tokenator

abstract class OudsSizeSemanticTokens {
  late double iconDecorative2xlarge;
  late double iconDecorative2xsmall;
  late double iconDecorative3xsmall;
  late double iconDecorative4xsmall;
  late double iconDecorativeLarge;
  late double iconDecorativeMedium;
  late double iconDecorativeSmall;
  late double iconDecorativeXlarge;
  late double iconDecorativeXsmall;
  late double iconWithBodyLargeSizeLargeMobile;
  late double iconWithBodyLargeSizeLargeTablet;
  late double iconWithBodyLargeSizeMediumMobile;
  late double iconWithBodyLargeSizeMediumTablet;
  late double iconWithBodyLargeSizeSmallMobile;
  late double iconWithBodyLargeSizeSmallTablet;
  late double iconWithBodyMediumSizeLargeMobile;
  late double iconWithBodyMediumSizeLargeTablet;
  late double iconWithBodyMediumSizeMediumMobile;
  late double iconWithBodyMediumSizeMediumTablet;
  late double iconWithBodyMediumSizeSmallMobile;
  late double iconWithBodyMediumSizeSmallTablet;
  late double iconWithBodySmallSizeLargeMobile;
  late double iconWithBodySmallSizeLargeTablet;
  late double iconWithBodySmallSizeMediumMobile;
  late double iconWithBodySmallSizeMediumTablet;
  late double iconWithBodySmallSizeSmallMobile;
  late double iconWithBodySmallSizeSmallTablet;
  late double iconWithHeadingLargeSizeLargeMobile;
  late double iconWithHeadingLargeSizeLargeTablet;
  late double iconWithHeadingLargeSizeMediumMobile;
  late double iconWithHeadingLargeSizeMediumTablet;
  late double iconWithHeadingLargeSizeSmallMobile;
  late double iconWithHeadingLargeSizeSmallTablet;
  late double iconWithHeadingMediumSizeLargeMobile;
  late double iconWithHeadingMediumSizeLargeTablet;
  late double iconWithHeadingMediumSizeMediumMobile;
  late double iconWithHeadingMediumSizeMediumTablet;
  late double iconWithHeadingMediumSizeSmallMobile;
  late double iconWithHeadingMediumSizeSmallTablet;
  late double iconWithHeadingSmallSizeLargeMobile;
  late double iconWithHeadingSmallSizeLargeTablet;
  late double iconWithHeadingSmallSizeMediumMobile;
  late double iconWithHeadingSmallSizeMediumTablet;
  late double iconWithHeadingSmallSizeSmallMobile;
  late double iconWithHeadingSmallSizeSmallTablet;
  late double iconWithHeadingXlargeSizeLargeMobile;
  late double iconWithHeadingXlargeSizeLargeTablet;
  late double iconWithHeadingXlargeSizeMediumMobile;
  late double iconWithHeadingXlargeSizeMediumTablet;
  late double iconWithHeadingXlargeSizeSmallMobile;
  late double iconWithHeadingXlargeSizeSmallTablet;
  late double iconWithLabelLargeSizeLarge;
  late double iconWithLabelLargeSizeMedium;
  late double iconWithLabelLargeSizeSmall;
  late double iconWithLabelLargeSizeXlarge;
  late double iconWithLabelLargeSizeXsmall;
  late double iconWithLabelMediumSizeLarge;
  late double iconWithLabelMediumSizeMedium;
  late double iconWithLabelMediumSizeSmall;
  late double iconWithLabelMediumSizeXsmall;
  late double iconWithLabelSmallSizeLarge;
  late double iconWithLabelSmallSizeMedium;
  late double iconWithLabelSmallSizeSmall;
  late double iconWithLabelSmallSizeXsmall;
  late double iconWithLabelXlargeSizeLarge;
  late double iconWithLabelXlargeSizeMedium;
  late double iconWithLabelXlargeSizeSmall;
  late double maxWidthTypeBodyLargeMobile;
  late double maxWidthTypeBodyLargeTablet;
  late double maxWidthTypeBodyMediumMobile;
  late double maxWidthTypeBodyMediumTablet;
  late double maxWidthTypeBodySmallMobile;
  late double maxWidthTypeBodySmallTablet;
  late double maxWidthTypeDisplayLargeMobile;
  late double maxWidthTypeDisplayLargeTablet;
  late double maxWidthTypeDisplayMediumMobile;
  late double maxWidthTypeDisplayMediumTablet;
  late double maxWidthTypeDisplaySmallMobile;
  late double maxWidthTypeDisplaySmallTablet;
  late double maxWidthTypeHeadingLargeMobile;
  late double maxWidthTypeHeadingLargeTablet;
  late double maxWidthTypeHeadingMediumMobile;
  late double maxWidthTypeHeadingMediumTablet;
  late double maxWidthTypeHeadingSmallMobile;
  late double maxWidthTypeHeadingSmallTablet;
  late double maxWidthTypeHeadingXlargeMobile;
  late double maxWidthTypeHeadingXlargeTablet;
  late double minInteractiveArea;
}
