//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

abstract class OudsBorderSemanticTokens {
  late double radiusDefault;
  late double radiusLarge;
  late double radiusMedium;
  late double radiusNone;
  late double radiusPill;
  late double radiusSmall;
  late String styleDefault;
  late String styleDrag;
  late double widthDefault;
  late double widthFocus;
  late double widthFocusInset;
  late double widthMedium;
  late double widthNone;
  late double widthThick;
  late double widthThicker;
  late double widthThin;
}
