//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.3.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.3.0
//
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorDecorativeSemanticTokens {
  final Color decorativeAccent1Default;
  final Color decorativeAccent1Emphasized;
  final Color decorativeAccent1Muted;
  final Color decorativeAccent2Default;
  final Color decorativeAccent2Emphasized;
  final Color decorativeAccent2Muted;
  final Color decorativeAccent3Default;
  final Color decorativeAccent3Emphasized;
  final Color decorativeAccent3Muted;
  final Color decorativeAccent4Default;
  final Color decorativeAccent4Emphasized;
  final Color decorativeAccent4Muted;
  final Color decorativeAccent5Default;
  final Color decorativeAccent5Emphasized;
  final Color decorativeAccent5Muted;
  final Color decorativeBrandPrimary;
  final Color decorativeBrandPrimaryEmphasized;
  final Color decorativeBrandPrimaryMuted;
  final Color decorativeBrandSecondary;
  final Color decorativeBrandSecondaryEmphasized;
  final Color decorativeBrandSecondaryMuted;
  final Color decorativeBrandTertiary;
  final Color decorativeBrandTertiaryEmphasized;
  final Color decorativeBrandTertiaryMuted;
  final Color decorativeNeutralEmphasizedHigh;
  final Color decorativeNeutralEmphasizedHigher;
  final Color decorativeNeutralEmphasizedHighest;
  final Color decorativeNeutralEmphasizedLow;
  final Color decorativeNeutralEmphasizedLower;
  final Color decorativeNeutralEmphasizedLowest;
  final Color decorativeNeutralEmphasizedMedium;
  final Color decorativeNeutralMutedHigh;
  final Color decorativeNeutralMutedHigher;
  final Color decorativeNeutralMutedHighest;
  final Color decorativeNeutralMutedLow;
  final Color decorativeNeutralMutedLower;
  final Color decorativeNeutralMutedLowest;
  final Color decorativeNeutralMutedMedium;
  final Color decorativeSkinTint100;
  final Color decorativeSkinTint200;
  final Color decorativeSkinTint300;
  final Color decorativeSkinTint400;
  final Color decorativeSkinTint500;
  final Color decorativeSkinTint600;
  final Color decorativeSkinTint700;
  final Color decorativeSkinTint800;
  final Color decorativeSkinTint900;

  const OudsColorDecorativeSemanticTokens({
    required this.decorativeAccent1Default,
    required this.decorativeAccent1Emphasized,
    required this.decorativeAccent1Muted,
    required this.decorativeAccent2Default,
    required this.decorativeAccent2Emphasized,
    required this.decorativeAccent2Muted,
    required this.decorativeAccent3Default,
    required this.decorativeAccent3Emphasized,
    required this.decorativeAccent3Muted,
    required this.decorativeAccent4Default,
    required this.decorativeAccent4Emphasized,
    required this.decorativeAccent4Muted,
    required this.decorativeAccent5Default,
    required this.decorativeAccent5Emphasized,
    required this.decorativeAccent5Muted,
    required this.decorativeBrandPrimary,
    required this.decorativeBrandPrimaryEmphasized,
    required this.decorativeBrandPrimaryMuted,
    required this.decorativeBrandSecondary,
    required this.decorativeBrandSecondaryEmphasized,
    required this.decorativeBrandSecondaryMuted,
    required this.decorativeBrandTertiary,
    required this.decorativeBrandTertiaryEmphasized,
    required this.decorativeBrandTertiaryMuted,
    required this.decorativeNeutralEmphasizedHigh,
    required this.decorativeNeutralEmphasizedHigher,
    required this.decorativeNeutralEmphasizedHighest,
    required this.decorativeNeutralEmphasizedLow,
    required this.decorativeNeutralEmphasizedLower,
    required this.decorativeNeutralEmphasizedLowest,
    required this.decorativeNeutralEmphasizedMedium,
    required this.decorativeNeutralMutedHigh,
    required this.decorativeNeutralMutedHigher,
    required this.decorativeNeutralMutedHighest,
    required this.decorativeNeutralMutedLow,
    required this.decorativeNeutralMutedLower,
    required this.decorativeNeutralMutedLowest,
    required this.decorativeNeutralMutedMedium,
    required this.decorativeSkinTint100,
    required this.decorativeSkinTint200,
    required this.decorativeSkinTint300,
    required this.decorativeSkinTint400,
    required this.decorativeSkinTint500,
    required this.decorativeSkinTint600,
    required this.decorativeSkinTint700,
    required this.decorativeSkinTint800,
    required this.decorativeSkinTint900,
  });
}
