//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorAlwaysSemanticTokens {
  final Color alwaysBlack;
  final Color alwaysWhite;
  final Color alwaysOnBlack;
  final Color alwaysOnWhite;

  const OudsColorAlwaysSemanticTokens({
    required this.alwaysBlack,
    required this.alwaysWhite,
    required this.alwaysOnBlack,
    required this.alwaysOnWhite,
  });
}
