//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.7.0
// Generated by Tokenator

import 'package:flutter/material.dart';
  
abstract class OudsColorSurfaceSemanticTokens {
  final Color surfaceBrandPrimaryLight;
  final Color surfaceBrandPrimaryDark;
  final Color surfaceStatusAccentEmphasizedLight;
  final Color surfaceStatusAccentMutedLight;
  final Color surfaceStatusAccentEmphasizedDark;
  final Color surfaceStatusAccentMutedDark;
  final Color surfaceStatusInfoEmphasizedLight;
  final Color surfaceStatusInfoMutedLight;
  final Color surfaceStatusInfoEmphasizedDark;
  final Color surfaceStatusInfoMutedDark;
  final Color surfaceStatusNegativeEmphasizedLight;
  final Color surfaceStatusNegativeMutedLight;
  final Color surfaceStatusNegativeEmphasizedDark;
  final Color surfaceStatusNegativeMutedDark;
  final Color surfaceStatusNeutralEmphasizedLight;
  final Color surfaceStatusNeutralMutedLight;
  final Color surfaceStatusNeutralEmphasizedDark;
  final Color surfaceStatusNeutralMutedDark;
  final Color surfaceStatusPositiveEmphasizedLight;
  final Color surfaceStatusPositiveMutedLight;
  final Color surfaceStatusPositiveEmphasizedDark;
  final Color surfaceStatusPositiveMutedDark;
  final Color surfaceStatusWarningEmphasizedLight;
  final Color surfaceStatusWarningMutedLight;
  final Color surfaceStatusWarningEmphasizedDark;
  final Color surfaceStatusWarningMutedDark;

  const OudsColorSurfaceSemanticTokens({
    required this.surfaceBrandPrimaryLight,
    required this.surfaceBrandPrimaryDark,
    required this.surfaceStatusAccentEmphasizedLight,
    required this.surfaceStatusAccentMutedLight,
    required this.surfaceStatusAccentEmphasizedDark,
    required this.surfaceStatusAccentMutedDark,
    required this.surfaceStatusInfoEmphasizedLight,
    required this.surfaceStatusInfoMutedLight,
    required this.surfaceStatusInfoEmphasizedDark,
    required this.surfaceStatusInfoMutedDark,
    required this.surfaceStatusNegativeEmphasizedLight,
    required this.surfaceStatusNegativeMutedLight,
    required this.surfaceStatusNegativeEmphasizedDark,
    required this.surfaceStatusNegativeMutedDark,
    required this.surfaceStatusNeutralEmphasizedLight,
    required this.surfaceStatusNeutralMutedLight,
    required this.surfaceStatusNeutralEmphasizedDark,
    required this.surfaceStatusNeutralMutedDark,
    required this.surfaceStatusPositiveEmphasizedLight,
    required this.surfaceStatusPositiveMutedLight,
    required this.surfaceStatusPositiveEmphasizedDark,
    required this.surfaceStatusPositiveMutedDark,
    required this.surfaceStatusWarningEmphasizedLight,
    required this.surfaceStatusWarningMutedLight,
    required this.surfaceStatusWarningEmphasizedDark,
    required this.surfaceStatusWarningMutedDark,
  });
}
