//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.1.0
// Generated by Tokenator

abstract class OudsSpaceSemanticTokens {
  late double columnGap2xlarge;
  late double columnGap2xsmall;
  late double columnGap3xsmall;
  late double columnGapLarge;
  late double columnGapMedium;
  late double columnGapNone;
  late double columnGapSmall;
  late double columnGapXlarge;
  late double columnGapXsmall;
  late double fixed2xlarge;
  late double fixed2xsmall;
  late double fixed3xlarge;
  late double fixed3xsmall;
  late double fixed4xlarge;
  late double fixed5xlarge;
  late double fixedLarge;
  late double fixedMedium;
  late double fixedNone;
  late double fixedSmall;
  late double fixedXlarge;
  late double fixedXsmall;
  late double inset2xlarge;
  late double inset2xsmall;
  late double inset3xlarge;
  late double inset3xsmall;
  late double inset4xsmall;
  late double insetLarge;
  late double insetMedium;
  late double insetNone;
  late double insetSmall;
  late double insetXlarge;
  late double insetXsmall;
  late double paddingBlock2xlarge;
  late double paddingBlock2xsmall;
  late double paddingBlock3xlarge;
  late double paddingBlock3xsmall;
  late double paddingBlock4xlarge;
  late double paddingBlock4xsmall;
  late double paddingBlockLarge;
  late double paddingBlockMedium;
  late double paddingBlockNone;
  late double paddingBlockSmall;
  late double paddingBlockXlarge;
  late double paddingBlockXsmall;
  late double paddingInline2xlarge;
  late double paddingInline2xsmall;
  late double paddingInline3xlarge;
  late double paddingInline3xsmall;
  late double paddingInline4xlarge;
  late double paddingInline4xsmall;
  late double paddingInlineLarge;
  late double paddingInlineMedium;
  late double paddingInlineNone;
  late double paddingInlineSmall;
  late double paddingInlineXlarge;
  late double paddingInlineXsmall;
  late double rowGap2xsmall;
  late double rowGap3xsmall;
  late double rowGapLarge;
  late double rowGapMedium;
  late double rowGapNone;
  late double rowGapSmall;
  late double rowGapXsmall;
  late double scaled2xlargeMobile;
  late double scaled2xlargeTablet;
  late double scaled2xsmallMobile;
  late double scaled2xsmallTablet;
  late double scaled3xlargeMobile;
  late double scaled3xlargeTablet;
  late double scaled3xsmallMobile;
  late double scaled3xsmallTablet;
  late double scaledLargeMobile;
  late double scaledLargeTablet;
  late double scaledMediumMobile;
  late double scaledMediumTablet;
  late double scaledNoneMobile;
  late double scaledNoneTablet;
  late double scaledSmallMobile;
  late double scaledSmallTablet;
  late double scaledXlargeMobile;
  late double scaledXlargeTablet;
  late double scaledXsmallMobile;
  late double scaledXsmallTablet;
}
