//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorOverlaySemanticTokens {
  final Color overlayDragDark;
  final Color overlayDragLight;
  final Color overlayDropdownDark;
  final Color overlayDropdownLight;
  final Color overlayModalDark;
  final Color overlayModalLight;
  final Color overlayTooltipDark;
  final Color overlayTooltipLight;

  const OudsColorOverlaySemanticTokens({
    required this.overlayDragDark,
    required this.overlayDragLight,
    required this.overlayDropdownDark,
    required this.overlayDropdownLight,
    required this.overlayModalDark,
    required this.overlayModalLight,
    required this.overlayTooltipDark,
    required this.overlayTooltipLight,
  });
}
