//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.10.0
// Generated by Tokenator

import 'package:flutter/material.dart';
  
abstract class OudsColorBgSemanticTokens {
  final Color bgEmphasizedLight;
  final Color bgPrimaryLight;
  final Color bgSecondaryLight;
  final Color bgTertiaryLight;
  final Color bgEmphasizedDark;
  final Color bgPrimaryDark;
  final Color bgSecondaryDark;
  final Color bgTertiaryDark;

  const OudsColorBgSemanticTokens({
    required this.bgEmphasizedLight,
    required this.bgPrimaryLight,
    required this.bgSecondaryLight,
    required this.bgTertiaryLight,
    required this.bgEmphasizedDark,
    required this.bgPrimaryDark,
    required this.bgSecondaryDark,
    required this.bgTertiaryDark,
  });
}
