//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsColorSurfaceSemanticTokens {
  final Color surfaceBrandPrimaryDark;
  final Color surfaceBrandPrimaryLight;
  final Color surfaceBrandSecondaryDark;
  final Color surfaceBrandSecondaryLight;
  final Color surfaceBrandTertiaryDark;
  final Color surfaceBrandTertiaryLight;
  final Color surfaceInverseHighDark;
  final Color surfaceInverseHighLight;
  final Color surfaceInverseLowDark;
  final Color surfaceInverseLowLight;
  final Color surfacePrimaryDark;
  final Color surfacePrimaryLight;
  final Color surfaceSecondaryDark;
  final Color surfaceSecondaryLight;
  final Color surfaceStatusAccentEmphasizedDark;
  final Color surfaceStatusAccentEmphasizedLight;
  final Color surfaceStatusAccentMutedDark;
  final Color surfaceStatusAccentMutedLight;
  final Color surfaceStatusInfoEmphasizedDark;
  final Color surfaceStatusInfoEmphasizedLight;
  final Color surfaceStatusInfoMutedDark;
  final Color surfaceStatusInfoMutedLight;
  final Color surfaceStatusNegativeEmphasizedDark;
  final Color surfaceStatusNegativeEmphasizedLight;
  final Color surfaceStatusNegativeMutedDark;
  final Color surfaceStatusNegativeMutedLight;
  final Color surfaceStatusPositiveEmphasizedDark;
  final Color surfaceStatusPositiveEmphasizedLight;
  final Color surfaceStatusPositiveMutedDark;
  final Color surfaceStatusPositiveMutedLight;
  final Color surfaceStatusWarningEmphasizedDark;
  final Color surfaceStatusWarningEmphasizedLight;
  final Color surfaceStatusWarningMutedDark;
  final Color surfaceStatusWarningMutedLight;
  final Color surfaceTertiaryDark;
  final Color surfaceTertiaryLight;

  const OudsColorSurfaceSemanticTokens({
    required this.surfaceBrandPrimaryDark,
    required this.surfaceBrandPrimaryLight,
    required this.surfaceBrandSecondaryDark,
    required this.surfaceBrandSecondaryLight,
    required this.surfaceBrandTertiaryDark,
    required this.surfaceBrandTertiaryLight,
    required this.surfaceInverseHighDark,
    required this.surfaceInverseHighLight,
    required this.surfaceInverseLowDark,
    required this.surfaceInverseLowLight,
    required this.surfacePrimaryDark,
    required this.surfacePrimaryLight,
    required this.surfaceSecondaryDark,
    required this.surfaceSecondaryLight,
    required this.surfaceStatusAccentEmphasizedDark,
    required this.surfaceStatusAccentEmphasizedLight,
    required this.surfaceStatusAccentMutedDark,
    required this.surfaceStatusAccentMutedLight,
    required this.surfaceStatusInfoEmphasizedDark,
    required this.surfaceStatusInfoEmphasizedLight,
    required this.surfaceStatusInfoMutedDark,
    required this.surfaceStatusInfoMutedLight,
    required this.surfaceStatusNegativeEmphasizedDark,
    required this.surfaceStatusNegativeEmphasizedLight,
    required this.surfaceStatusNegativeMutedDark,
    required this.surfaceStatusNegativeMutedLight,
    required this.surfaceStatusPositiveEmphasizedDark,
    required this.surfaceStatusPositiveEmphasizedLight,
    required this.surfaceStatusPositiveMutedDark,
    required this.surfaceStatusPositiveMutedLight,
    required this.surfaceStatusWarningEmphasizedDark,
    required this.surfaceStatusWarningEmphasizedLight,
    required this.surfaceStatusWarningMutedDark,
    required this.surfaceStatusWarningMutedLight,
    required this.surfaceTertiaryDark,
    required this.surfaceTertiaryLight,
  });
}
