//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

abstract class OudsElevationSemanticTokens {
  late double none;
  late double raised;
  late double drag;
  late double overlayDefault;
  late double overlayEmphasized;
  late double stickyDefault;
  late double stickyEmphasized;
  late double stickyNavigationScrolled;
}
