//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_orange/raw/orange_brand_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_border_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
  
class OrangeColorBorderSemanticTokens extends OudsColorBorderSemanticTokens {
  const OrangeColorBorderSemanticTokens({
    super.borderBrandPrimaryLight = OrangeBrandColorRawTokens.colorOrange550,
    super.borderDefaultLight = ColorRawTokens.colorOpacityBlack200,
    super.borderEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.borderFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.borderFocusInsetLight = ColorRawTokens.colorFunctionalWhite,
    super.borderOnBrandPrimaryLight = ColorRawTokens.colorFunctionalBlack,
    super.borderOnBrandPrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.borderBrandPrimaryDark = OrangeBrandColorRawTokens.colorOrange500,
    super.borderDefaultDark = ColorRawTokens.colorOpacityWhite200,
    super.borderEmphasizedDark = ColorRawTokens.colorOpacityWhite920,
    super.borderFocusDark = ColorRawTokens.colorFunctionalLightGray160,
    super.borderFocusInsetDark = ColorRawTokens.colorFunctionalDarkGray880,
  });
}
