//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_always_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorAlwaysSemanticTokens extends OudsColorAlwaysSemanticTokens {
  const OrangeColorAlwaysSemanticTokens({
    super.alwaysBlack = ColorRawTokens.colorFunctionalBlack,
    super.alwaysOnBlack = ColorRawTokens.colorFunctionalGrayLight160,
    super.alwaysOnWhite = ColorRawTokens.colorFunctionalBlack,
    super.alwaysWhite = ColorRawTokens.colorFunctionalWhite,
  });
}
