//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.5.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_content_semantic_tokens.dart';
import 'package:ouds_theme_orange/raw/orange_brand_color_raw_tokens.dart';

class OrangeColorContentSemanticTokens extends OudsColorContentSemanticTokens {
  const OrangeColorContentSemanticTokens({
    super.contentBrandPrimaryLight = OrangeBrandColorRawTokens.colorOrange550,
    super.contentDefaultLight = ColorRawTokens.colorFunctionalBlack,
    super.contentDisabledLight = ColorRawTokens.colorOpacityBlack200,
    super.contentMutedLight = ColorRawTokens.colorOpacityBlack680,
    super.contentOnActionDisabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionEnabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionFocusLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHighlightedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHoverLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionLoadingLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionPressedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionDisabledDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionEnabledDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionFocusDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionHighlightedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionHoverDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionLoadingDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionPressedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnBrandPrimaryLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnBrandPrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnOverlayEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnOverlayEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusEmphasizedAltLight =
        ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusEmphasizedAltDark =
        ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusMutedDark = ColorRawTokens.colorFunctionalLightGray160,
    super.contentStatusInfoLight = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusNegativeLight = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusPositiveLight =
        ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusWarningLight = ColorRawTokens.colorFunctionalSun500,
    super.contentStatusInfoDark = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusNegativeDark = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusPositiveDark =
        ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusWarningDark = ColorRawTokens.colorFunctionalSun500,
    super.contentBrandPrimaryDark = OrangeBrandColorRawTokens.colorOrange500,
    super.contentDefaultDark = ColorRawTokens.colorFunctionalLightGray160,
    super.contentDisabledDark = ColorRawTokens.colorOpacityWhite200,
    super.contentMutedDark = ColorRawTokens.colorOpacityWhite640,
  });
}
