//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_action_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorActionSemanticTokens extends OudsColorActionSemanticTokens {
  const OrangeColorActionSemanticTokens({
    super.actionDisabledDark = ColorRawTokens.colorOpacityWhite200,
    super.actionDisabledLight = ColorRawTokens.colorOpacityBlack200,
    super.actionEnabledDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.actionEnabledLight = ColorRawTokens.colorFunctionalBlack,
    super.actionFocusDark = ColorRawTokens.colorOpacityWhite640,
    super.actionFocusLight = ColorRawTokens.colorOpacityBlack680,
    super.actionHighlightedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.actionHighlightedLight = ColorRawTokens.colorFunctionalBlack,
    super.actionHoverDark = ColorRawTokens.colorOpacityWhite640,
    super.actionHoverLight = ColorRawTokens.colorOpacityBlack680,
    super.actionLoadingDark = OrangeColorRawTokens.colorOrange500,
    super.actionLoadingLight = OrangeColorRawTokens.colorOrange550,
    super.actionNegativeEnabledDark = ColorRawTokens.colorFunctionalScarlet300,
    super.actionNegativeEnabledLight = ColorRawTokens.colorFunctionalScarlet600,
    super.actionNegativeFocusDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeFocusLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeHoverDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeHoverLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeLoadingDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativeLoadingLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionNegativePressedDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativePressedLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionPressedDark = OrangeColorRawTokens.colorOrange500,
    super.actionPressedLight = OrangeColorRawTokens.colorOrange550,
    super.actionSelectedDark = OrangeColorRawTokens.colorOrange500,
    super.actionSelectedLight = OrangeColorRawTokens.colorOrange550,
    super.actionSupportEnabledDark = ColorRawTokens.colorOpacityWhite40,
    super.actionSupportEnabledLight = ColorRawTokens.colorOpacityBlack40,
    super.actionSupportFocusDark = ColorRawTokens.colorOpacityWhite80,
    super.actionSupportFocusLight = ColorRawTokens.colorOpacityBlack80,
    super.actionSupportHoverDark = ColorRawTokens.colorOpacityWhite80,
    super.actionSupportHoverLight = ColorRawTokens.colorOpacityBlack80,
    super.actionSupportLoadingDark = ColorRawTokens.colorOpacityWhite120,
    super.actionSupportLoadingLight = ColorRawTokens.colorOpacityBlack120,
    super.actionSupportPressedDark = ColorRawTokens.colorOpacityWhite120,
    super.actionSupportPressedLight = ColorRawTokens.colorOpacityBlack120,
    super.actionVisitedDark = OrangeColorRawTokens.colorDecorativeAmethyst400,
    super.actionVisitedLight = OrangeColorRawTokens.colorDecorativeAmethyst600,
  });
}
