//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 1.2.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_decorative_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorDecorativeSemanticTokens extends OudsColorDecorativeSemanticTokens {
  const OrangeColorDecorativeSemanticTokens({
    super.decorativeAccent1Default = OrangeColorRawTokens.colorDecorativeEmerald500,
    super.decorativeAccent1Emphasized = OrangeColorRawTokens.colorDecorativeEmerald700,
    super.decorativeAccent1Muted = OrangeColorRawTokens.colorDecorativeEmerald200,
    super.decorativeAccent2Default = OrangeColorRawTokens.colorDecorativeSky400,
    super.decorativeAccent2Emphasized = OrangeColorRawTokens.colorDecorativeSky700,
    super.decorativeAccent2Muted = OrangeColorRawTokens.colorDecorativeSky200,
    super.decorativeAccent3Default = ColorRawTokens.colorFunctionalSun500,
    super.decorativeAccent3Emphasized = OrangeColorRawTokens.colorDecorativeAmber500,
    super.decorativeAccent3Muted = ColorRawTokens.colorFunctionalSun200,
    super.decorativeAccent4Default = OrangeColorRawTokens.colorDecorativeAmethyst400,
    super.decorativeAccent4Emphasized = OrangeColorRawTokens.colorDecorativeAmethyst800,
    super.decorativeAccent4Muted = OrangeColorRawTokens.colorDecorativeAmethyst200,
    super.decorativeAccent5Default = OrangeColorRawTokens.colorDecorativeShockingPink200,
    super.decorativeAccent5Emphasized = OrangeColorRawTokens.colorDecorativeShockingPink300,
    super.decorativeAccent5Muted = OrangeColorRawTokens.colorDecorativeShockingPink100,
    super.decorativeBrandPrimary = OrangeColorRawTokens.colorOrange500,
    super.decorativeBrandPrimaryEmphasized = const Color(0x00ff0000),
    super.decorativeBrandPrimaryMuted = const Color(0x00ff0000),
    super.decorativeBrandSecondary = ColorRawTokens.colorFunctionalBlack,
    super.decorativeBrandSecondaryEmphasized = const Color(0x00ff0000),
    super.decorativeBrandSecondaryMuted = const Color(0x00ff0000),
    super.decorativeBrandTertiary = ColorRawTokens.colorFunctionalWhite,
    super.decorativeBrandTertiaryEmphasized = const Color(0x00ff0000),
    super.decorativeBrandTertiaryMuted = const Color(0x00ff0000),
    super.decorativeNeutralEmphasizedHigh = const Color(0x00ff0000),
    super.decorativeNeutralEmphasizedHigher = ColorRawTokens.colorFunctionalGrayDark640,
    super.decorativeNeutralEmphasizedHighest = const Color(0x00ff0000),
    super.decorativeNeutralEmphasizedLow = ColorRawTokens.colorFunctionalGrayDark400,
    super.decorativeNeutralEmphasizedLower = ColorRawTokens.colorFunctionalGrayDark320,
    super.decorativeNeutralEmphasizedLowest = ColorRawTokens.colorFunctionalGrayDark240,
    super.decorativeNeutralEmphasizedMedium = const Color(0x00ff0000),
    super.decorativeNeutralMutedHigh = ColorRawTokens.colorFunctionalGrayLight400,
    super.decorativeNeutralMutedHigher = ColorRawTokens.colorFunctionalGrayLight800,
    super.decorativeNeutralMutedHighest = ColorRawTokens.colorFunctionalGrayLight960,
    super.decorativeNeutralMutedLow = ColorRawTokens.colorFunctionalGrayLight240,
    super.decorativeNeutralMutedLower = ColorRawTokens.colorFunctionalGrayLight160,
    super.decorativeNeutralMutedLowest = ColorRawTokens.colorFunctionalGrayLight80,
    super.decorativeNeutralMutedMedium = ColorRawTokens.colorFunctionalGrayLight320,
    super.decorativeSkinTint100 = OrangeColorRawTokens.colorDecorativeDeepPeach100,
    super.decorativeSkinTint200 = OrangeColorRawTokens.colorDecorativeDeepPeach200,
    super.decorativeSkinTint300 = OrangeColorRawTokens.colorDecorativeDeepPeach300,
    super.decorativeSkinTint400 = OrangeColorRawTokens.colorDecorativeDeepPeach400,
    super.decorativeSkinTint500 = OrangeColorRawTokens.colorDecorativeDeepPeach500,
    super.decorativeSkinTint600 = OrangeColorRawTokens.colorDecorativeDeepPeach600,
    super.decorativeSkinTint700 = OrangeColorRawTokens.colorDecorativeDeepPeach700,
    super.decorativeSkinTint800 = OrangeColorRawTokens.colorDecorativeDeepPeach800,
    super.decorativeSkinTint900 = OrangeColorRawTokens.colorDecorativeDeepPeach900,
  });
}
