//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_content_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorContentSemanticTokens extends OudsColorContentSemanticTokens {
  const OrangeColorContentSemanticTokens({
    super.contentBrandPrimaryDark = OrangeColorRawTokens.colorOrange500,
    super.contentBrandPrimaryLight = OrangeColorRawTokens.colorOrange550,
    super.contentBrandSecondaryDark = const Color(0x00ff0000),
    super.contentBrandSecondaryLight = const Color(0x00ff0000),
    super.contentBrandTertiaryDark = const Color(0x00ff0000),
    super.contentBrandTertiaryLight = const Color(0x00ff0000),
    super.contentDefaultDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentDefaultLight = ColorRawTokens.colorFunctionalBlack,
    super.contentDisabledDark = ColorRawTokens.colorOpacityWhite200,
    super.contentDisabledLight = ColorRawTokens.colorOpacityBlack200,
    super.contentMutedDark = ColorRawTokens.colorOpacityWhite640,
    super.contentMutedLight = ColorRawTokens.colorOpacityBlack680,
    super.contentOnActionDisabledDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionDisabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionEnabledDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionEnabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionFocusDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionFocusLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHighlightedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionHighlightedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHoverDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionHoverLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionLoadingDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionLoadingLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionPressedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnActionPressedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionSelectedDark = const Color(0x00ff0000),
    super.contentOnActionSelectedLight = const Color(0x00ff0000),
    super.contentOnBrandPrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnBrandPrimaryLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnBrandSecondaryDark = const Color(0x00ff0000),
    super.contentOnBrandSecondaryLight = const Color(0x00ff0000),
    super.contentOnBrandTertiaryDark = const Color(0x00ff0000),
    super.contentOnBrandTertiaryLight = const Color(0x00ff0000),
    super.contentOnOverlayEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnOverlayEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusAccentEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusAccentEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusAccentMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusAccentMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusInfoMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNegativeEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNegativeEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusNegativeMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusNegativeMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNeutralEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNeutralEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusNeutralMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusNeutralMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusPositiveMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusWarningMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentStatusAccentDark = OrangeColorRawTokens.colorOrange500,
    super.contentStatusAccentLight = OrangeColorRawTokens.colorOrange500,
    super.contentStatusInfoDark = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusInfoLight = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusNegativeDark = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusNegativeLight = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusPositiveDark = ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusPositiveLight = ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusWarningDark = ColorRawTokens.colorFunctionalSun500,
    super.contentStatusWarningLight = ColorRawTokens.colorFunctionalSun500,
  });
}
