//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_border_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorBorderSemanticTokens extends OudsColorBorderSemanticTokens {
  const OrangeColorBorderSemanticTokens({
    super.borderBrandPrimaryDark = OrangeColorRawTokens.colorOrange500,
    super.borderBrandPrimaryLight = OrangeColorRawTokens.colorOrange550,
    super.borderBrandSecondaryDark = const Color(0x00ff0000),
    super.borderBrandSecondaryLight = const Color(0x00ff0000),
    super.borderBrandTertiaryDark = const Color(0x00ff0000),
    super.borderBrandTertiaryLight = const Color(0x00ff0000),
    super.borderDefaultDark = ColorRawTokens.colorOpacityWhite200,
    super.borderDefaultLight = ColorRawTokens.colorOpacityBlack200,
    super.borderEmphasizedDark = ColorRawTokens.colorOpacityWhite920,
    super.borderEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.borderFocusDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.borderFocusInsetDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.borderFocusInsetLight = ColorRawTokens.colorFunctionalWhite,
    super.borderFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.borderMutedDark = ColorRawTokens.colorOpacityWhite80,
    super.borderMutedLight = ColorRawTokens.colorOpacityBlack80,
    super.borderOnBrandPrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.borderOnBrandPrimaryLight = ColorRawTokens.colorFunctionalBlack,
    super.borderOnBrandSecondaryDark = const Color(0x00ff0000),
    super.borderOnBrandSecondaryLight = const Color(0x00ff0000),
    super.borderOnBrandTertiaryDark = const Color(0x00ff0000),
    super.borderOnBrandTertiaryLight = const Color(0x00ff0000),
    super.borderStatusAccentDark = const Color(0x00ff0000),
    super.borderStatusAccentLight = const Color(0x00ff0000),
    super.borderStatusInfoDark = const Color(0x00ff0000),
    super.borderStatusInfoLight = const Color(0x00ff0000),
    super.borderStatusNegativeDark = const Color(0x00ff0000),
    super.borderStatusNegativeLight = const Color(0x00ff0000),
    super.borderStatusPositiveDark = const Color(0x00ff0000),
    super.borderStatusPositiveLight = const Color(0x00ff0000),
    super.borderStatusWarningDark = const Color(0x00ff0000),
    super.borderStatusWarningLight = const Color(0x00ff0000),
  });
}
