//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.11.0
// Generated by Tokenator

import 'package:ouds_theme_orange/raw/orange_brand_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_surface_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
  
class OrangeColorSurfaceSemanticTokens extends OudsColorSurfaceSemanticTokens {
  const OrangeColorSurfaceSemanticTokens({
    super.surfaceBrandPrimaryLight = OrangeBrandColorRawTokens.colorOrange500,
    super.surfaceBrandPrimaryDark = OrangeBrandColorRawTokens.colorOrange500,
    super.surfaceStatusAccentEmphasizedLight = ColorRawTokens.colorFunctionalSun500,
    super.surfaceStatusAccentMutedLight = OrangeBrandColorRawTokens.colorWarmGray100,
    super.surfaceStatusAccentEmphasizedDark = ColorRawTokens.colorFunctionalSun300,
    super.surfaceStatusAccentMutedDark = OrangeBrandColorRawTokens.colorWarmGray900,
    super.surfaceStatusInfoEmphasizedLight = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.surfaceStatusInfoMutedLight = ColorRawTokens.colorOpacityDodgerBlue,
    super.surfaceStatusInfoEmphasizedDark = ColorRawTokens.colorFunctionalDodgerBlue300,
    super.surfaceStatusInfoMutedDark = ColorRawTokens.colorFunctionalDodgerBlue900,
    super.surfaceStatusNegativeEmphasizedLight = ColorRawTokens.colorFunctionalScarlet600,
    super.surfaceStatusNegativeMutedLight = ColorRawTokens.colorOpacityScarlet,
    super.surfaceStatusNegativeEmphasizedDark = ColorRawTokens.colorFunctionalScarlet300,
    super.surfaceStatusNegativeMutedDark = ColorRawTokens.colorFunctionalScarlet900,
    super.surfaceStatusNeutralEmphasizedLight = ColorRawTokens.colorOpacityBlack840,
    super.surfaceStatusNeutralMutedLight = ColorRawTokens.colorOpacityBlack40,
    super.surfaceStatusNeutralEmphasizedDark = ColorRawTokens.colorOpacityWhite800,
    super.surfaceStatusNeutralMutedDark = ColorRawTokens.colorOpacityWhite80,
    super.surfaceStatusPositiveEmphasizedLight = ColorRawTokens.colorFunctionalMalachite500,
    super.surfaceStatusPositiveMutedLight = ColorRawTokens.colorOpacityMalachite,
    super.surfaceStatusPositiveEmphasizedDark = ColorRawTokens.colorFunctionalMalachite300,
    super.surfaceStatusPositiveMutedDark = ColorRawTokens.colorFunctionalMalachite900,
    super.surfaceStatusWarningEmphasizedLight = ColorRawTokens.colorFunctionalSun500,
    super.surfaceStatusWarningMutedLight = ColorRawTokens.colorOpacitySun,
    super.surfaceStatusWarningEmphasizedDark = ColorRawTokens.colorFunctionalSun300,
    super.surfaceStatusWarningMutedDark = ColorRawTokens.colorFunctionalSun900,
  });
}
