//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:ouds_theme_orange/raw/orange_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_bg_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class OrangeColorBgSemanticTokens extends OudsColorBgSemanticTokens {
  const OrangeColorBgSemanticTokens({
    super.bgEmphasizedDark = ColorRawTokens.colorFunctionalGrayDark640,
    super.bgEmphasizedLight = ColorRawTokens.colorFunctionalGrayDark880,
    super.bgPrimaryDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.bgPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.bgSecondaryDark = ColorRawTokens.colorFunctionalGrayDark800,
    super.bgSecondaryLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.bgTertiaryDark = OrangeColorRawTokens.colorWarmGray1000,
    super.bgTertiaryLight = OrangeColorRawTokens.colorWarmGray100,
  });
}
