//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_size_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class OrangeSizeSemanticTokens extends OudsSizeSemanticTokens {
  @override
  double get iconDecorative2xlarge => DimensionRawTokens.dimension900;
  @override
  double get iconDecorative2xsmall => DimensionRawTokens.dimension200;
  @override
  double get iconDecorative3xsmall => DimensionRawTokens.dimension150;
  @override
  double get iconDecorative4xsmall => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get iconDecorativeLarge => DimensionRawTokens.dimension600;
  @override
  double get iconDecorativeMedium => DimensionRawTokens.dimension500;
  @override
  double get iconDecorativeSmall => DimensionRawTokens.dimension400;
  @override
  double get iconDecorativeXlarge => DimensionRawTokens.dimension700;
  @override
  double get iconDecorativeXsmall => DimensionRawTokens.dimension300;
  @override
  double get iconWithBodyLargeSizeLargeMobile => DimensionRawTokens.dimension350;
  @override
  double get iconWithBodyLargeSizeLargeTablet => DimensionRawTokens.dimension350;
  @override
  double get iconWithBodyLargeSizeMediumMobile => DimensionRawTokens.dimension300;
  @override
  double get iconWithBodyLargeSizeMediumTablet => DimensionRawTokens.dimension300;
  @override
  double get iconWithBodyLargeSizeSmallMobile => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodyLargeSizeSmallTablet => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodyMediumSizeLargeMobile => DimensionRawTokens.dimension300;
  @override
  double get iconWithBodyMediumSizeLargeTablet => DimensionRawTokens.dimension300;
  @override
  double get iconWithBodyMediumSizeMediumMobile => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodyMediumSizeMediumTablet => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodyMediumSizeSmallMobile => DimensionRawTokens.dimension200;
  @override
  double get iconWithBodyMediumSizeSmallTablet => DimensionRawTokens.dimension200;
  @override
  double get iconWithBodySmallSizeLargeMobile => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodySmallSizeLargeTablet => DimensionRawTokens.dimension250;
  @override
  double get iconWithBodySmallSizeMediumMobile => DimensionRawTokens.dimension200;
  @override
  double get iconWithBodySmallSizeMediumTablet => DimensionRawTokens.dimension200;
  @override
  double get iconWithBodySmallSizeSmallMobile => DimensionRawTokens.dimension150;
  @override
  double get iconWithBodySmallSizeSmallTablet => DimensionRawTokens.dimension150;
  @override
  double get iconWithHeadingLargeSizeLargeMobile => DimensionRawTokens.dimension500;
  @override
  double get iconWithHeadingLargeSizeLargeTablet => DimensionRawTokens.dimension550;
  @override
  double get iconWithHeadingLargeSizeMediumMobile => DimensionRawTokens.dimension450;
  @override
  double get iconWithHeadingLargeSizeMediumTablet => DimensionRawTokens.dimension500;
  @override
  double get iconWithHeadingLargeSizeSmallMobile => DimensionRawTokens.dimension400;
  @override
  double get iconWithHeadingLargeSizeSmallTablet => DimensionRawTokens.dimension450;
  @override
  double get iconWithHeadingMediumSizeLargeMobile => DimensionRawTokens.dimension400;
  @override
  double get iconWithHeadingMediumSizeLargeTablet => DimensionRawTokens.dimension500;
  @override
  double get iconWithHeadingMediumSizeMediumMobile => DimensionRawTokens.dimension350;
  @override
  double get iconWithHeadingMediumSizeMediumTablet => DimensionRawTokens.dimension450;
  @override
  double get iconWithHeadingMediumSizeSmallMobile => DimensionRawTokens.dimension300;
  @override
  double get iconWithHeadingMediumSizeSmallTablet => DimensionRawTokens.dimension400;
  @override
  double get iconWithHeadingSmallSizeLargeMobile => DimensionRawTokens.dimension400;
  @override
  double get iconWithHeadingSmallSizeLargeTablet => DimensionRawTokens.dimension400;
  @override
  double get iconWithHeadingSmallSizeMediumMobile => DimensionRawTokens.dimension350;
  @override
  double get iconWithHeadingSmallSizeMediumTablet => DimensionRawTokens.dimension350;
  @override
  double get iconWithHeadingSmallSizeSmallMobile => DimensionRawTokens.dimension300;
  @override
  double get iconWithHeadingSmallSizeSmallTablet => DimensionRawTokens.dimension300;
  @override
  double get iconWithHeadingXlargeSizeLargeMobile => DimensionRawTokens.dimension550;
  @override
  double get iconWithHeadingXlargeSizeLargeTablet => DimensionRawTokens.dimension650;
  @override
  double get iconWithHeadingXlargeSizeMediumMobile => DimensionRawTokens.dimension500;
  @override
  double get iconWithHeadingXlargeSizeMediumTablet => DimensionRawTokens.dimension600;
  @override
  double get iconWithHeadingXlargeSizeSmallMobile => DimensionRawTokens.dimension450;
  @override
  double get iconWithHeadingXlargeSizeSmallTablet => DimensionRawTokens.dimension550;
  @override
  double get iconWithLabelLargeSizeLarge => DimensionRawTokens.dimension400;
  @override
  double get iconWithLabelLargeSizeMedium => DimensionRawTokens.dimension350;
  @override
  double get iconWithLabelLargeSizeSmall => DimensionRawTokens.dimension300;
  @override
  double get iconWithLabelLargeSizeXlarge => DimensionRawTokens.dimension450;
  @override
  double get iconWithLabelLargeSizeXsmall => DimensionRawTokens.dimension250;
  @override
  double get iconWithLabelMediumSizeLarge => DimensionRawTokens.dimension300;
  @override
  double get iconWithLabelMediumSizeMedium => DimensionRawTokens.dimension250;
  @override
  double get iconWithLabelMediumSizeSmall => DimensionRawTokens.dimension200;
  @override
  double get iconWithLabelMediumSizeXsmall => DimensionRawTokens.dimension150;
  @override
  double get iconWithLabelSmallSizeLarge => DimensionRawTokens.dimension250;
  @override
  double get iconWithLabelSmallSizeMedium => DimensionRawTokens.dimension200;
  @override
  double get iconWithLabelSmallSizeSmall => DimensionRawTokens.dimension150;
  @override
  double get iconWithLabelSmallSizeXsmall => DimensionRawTokens.dimensionOutOfSystem250;
  @override
  double get iconWithLabelXlargeSizeLarge => DimensionRawTokens.dimension500;
  @override
  double get iconWithLabelXlargeSizeMedium => DimensionRawTokens.dimension450;
  @override
  double get iconWithLabelXlargeSizeSmall => DimensionRawTokens.dimension400;
  @override
  double get iconWithLabelXlargeSizeXsmall => DimensionRawTokens.dimension350;
  @override
  double get maxWidthBodyLargeMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthBodyLargeTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthBodyMediumMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthBodyMediumTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthBodySmallMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthBodySmallTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthDisplayLargeMobile => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthDisplayLargeTablet => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthDisplayMediumMobile => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthDisplayMediumTablet => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthDisplaySmallMobile => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthDisplaySmallTablet => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthHeadingLargeMobile => DimensionRawTokens.dimension7000;
  @override
  double get maxWidthHeadingLargeTablet => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthHeadingMediumMobile => DimensionRawTokens.dimension7000;
  @override
  double get maxWidthHeadingMediumTablet => DimensionRawTokens.dimension7000;
  @override
  double get maxWidthHeadingSmallMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthHeadingSmallTablet => DimensionRawTokens.dimension7000;
  @override
  double get maxWidthHeadingXlargeMobile => DimensionRawTokens.dimension7000;
  @override
  double get maxWidthHeadingXlargeTablet => DimensionRawTokens.dimension9000;
  @override
  double get maxWidthLabelLargeMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelLargeTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelMediumMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelMediumTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelSmallMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelSmallTablet => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelXlargeMobile => DimensionRawTokens.dimension6000;
  @override
  double get maxWidthLabelXlargeTablet => DimensionRawTokens.dimension6000;
  @override
  double get minInteractiveArea => DimensionRawTokens.dimension600;
}
