//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 1.2.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_controlItem_tokens.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class OrangeControlItemTokens extends OudsControlItemTokens {
  @override
  double get borderRadius => providersTokens.borderTokens.radiusNone;
  @override
  double get borderRadiusItemOnly => providersTokens.borderTokens.radiusDefault;
  @override
  Color get colorBgFocus => providersTokens.colorScheme.actionSupportFocus;
  @override
  Color get colorBgHover => providersTokens.colorScheme.actionSupportHover;
  @override
  Color get colorBgLoading => providersTokens.colorScheme.actionSupportLoading;
  @override
  Color get colorBgPressed => providersTokens.colorScheme.actionSupportPressed;
  @override
  Color get colorContentLoader => providersTokens.colorScheme.contentDefault;
  @override
  double get sizeIcon => providersTokens.sizeTokens.iconWithLabelLargeSizeMd;
  @override
  double get sizeListItemSizeMinHeightText => providersTokens.sizeTokens.iconWithLabelLargeSizeMd;
  @override
  double get sizeLoader => providersTokens.sizeTokens.iconWithLabelLargeSizeSm;
  @override
  double get sizeMaxHeightAssetsContainer => DimensionRawTokens.dimension1200;
  @override
  double get sizeMinHeight => DimensionRawTokens.dimension650;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension2000;
  @override
  double get spaceColumnGap => providersTokens.spaceTokens.columnGapLg;
  @override
  double get spaceInset => providersTokens.spaceTokens.insetMd;
  @override
  double get spaceRowGap => providersTokens.spaceTokens.rowGapNone;
}
