//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 1.2.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_switch_tokens.dart';

class OrangeSwitchTokens extends OudsSwitchTokens {
  final OudsProvidersTokens providersTokens;

  OrangeSwitchTokens(this.providersTokens);

  @override
  double get borderRadiusCursor => providersTokens.borderTokens.radiusPill;
  @override
  double get borderRadiusTrack => providersTokens.borderTokens.radiusPill;
  @override
  Color get colorCheck => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorCheckInteraction => providersTokens.colorScheme.contentDefault;
  @override
  Color get colorCursor => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralMutedWhite, providersTokens.colorScheme.repositoryNeutralEmphasizedHighest);
  @override
  Color get colorTrackSelected => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPositiveDefault, providersTokens.colorScheme.repositoryPositiveHigh);
  @override
  Color get colorTrackSelectedInteraction => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPositiveHigh, providersTokens.colorScheme.repositoryPositiveLow);
  @override
  Color get colorTrackUnselected => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackMediumHigh, providersTokens.colorScheme.repositoryOpacityWhiteHigh);
  @override
  Color get colorTrackUnselectedInteraction => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackHigh, providersTokens.colorScheme.repositoryOpacityWhiteHigher);
  @override
  double get opacityCheck => providersTokens.opacityTokens.opaque;
  @override
  double get sizeHeightCursorSelected => DimensionRawTokens.dimension300;
  @override
  double get sizeHeightCursorUnselected => DimensionRawTokens.dimension200;
  @override
  double get sizeHeightTrack => DimensionRawTokens.dimension400;
  @override
  double get sizeMaxHeight => DimensionRawTokens.dimension400;
  @override
  double get sizeMinHeight => DimensionRawTokens.dimension400;
  @override
  double get sizeMinHeightInteractiveArea => providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension700;
  @override
  double get sizeWidthCursorSelected => DimensionRawTokens.dimension300;
  @override
  double get sizeWidthCursorSelectedPressed => DimensionRawTokens.dimension400;
  @override
  double get sizeWidthCursorUnselected => DimensionRawTokens.dimension200;
  @override
  double get sizeWidthCursorUnselectedPressed => DimensionRawTokens.dimension300;
  @override
  double get sizeWidthTrack => DimensionRawTokens.dimension700;
  @override
  double get spacePaddingInlineSelected => providersTokens.spaceTokens.paddingInline3xs;
  @override
  double get spacePaddingInlineUnselected => providersTokens.spaceTokens.paddingInlineXs;
}
