//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_link_tokens.dart';

class OrangeLinkTokens extends OudsLinkTokens {
  final OudsProvidersTokens providersTokens;

  OrangeLinkTokens(this.providersTokens);

  @override
  Color get colorChevronEnabled => providersTokens.colorScheme.contentBrandPrimary;
  @override
  Color get colorChevronFocus => providersTokens.colorScheme.contentBrandPrimary;
  @override
  Color get colorChevronHover => providersTokens.colorScheme.contentBrandPrimary;
  @override
  Color get colorChevronPressed => providersTokens.colorScheme.contentBrandPrimary;
  @override
  Color get colorContentEnabled => providersTokens.colorScheme.actionEnabled;
  @override
  Color get colorContentFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorContentHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorContentPressed => providersTokens.colorScheme.actionPressed;
  @override
  double get sizeIconDefault => providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeIconSmall => providersTokens.sizeTokens.iconWithLabelMediumSizeSmall;
  @override
  double get sizeMinHeightCompactDensity => DimensionRawTokens.dimension400;
  @override
  double get sizeMinHeightDefault => providersTokens.sizeTokens.minInteractiveAreaDefault;
  @override
  double get sizeMinHeightSmall => providersTokens.sizeTokens.minInteractiveAreaSmall;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension400;
  @override
  double get spaceColumnGapChevronDefault => providersTokens.spaceTokens.columnGap2xsmall;
  @override
  double get spaceColumnGapChevronSmall => providersTokens.spaceTokens.columnGap2xsmall;
  @override
  double get spaceColumnGapIconDefault => providersTokens.spaceTokens.columnGapSmall;
  @override
  double get spaceColumnGapIconSmall => providersTokens.spaceTokens.columnGapXsmall;
  @override
  double get spacePaddingBlockDefault => providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingBlockDefaultCompactDensity => providersTokens.spaceTokens.paddingBlock3xsmall;
  @override
  double get spacePaddingBlockSmall => providersTokens.spaceTokens.paddingBlockSmall;
  @override
  double get spacePaddingBlockSmallCompactDensity => providersTokens.spaceTokens.paddingBlock2xsmall;
  @override
  double get spacePaddingInline => providersTokens.spaceTokens.paddingInlineNone;
}
