//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsButtonTokens {
  late double borderRadiusDefault;
  late double borderRadiusRounded;
  late double borderRadiusSocial;
  late double borderWidthDefault;
  late double borderWidthDefaultInteraction;
  late double borderWidthDefaultInteractionMono;
  late Color colorBgBrandEnabled;
  late Color colorBgBrandFocus;
  late Color colorBgBrandHover;
  late Color colorBgBrandLoading;
  late Color colorBgBrandPressed;
  late Color colorBgDefaultDisabled;
  late Color colorBgDefaultEnabled;
  late Color colorBgDefaultFocus;
  late Color colorBgDefaultHover;
  late Color colorBgDefaultLoading;
  late Color colorBgDefaultPressed;
  late Color colorBgMinimalFocus;
  late Color colorBgMinimalHover;
  late Color colorBgMinimalPressed;
  late Color colorBorderDefaultDisabled;
  late Color colorBorderDefaultEnabled;
  late Color colorBorderDefaultFocus;
  late Color colorBorderDefaultHover;
  late Color colorBorderDefaultLoading;
  late Color colorBorderDefaultPressed;
  late Color colorContentBrandEnabled;
  late Color colorContentBrandFocus;
  late Color colorContentBrandHover;
  late Color colorContentBrandLoading;
  late Color colorContentBrandPressed;
  late Color colorContentDefaultDisabled;
  late Color colorContentDefaultEnabled;
  late Color colorContentDefaultFocus;
  late Color colorContentDefaultHover;
  late Color colorContentDefaultLoading;
  late Color colorContentDefaultPressed;
  late Color colorContentMinimalDisabled;
  late Color colorContentMinimalEnabled;
  late Color colorContentMinimalFocus;
  late Color colorContentMinimalHover;
  late Color colorContentMinimalLoading;
  late Color colorContentMinimalPressed;
  late double sizeIcon;
  late double sizeIconOnly;
  late double sizeLoader;
  late double sizeMaxHeightIconOnly;
  late double sizeMinHeight;
  late double sizeMinWidth;
  late double spaceColumnGapChevron;
  late double spaceColumnGapIcon;
  late double spaceColumnGapIconChevron;
  late double spaceInsetIconOnly;
  late double spacePaddingBlock;
  late double spacePaddingInlineChevronEnd;
  late double spacePaddingInlineChevronStart;
  late double spacePaddingInlineEndIconStart;
  late double spacePaddingInlineIconNone;
  late double spacePaddingInlineIconStart;
  late double spacePaddingInlineStartIconEnd;
}
