//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsControlItemTokens {
  late double borderRadiusCurrentIndicator;
  late double borderRadiusDefault;
  late double borderRadiusMedia;
  late double borderRadiusMediaRoundedCorner;
  late double borderRadiusRounded;
  late double borderWidthCurrentPage;
  late double borderWidthDefault;
  late Color colorBadgeSafetyArea;
  late Color colorBgCurrentDisabled;
  late Color colorBgCurrentEnabled;
  late Color colorBgCurrentFocus;
  late Color colorBgCurrentHover;
  late Color colorBgCurrentPressed;
  late Color colorContentCurrentDisabled;
  late Color colorContentCurrentEnabled;
  late Color colorContentCurrentFocus;
  late Color colorContentCurrentHover;
  late Color colorContentCurrentPressed;
  late double fontLetterSpacingAvatarInitialXlarge;
  late double fontLineHeightAvatarInitialXlarge;
  late double fontSizeAvatarInitialXlarge;
  late double opacityCurrentDivider;
  late double opacityCurrentIndicator;
  late double sizeAssetLarge;
  late double sizeAssetMedium;
  late double sizeAssetSmall;
  late double sizeAssetXlarge;
  late double sizeControlIndicator;
  late double sizeCurrentIndicatorWidth;
  late double sizeFlagHeight;
  late double sizeMaxWidth;
  late double sizeMinHeightCompact;
  late double sizeMinHeightDefault;
  late double sizeMinWidth;
  late double spaceColumnGap;
  late double spacePaddingBlockBottomSlot;
  late double spacePaddingBlockDensityCompact;
  late double spacePaddingBlockDensityCompactBottomExpandContainer;
  late double spacePaddingBlockDensityCompactTopAlignmentTopCounterweight;
  late double spacePaddingBlockDensityCompactTopAlignmentTopTextContainer;
  late double spacePaddingBlockDensityDefault;
  late double spacePaddingBlockDensityDefaultBottomExpandContainer;
  late double spacePaddingBlockDensityDefaultTopAlignmentTopCounterweight;
  late double spacePaddingBlockDensityDefaultTopAlignmentTopTextContainer;
  late double spacePaddingBlockTopHelperText;
  late double spacePaddingInline;
  late double spaceRowGap;
}
