//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsLinkTokens {
  late Color colorChevronEnabled;
  late Color colorChevronFocus;
  late Color colorChevronHover;
  late Color colorChevronPressed;
  late Color colorContentEnabled;
  late Color colorContentFocus;
  late Color colorContentHover;
  late Color colorContentPressed;
  late double sizeIconDefault;
  late double sizeIconSmall;
  late double sizeMinHeightDefault;
  late double sizeMinHeightSmall;
  late double sizeMinWidthDefault;
  late double sizeMinWidthSmall;
  late double spaceColumnGapChevronDefault;
  late double spaceColumnGapChevronSmall;
  late double spaceColumnGapIconDefault;
  late double spaceColumnGapIconSmall;
  late double spacePaddingBlock;
  late double spacePaddingInline;
}
