//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.0.0
// Generated by Tokenator

abstract class OudsBadgeTokens {
  late double sizeLarge;
  late double sizeMedium;
  late double sizeSmall;
  late double sizeXsmall;
  late double spaceInset;
  late double spacePaddingInlineLarge;
  late double spacePaddingInlineMedium;
}
