//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.10.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class OudsButtonTokens {
  final double borderRadius;
  final double borderWidthDefault;
  final double borderWidthDefaultInteraction;
  final double borderWidthDefaultInteractionMono;
  final double borderWidthMinimal;
  final double borderWidthMinimalInteraction;
  final Color colorBgDefaultDisabled;
  final Color colorBgDefaultDisabledMono;
  final Color colorBgDefaultEnabled;
  final Color colorBgDefaultEnabledMono;
  final Color colorBgDefaultFocus;
  final Color colorBgDefaultFocusMono;
  final Color colorBgDefaultHover;
  final Color colorBgDefaultHoverMono;
  final Color colorBgDefaultLoading;
  final Color colorBgDefaultLoadingMono;
  final Color colorBgDefaultPressed;
  final Color colorBgDefaultPressedMono;
  final Color colorBgMinimalDisabled;
  final Color colorBgMinimalDisabledMono;
  final Color colorBgMinimalEnabled;
  final Color colorBgMinimalEnabledMono;
  final Color colorBgMinimalFocus;
  final Color colorBgMinimalFocusMono;
  final Color colorBgMinimalHover;
  final Color colorBgMinimalHoverMono;
  final Color colorBgMinimalLoading;
  final Color colorBgMinimalLoadingMono;
  final Color colorBgMinimalPressed;
  final Color colorBgMinimalPressedMono;
  final Color colorBgStrongDisabledMono;
  final Color colorBgStrongEnabledMono;
  final Color colorBgStrongFocusMono;
  final Color colorBgStrongHoverMono;
  final Color colorBgStrongLoadingMono;
  final Color colorBgStrongPressedMono;
  final Color colorBorderDefaultDisabled;
  final Color colorBorderDefaultDisabledMono;
  final Color colorBorderDefaultEnabled;
  final Color colorBorderDefaultEnabledMono;
  final Color colorBorderDefaultFocus;
  final Color colorBorderDefaultFocusMono;
  final Color colorBorderDefaultHover;
  final Color colorBorderDefaultHoverMono;
  final Color colorBorderDefaultLoading;
  final Color colorBorderDefaultLoadingMono;
  final Color colorBorderDefaultPressed;
  final Color colorBorderDefaultPressedMono;
  final Color colorBorderMinimalDisabled;
  final Color colorBorderMinimalDisabledMono;
  final Color colorBorderMinimalEnabled;
  final Color colorBorderMinimalEnabledMono;
  final Color colorBorderMinimalFocus;
  final Color colorBorderMinimalFocusMono;
  final Color colorBorderMinimalHover;
  final Color colorBorderMinimalHoverMono;
  final Color colorBorderMinimalLoading;
  final Color colorBorderMinimalLoadingMono;
  final Color colorBorderMinimalPressed;
  final Color colorBorderMinimalPressedMono;
  final Color colorBorderStrongDisabledMono;
  final Color colorBorderStrongEnabledMono;
  final Color colorBorderStrongFocusMono;
  final Color colorBorderStrongHoverMono;
  final Color colorBorderStrongLoadingMono;
  final Color colorBorderStrongPressedMono;
  final Color colorContentDefaultDisabled;
  final Color colorContentDefaultDisabledMono;
  final Color colorContentDefaultEnabled;
  final Color colorContentDefaultEnabledMono;
  final Color colorContentDefaultFocus;
  final Color colorContentDefaultFocusMono;
  final Color colorContentDefaultHover;
  final Color colorContentDefaultHoverMono;
  final Color colorContentDefaultLoading;
  final Color colorContentDefaultLoadingMono;
  final Color colorContentDefaultPressed;
  final Color colorContentDefaultPressedMono;
  final Color colorContentMinimalDisabled;
  final Color colorContentMinimalDisabledMono;
  final Color colorContentMinimalEnabled;
  final Color colorContentMinimalEnabledMono;
  final Color colorContentMinimalFocus;
  final Color colorContentMinimalFocusMono;
  final Color colorContentMinimalHover;
  final Color colorContentMinimalHoverMono;
  final Color colorContentMinimalLoading;
  final Color colorContentMinimalLoadingMono;
  final Color colorContentMinimalPressed;
  final Color colorContentMinimalPressedMono;
  final Color colorContentStrongDisabledMono;
  final Color colorContentStrongEnabledMono;
  final Color colorContentStrongFocusMono;
  final Color colorContentStrongHoverMono;
  final Color colorContentStrongLoadingMono;
  final Color colorContentStrongPressedMono;
  final double sizeIcon;
  final double sizeIconOnly;
  final double sizeLoader;
  final double sizeMaxHeightIconOnly;
  final double sizeMinHeight;
  final double sizeMinWidth;
  final double spaceColumnGapArrow;
  final double spaceColumnGapIcon;
  final double spaceInsetIconOnly;
  final double spacePaddingBlock;
  final double spacePaddingInlineArrowEnd;
  final double spacePaddingInlineArrowStart;
  final double spacePaddingInlineEndIconStart;
  final double spacePaddingInlineIconNone;
  final double spacePaddingInlineIconStart;
  final double spacePaddingInlineStartIconEnd;

  OudsButtonTokens({
    required OudsProvidersTokens providersTokens,
    double? borderRadius,
    double? borderWidthDefault,
    double? borderWidthDefaultInteraction,
    double? borderWidthDefaultInteractionMono,
    double? borderWidthMinimal,
    double? borderWidthMinimalInteraction,
    Color? colorBgDefaultDisabled,
    Color? colorBgDefaultDisabledMono,
    Color? colorBgDefaultEnabled,
    Color? colorBgDefaultEnabledMono,
    Color? colorBgDefaultFocus,
    Color? colorBgDefaultFocusMono,
    Color? colorBgDefaultHover,
    Color? colorBgDefaultHoverMono,
    Color? colorBgDefaultLoading,
    Color? colorBgDefaultLoadingMono,
    Color? colorBgDefaultPressed,
    Color? colorBgDefaultPressedMono,
    Color? colorBgMinimalDisabled,
    Color? colorBgMinimalDisabledMono,
    Color? colorBgMinimalEnabled,
    Color? colorBgMinimalEnabledMono,
    Color? colorBgMinimalFocus,
    Color? colorBgMinimalFocusMono,
    Color? colorBgMinimalHover,
    Color? colorBgMinimalHoverMono,
    Color? colorBgMinimalLoading,
    Color? colorBgMinimalLoadingMono,
    Color? colorBgMinimalPressed,
    Color? colorBgMinimalPressedMono,
    Color? colorBgStrongDisabledMono,
    Color? colorBgStrongEnabledMono,
    Color? colorBgStrongFocusMono,
    Color? colorBgStrongHoverMono,
    Color? colorBgStrongLoadingMono,
    Color? colorBgStrongPressedMono,
    Color? colorBorderDefaultDisabled,
    Color? colorBorderDefaultDisabledMono,
    Color? colorBorderDefaultEnabled,
    Color? colorBorderDefaultEnabledMono,
    Color? colorBorderDefaultFocus,
    Color? colorBorderDefaultFocusMono,
    Color? colorBorderDefaultHover,
    Color? colorBorderDefaultHoverMono,
    Color? colorBorderDefaultLoading,
    Color? colorBorderDefaultLoadingMono,
    Color? colorBorderDefaultPressed,
    Color? colorBorderDefaultPressedMono,
    Color? colorBorderMinimalDisabled,
    Color? colorBorderMinimalDisabledMono,
    Color? colorBorderMinimalEnabled,
    Color? colorBorderMinimalEnabledMono,
    Color? colorBorderMinimalFocus,
    Color? colorBorderMinimalFocusMono,
    Color? colorBorderMinimalHover,
    Color? colorBorderMinimalHoverMono,
    Color? colorBorderMinimalLoading,
    Color? colorBorderMinimalLoadingMono,
    Color? colorBorderMinimalPressed,
    Color? colorBorderMinimalPressedMono,
    Color? colorBorderStrongDisabledMono,
    Color? colorBorderStrongEnabledMono,
    Color? colorBorderStrongFocusMono,
    Color? colorBorderStrongHoverMono,
    Color? colorBorderStrongLoadingMono,
    Color? colorBorderStrongPressedMono,
    Color? colorContentDefaultDisabled,
    Color? colorContentDefaultDisabledMono,
    Color? colorContentDefaultEnabled,
    Color? colorContentDefaultEnabledMono,
    Color? colorContentDefaultFocus,
    Color? colorContentDefaultFocusMono,
    Color? colorContentDefaultHover,
    Color? colorContentDefaultHoverMono,
    Color? colorContentDefaultLoading,
    Color? colorContentDefaultLoadingMono,
    Color? colorContentDefaultPressed,
    Color? colorContentDefaultPressedMono,
    Color? colorContentMinimalDisabled,
    Color? colorContentMinimalDisabledMono,
    Color? colorContentMinimalEnabled,
    Color? colorContentMinimalEnabledMono,
    Color? colorContentMinimalFocus,
    Color? colorContentMinimalFocusMono,
    Color? colorContentMinimalHover,
    Color? colorContentMinimalHoverMono,
    Color? colorContentMinimalLoading,
    Color? colorContentMinimalLoadingMono,
    Color? colorContentMinimalPressed,
    Color? colorContentMinimalPressedMono,
    Color? colorContentStrongDisabledMono,
    Color? colorContentStrongEnabledMono,
    Color? colorContentStrongFocusMono,
    Color? colorContentStrongHoverMono,
    Color? colorContentStrongLoadingMono,
    Color? colorContentStrongPressedMono,
    double? sizeIcon,
    double? sizeIconOnly,
    double? sizeLoader,
    double? sizeMaxHeightIconOnly,
    double? sizeMinHeight,
    double? sizeMinWidth,
    double? spaceColumnGapArrow,
    double? spaceColumnGapIcon,
    double? spaceInsetIconOnly,
    double? spacePaddingBlock,
    double? spacePaddingInlineArrowEnd,
    double? spacePaddingInlineArrowStart,
    double? spacePaddingInlineEndIconStart,
    double? spacePaddingInlineIconNone,
    double? spacePaddingInlineIconStart,
    double? spacePaddingInlineStartIconEnd
  }) :
    borderRadius = borderRadius ?? providersTokens.borderTokens.radiusDefault,
    borderWidthDefault = borderWidthDefault ?? providersTokens.borderTokens.widthDefault,
    borderWidthDefaultInteraction = borderWidthDefaultInteraction ?? providersTokens.borderTokens.widthMedium,
    borderWidthDefaultInteractionMono = borderWidthDefaultInteractionMono ?? providersTokens.borderTokens.widthNone,
    borderWidthMinimal = borderWidthMinimal ?? providersTokens.borderTokens.widthNone,
    borderWidthMinimalInteraction = borderWidthMinimalInteraction ?? providersTokens.borderTokens.widthNone,
    colorBgDefaultDisabled = colorBgDefaultDisabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultDisabledMono = colorBgDefaultDisabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultEnabled = colorBgDefaultEnabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultEnabledMono = colorBgDefaultEnabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultFocus = colorBgDefaultFocus ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultFocusMono = colorBgDefaultFocusMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgDefaultHover = colorBgDefaultHover ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultHoverMono = colorBgDefaultHoverMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgDefaultLoading = colorBgDefaultLoading ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultLoadingMono = colorBgDefaultLoadingMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBgDefaultPressed = colorBgDefaultPressed ?? providersTokens.colorScheme.opacityTransparent,
    colorBgDefaultPressedMono = colorBgDefaultPressedMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBgMinimalDisabled = colorBgMinimalDisabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBgMinimalDisabledMono = colorBgMinimalDisabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBgMinimalEnabled = colorBgMinimalEnabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBgMinimalEnabledMono = colorBgMinimalEnabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBgMinimalFocus = colorBgMinimalFocus ?? providersTokens.colorScheme.actionSupportFocus,
    colorBgMinimalFocusMono = colorBgMinimalFocusMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgMinimalHover = colorBgMinimalHover ?? providersTokens.colorScheme.actionSupportHover,
    colorBgMinimalHoverMono = colorBgMinimalHoverMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgMinimalLoading = colorBgMinimalLoading ?? providersTokens.colorScheme.actionSupportLoading,
    colorBgMinimalLoadingMono = colorBgMinimalLoadingMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBgMinimalPressed = colorBgMinimalPressed ?? providersTokens.colorScheme.actionSupportPressed,
    colorBgMinimalPressedMono = colorBgMinimalPressedMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBgStrongDisabledMono = colorBgStrongDisabledMono ?? providersTokens.colorScheme.repositoryOpacityBlackMedium,
    colorBgStrongEnabledMono = colorBgStrongEnabledMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorBgStrongFocusMono = colorBgStrongFocusMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgStrongHoverMono = colorBgStrongHoverMono ?? providersTokens.colorScheme.repositoryOpacityBlackHigher,
    colorBgStrongLoadingMono = colorBgStrongLoadingMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBgStrongPressedMono = colorBgStrongPressedMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigher,
    colorBorderDefaultDisabled = colorBorderDefaultDisabled ?? providersTokens.colorScheme.actionDisabled,
    colorBorderDefaultDisabledMono = colorBorderDefaultDisabledMono ?? providersTokens.colorScheme.repositoryOpacityBlackMedium,
    colorBorderDefaultEnabled = colorBorderDefaultEnabled ?? providersTokens.colorScheme.actionEnabled,
    colorBorderDefaultEnabledMono = colorBorderDefaultEnabledMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorBorderDefaultFocus = colorBorderDefaultFocus ?? providersTokens.colorScheme.actionFocus,
    colorBorderDefaultFocusMono = colorBorderDefaultFocusMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderDefaultHover = colorBorderDefaultHover ?? providersTokens.colorScheme.actionHover,
    colorBorderDefaultHoverMono = colorBorderDefaultHoverMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderDefaultLoading = colorBorderDefaultLoading ?? providersTokens.colorScheme.actionLoading,
    colorBorderDefaultLoadingMono = colorBorderDefaultLoadingMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderDefaultPressed = colorBorderDefaultPressed ?? providersTokens.colorScheme.actionPressed,
    colorBorderDefaultPressedMono = colorBorderDefaultPressedMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalDisabled = colorBorderMinimalDisabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalDisabledMono = colorBorderMinimalDisabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalEnabled = colorBorderMinimalEnabled ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalEnabledMono = colorBorderMinimalEnabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalFocus = colorBorderMinimalFocus ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalFocusMono = colorBorderMinimalFocusMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalHover = colorBorderMinimalHover ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalHoverMono = colorBorderMinimalHoverMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalLoading = colorBorderMinimalLoading ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalLoadingMono = colorBorderMinimalLoadingMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalPressed = colorBorderMinimalPressed ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderMinimalPressedMono = colorBorderMinimalPressedMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongDisabledMono = colorBorderStrongDisabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongEnabledMono = colorBorderStrongEnabledMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongFocusMono = colorBorderStrongFocusMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongHoverMono = colorBorderStrongHoverMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongLoadingMono = colorBorderStrongLoadingMono ?? providersTokens.colorScheme.opacityTransparent,
    colorBorderStrongPressedMono = colorBorderStrongPressedMono ?? providersTokens.colorScheme.opacityTransparent,
    colorContentDefaultDisabled = colorContentDefaultDisabled ?? providersTokens.colorScheme.actionDisabled,
    colorContentDefaultDisabledMono = colorContentDefaultDisabledMono ?? providersTokens.colorScheme.repositoryOpacityBlackMedium,
    colorContentDefaultEnabled = colorContentDefaultEnabled ?? providersTokens.colorScheme.actionEnabled,
    colorContentDefaultEnabledMono = colorContentDefaultEnabledMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentDefaultFocus = colorContentDefaultFocus ?? providersTokens.colorScheme.actionFocus,
    colorContentDefaultFocusMono = colorContentDefaultFocusMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentDefaultHover = colorContentDefaultHover ?? providersTokens.colorScheme.actionHover,
    colorContentDefaultHoverMono = colorContentDefaultHoverMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentDefaultLoading = colorContentDefaultLoading ?? providersTokens.colorScheme.actionLoading,
    colorContentDefaultLoadingMono = colorContentDefaultLoadingMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentDefaultPressed = colorContentDefaultPressed ?? providersTokens.colorScheme.actionPressed,
    colorContentDefaultPressedMono = colorContentDefaultPressedMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentMinimalDisabled = colorContentMinimalDisabled ?? providersTokens.colorScheme.actionDisabled,
    colorContentMinimalDisabledMono = colorContentMinimalDisabledMono ?? providersTokens.colorScheme.repositoryOpacityBlackMedium,
    colorContentMinimalEnabled = colorContentMinimalEnabled ?? providersTokens.colorScheme.actionEnabled,
    colorContentMinimalEnabledMono = colorContentMinimalEnabledMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentMinimalFocus = colorContentMinimalFocus ?? providersTokens.colorScheme.actionFocus,
    colorContentMinimalFocusMono = colorContentMinimalFocusMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentMinimalHover = colorContentMinimalHover ?? providersTokens.colorScheme.actionHover,
    colorContentMinimalHoverMono = colorContentMinimalHoverMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentMinimalLoading = colorContentMinimalLoading ?? providersTokens.colorScheme.contentDefault,
    colorContentMinimalLoadingMono = colorContentMinimalLoadingMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentMinimalPressed = colorContentMinimalPressed ?? providersTokens.colorScheme.actionPressed,
    colorContentMinimalPressedMono = colorContentMinimalPressedMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentStrongDisabledMono = colorContentStrongDisabledMono ?? providersTokens.colorScheme.repositoryOpacityWhiteHigh,
    colorContentStrongEnabledMono = colorContentStrongEnabledMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentStrongFocusMono = colorContentStrongFocusMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentStrongHoverMono = colorContentStrongHoverMono ?? providersTokens.colorScheme.repositoryNeutralMutedWhite,
    colorContentStrongLoadingMono = colorContentStrongLoadingMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    colorContentStrongPressedMono = colorContentStrongPressedMono ?? providersTokens.colorScheme.repositoryNeutralEmphasizedBlack,
    sizeIcon = sizeIcon ?? providersTokens.sizeTokens.iconWithLabelLargeSizeXs,
    sizeIconOnly = sizeIconOnly ?? providersTokens.sizeTokens.iconWithLabelLargeSizeSm,
    sizeLoader = sizeLoader ?? providersTokens.sizeTokens.iconWithLabelLargeSizeXs,
    sizeMaxHeightIconOnly = sizeMaxHeightIconOnly ?? DimensionRawTokens.dimension600,
    sizeMinHeight = sizeMinHeight ?? DimensionRawTokens.dimension600,
    sizeMinWidth = sizeMinWidth ?? DimensionRawTokens.dimension600,
    spaceColumnGapArrow = spaceColumnGapArrow ?? providersTokens.spaceTokens.columnGapShorter,
    spaceColumnGapIcon = spaceColumnGapIcon ?? providersTokens.spaceTokens.columnGapShort,
    spaceInsetIconOnly = spaceInsetIconOnly ?? providersTokens.spaceTokens.insetMedium,
    spacePaddingBlock = spacePaddingBlock ?? providersTokens.spaceTokens.paddingBlockMedium,
    spacePaddingInlineArrowEnd = spacePaddingInlineArrowEnd ?? providersTokens.spaceTokens.paddingInlineTall,
    spacePaddingInlineArrowStart = spacePaddingInlineArrowStart ?? providersTokens.spaceTokens.paddingInlineTall,
    spacePaddingInlineEndIconStart = spacePaddingInlineEndIconStart ?? providersTokens.spaceTokens.paddingInlineSpacious,
    spacePaddingInlineIconNone = spacePaddingInlineIconNone ?? providersTokens.spaceTokens.paddingInlineHuge,
    spacePaddingInlineIconStart = spacePaddingInlineIconStart ?? providersTokens.spaceTokens.paddingInlineTaller,
    spacePaddingInlineStartIconEnd = spacePaddingInlineStartIconEnd ?? providersTokens.spaceTokens.paddingInlineSpacious;
}
