//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.6.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsListItemTokens {
  late double borderRadiusCurrentIndicator;
  late double borderRadiusDefault;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double borderRadiusItemOnly;
  late double borderRadiusMedia;
  late double borderRadiusMediaRounded;
  late double borderRadiusRounded;
  late double borderWidthCurrentPage;
  late double borderWidthDefault;
  late Color colorBgBadgeSafetyArea;
  late Color colorBgCurrentDisabled;
  late Color colorBgCurrentEnabled;
  late Color colorBgCurrentFocus;
  late Color colorBgCurrentHover;
  late Color colorBgCurrentPressed;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late Color colorBgFocus;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late Color colorBgHover;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late Color colorBgLoading;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late Color colorBgPressed;
  late Color colorContentCurrentDisabled;
  late Color colorContentCurrentEnabled;
  late Color colorContentCurrentFocus;
  late Color colorContentCurrentHover;
  late Color colorContentCurrentPressed;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late Color colorContentLoader;
  late double fontLetterSpacingAvatarInitialXlarge;
  late double fontLineHeightAvatarInitialXlarge;
  late double fontSizeAvatarInitialXlarge;
  late double opacityCurrentDivider;
  late double opacityCurrentIndicator;
  late double sizeAssetLarge;
  late double sizeAssetMedium;
  late double sizeAssetSmall;
  late double sizeAssetXlarge;
  late double sizeControlIndicator;
  late double sizeCurrentIndicatorWidth;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double sizeErrorIcon;
  late double sizeFlagHeight;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double sizeIcon;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double sizeLoader;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double sizeMaxHeightAssetsContainer;
  late double sizeMaxSizeLeadingTrailingSlot;
  late double sizeMaxWidth;
  late double sizeMinHeightDefault;
  late double sizeMinHeightSmall;
  late double sizeMinWidth;
  late double spaceColumnGap;
  late double spacePaddingBlockBottomSlotListItemContainer;
  late double spacePaddingBlockDefault;
  late double spacePaddingBlockSlotTextContainer;
  late double spacePaddingBlockSmall;
  late double spacePaddingBlockTopAlignmentTopCounterweightDefault;
  late double spacePaddingBlockTopAlignmentTopCounterweightSmall;
  late double spacePaddingBlockTopAlignmentTopTextContainerDefault;
  late double spacePaddingBlockTopAlignmentTopTextContainerSmall;
  late double spacePaddingBlockTopHelperText;
  late double spacePaddingInline;
  @Deprecated("This token is deprecated and will be removed in a future version.")
  late double spacePaddingInlineErrorIcon;
  late double spaceRowGap;
}
