//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.11.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';

class OudsDividerTokens {
  final double borderWidth;

  OudsDividerTokens({
    required OudsProvidersTokens providersTokens,
    double? borderWidth
  }) :
    borderWidth = borderWidth ?? providersTokens.borderTokens.widthThin;
}
