//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.3.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsControlItemTokens {
  late double borderRadius;
  late double borderRadiusItemOnly;
  late Color colorBgFocus;
  late Color colorBgHover;
  late Color colorBgLoading;
  late Color colorBgPressed;
  late Color colorContentLoader;
  late double sizeErrorIcon;
  late double sizeIcon;
  late double sizeLoader;
  late double sizeMaxHeightAssetsContainer;
  late double sizeMaxWidth;
  late double sizeMinHeight;
  late double sizeMinWidth;
  late double spaceColumnGap;
  late double spacePaddingBlockDefault;
  late double spacePaddingBlockTopErrorText;
  late double spacePaddingInline;
  late double spacePaddingInlineErrorIcon;
  late double spaceRowGap;
}
