//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.3.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsButtonMonoTokens {
  late Color colorBgDefaultDisabled;
  late Color colorBgDefaultEnabled;
  late Color colorBgDefaultFocus;
  late Color colorBgDefaultHover;
  late Color colorBgDefaultLoading;
  late Color colorBgDefaultPressed;
  late Color colorBgMinimalFocus;
  late Color colorBgMinimalHover;
  late Color colorBgMinimalPressed;
  late Color colorBgStrongDisabled;
  late Color colorBgStrongEnabled;
  late Color colorBgStrongFocus;
  late Color colorBgStrongHover;
  late Color colorBgStrongLoading;
  late Color colorBgStrongPressed;
  late Color colorBorderDefaultDisabled;
  late Color colorBorderDefaultEnabled;
  late Color colorBorderDefaultFocus;
  late Color colorBorderDefaultHover;
  late Color colorBorderDefaultLoading;
  late Color colorBorderDefaultPressed;
  late Color colorContentDefaultDisabled;
  late Color colorContentDefaultEnabled;
  late Color colorContentDefaultFocus;
  late Color colorContentDefaultHover;
  late Color colorContentDefaultLoading;
  late Color colorContentDefaultPressed;
  late Color colorContentMinimalDisabled;
  late Color colorContentMinimalEnabled;
  late Color colorContentMinimalFocus;
  late Color colorContentMinimalHover;
  late Color colorContentMinimalLoading;
  late Color colorContentMinimalPressed;
  late Color colorContentStrongDisabled;
  late Color colorContentStrongEnabled;
  late Color colorContentStrongFocus;
  late Color colorContentStrongHover;
  late Color colorContentStrongLoading;
  late Color colorContentStrongPressed;
}
