//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';

class OudsSwitchTokens {
  final double borderRadiusCursor;
  final double borderRadiusTrack;
  final Color colorCheck;
  final Color colorCheckInteraction;
  final Color colorCursor;
  final Color colorTrackSelected;
  final Color colorTrackSelectedInteraction;
  final Color colorTrackUnselected;
  final Color colorTrackUnselectedInteraction;
  final double opacityCheck;
  final double sizeHeightCursorSelected;
  final double sizeHeightCursorUnselected;
  final double sizeHeightTrack;
  final double sizeMaxHeight;
  final double sizeMinHeight;
  final double sizeMinHeightInteractiveArea;
  final double sizeMinWidth;
  final double sizeWidthCursorSelected;
  final double sizeWidthCursorSelectedPressed;
  final double sizeWidthCursorUnselected;
  final double sizeWidthCursorUnselectedPressed;
  final double sizeWidthTrack;
  final double spacePaddingInlineSelected;
  final double spacePaddingInlineUnselected;

  OudsSwitchTokens({
    required OudsProvidersTokens providersTokens,
    double? borderRadiusCursor,
    double? borderRadiusTrack,
    Color? colorCheck,
    Color? colorCheckInteraction,
    Color? colorCursor,
    Color? colorTrackSelected,
    Color? colorTrackSelectedInteraction,
    Color? colorTrackUnselected,
    Color? colorTrackUnselectedInteraction,
    double? opacityCheck,
    double? sizeHeightCursorSelected,
    double? sizeHeightCursorUnselected,
    double? sizeHeightTrack,
    double? sizeMaxHeight,
    double? sizeMinHeight,
    double? sizeMinHeightInteractiveArea,
    double? sizeMinWidth,
    double? sizeWidthCursorSelected,
    double? sizeWidthCursorSelectedPressed,
    double? sizeWidthCursorUnselected,
    double? sizeWidthCursorUnselectedPressed,
    double? sizeWidthTrack,
    double? spacePaddingInlineSelected,
    double? spacePaddingInlineUnselected
  }) :
    borderRadiusCursor = borderRadiusCursor ?? providersTokens.borderTokens.radiusPill,
    borderRadiusTrack = borderRadiusTrack ?? providersTokens.borderTokens.radiusPill,
    colorCheck = colorCheck ?? providersTokens.colorScheme.contentDefault,
    colorCheckInteraction = colorCheckInteraction ?? providersTokens.colorScheme.contentDefault,
    colorCursor = colorCursor ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralMutedWhite, providersTokens.colorScheme.repositoryNeutralEmphasizedHighest),
    colorTrackSelected = colorTrackSelected ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPositiveDefault, providersTokens.colorScheme.repositoryPositiveHigh),
    colorTrackSelectedInteraction = colorTrackSelectedInteraction ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryPositiveHigh, providersTokens.colorScheme.repositoryPositiveLow),
    colorTrackUnselected = colorTrackUnselected ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackMediumHigh, providersTokens.colorScheme.repositoryOpacityWhiteHigh),
    colorTrackUnselectedInteraction = colorTrackUnselectedInteraction ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackHigh, providersTokens.colorScheme.repositoryOpacityWhiteHigher),
    opacityCheck = opacityCheck ?? providersTokens.opacityTokens.opaque,
    sizeHeightCursorSelected = sizeHeightCursorSelected ?? DimensionRawTokens.dimension300,
    sizeHeightCursorUnselected = sizeHeightCursorUnselected ?? DimensionRawTokens.dimension200,
    sizeHeightTrack = sizeHeightTrack ?? DimensionRawTokens.dimension400,
    sizeMaxHeight = sizeMaxHeight ?? DimensionRawTokens.dimension400,
    sizeMinHeight = sizeMinHeight ?? DimensionRawTokens.dimension400,
    sizeMinHeightInteractiveArea = sizeMinHeightInteractiveArea ?? providersTokens.sizeTokens.minInteractiveArea,
    sizeMinWidth = sizeMinWidth ?? DimensionRawTokens.dimension700,
    sizeWidthCursorSelected = sizeWidthCursorSelected ?? DimensionRawTokens.dimension300,
    sizeWidthCursorSelectedPressed = sizeWidthCursorSelectedPressed ?? DimensionRawTokens.dimension400,
    sizeWidthCursorUnselected = sizeWidthCursorUnselected ?? DimensionRawTokens.dimension200,
    sizeWidthCursorUnselectedPressed = sizeWidthCursorUnselectedPressed ?? DimensionRawTokens.dimension300,
    sizeWidthTrack = sizeWidthTrack ?? DimensionRawTokens.dimension700,
    spacePaddingInlineSelected = spacePaddingInlineSelected ?? providersTokens.spaceTokens.paddingInline3xs,
    spacePaddingInlineUnselected = spacePaddingInlineUnselected ?? providersTokens.spaceTokens.paddingInlineXs;
}
