//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 1.3.0
// Generated by Tokenator

abstract class OudsCheckboxTokens {
  late double borderRadius;
  late double borderWidthSelected;
  late double borderWidthSelectedFocus;
  late double borderWidthSelectedHover;
  late double borderWidthSelectedPressed;
  late double borderWidthUnselected;
  late double borderWidthUnselectedFocus;
  late double borderWidthUnselectedHover;
  late double borderWidthUnselectedPressed;
  late double sizeIndicator;
  late double sizeMaxHeight;
  late double sizeMinHeight;
  late double sizeMinWidth;
}
