//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';

class OudsLinkMonoTokens {
  final Color? colorContentDisabled;
  final Color? colorContentEnabled;
  final Color? colorContentFocus;
  final Color? colorContentHover;
  final Color? colorContentPressed;

  OudsLinkMonoTokens({
    required OudsProvidersTokens providersTokens,
    Color? colorContentDisabled,
    Color? colorContentEnabled,
    Color? colorContentFocus,
    Color? colorContentHover,
    Color? colorContentPressed
  }) :
    colorContentDisabled = colorContentDisabled ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackMedium, providersTokens.colorScheme.repositoryOpacityWhiteMedium),
    colorContentEnabled = colorContentEnabled ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralEmphasizedBlack, providersTokens.colorScheme.repositoryNeutralMutedWhite),
    colorContentFocus = colorContentFocus ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralEmphasizedBlack, providersTokens.colorScheme.repositoryNeutralMutedWhite),
    colorContentHover = colorContentHover ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralEmphasizedBlack, providersTokens.colorScheme.repositoryNeutralMutedWhite),
    colorContentPressed = colorContentPressed ?? providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryOpacityBlackHigh, providersTokens.colorScheme.repositoryOpacityWhiteHigher);
}
