//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.3.0
// Generated by Tokenator

abstract class OudsAlertTokens {
  late double borderRadiusDefault;
  late double borderRadiusRounded;
  late double borderWidth;
  late double sizeIcon;
  late double sizeMinHeight;
  late double sizeMinHeightBottomActionPlacement;
  late double sizeMinWidth;
  late double spaceColumnGap;
  late double spaceColumnGapAction;
  late double spacePaddingBlock;
  late double spacePaddingInline;
  late double spaceRowGap;
  late double spaceRowGapAction;
  late double spaceRowGapBullet;
}
