//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange brand tokens version 2.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';

abstract class OudsInputTagTokens {
  late double borderWidthDefault;
  late double borderWidthDefaultInteraction;
  late Color colorBgEnabled;
  late Color colorBgFocus;
  late Color colorBgHover;
  late Color colorBgPressed;
  late Color colorBorderEnabled;
  late Color colorBorderFocus;
  late Color colorBorderHover;
  late Color colorBorderPressed;
  late Color colorContentEnabled;
  late Color colorContentFocus;
  late Color colorContentHover;
  late Color colorContentPressed;
}
