//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';

class OudsSkeletonTokens {
  final Color colorBg;
  final Color colorGradientStartEnd;
  final Color colorGradientMiddle;

  OudsSkeletonTokens({
    required OudsProvidersTokens providersTokens,
    Color? colorBg,
    Color? colorGradientStartEnd,
    Color? colorGradientMiddle
  }) :
    colorBg = colorBg ?? providersTokens.colorScheme.opacityLowest,
    colorGradientStartEnd = colorGradientStartEnd ?? providersTokens.colorScheme.opacityTransparent,
    colorGradientMiddle = colorGradientMiddle ?? providersTokens.colorScheme.opacityLower;
}
