name: ouds_theme_orange_compact
description: 'Orange Compact theme implementation for OUDS, with branding-specific design tokens optimized for compact displays.'
version: 1.3.0

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ouds_core: ^1.3.0
  ouds_theme_contract: ^1.3.0
  ouds_global_raw_tokens: ^1.3.0
  ouds_theme_orange: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Thin.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono.ttf

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/component/alert/
    - assets/component/badge-icon/
    - assets/component/checkbox/
    - assets/component/chip/
    - assets/component/bullet-list/
    - assets/component/button/
    - assets/component/link/
    - assets/component/radio-button/
    - assets/component/switch/
    - assets/component/tag/
    - assets/communication/accessibility/
    - assets/communication/security-and-safety/
    - assets/functional/social-and-engagement/
    - assets/functional/settings-and-tools/
    - assets/functional/navigation/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

