//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Generated by Tokenator

class OudsTokensVersion {
    static const oudsCore = '1.9.0';
    static const androidCore = '1.0.0';
    static const androidSystem = '1.2.0';
    static const orangeCore = '1.2.0';
    static const orangeBrand = '2.2.0';
    static const soshCore = '1.2.0';
    static const soshBrand = '2.2.0';
    static const wireframeCore = '1.3.0';
    static const wireframeBrand = '2.2.0';
}
