import 'package:flutter/cupertino.dart';
import 'package:ouds_flutter_demo/l10n/app_localizations.dart';
import 'package:ouds_flutter_demo/ui/tokens/color/color_screen.dart';
import 'package:ouds_theme_contract/ouds_theme_contract.dart';

class ColorTokensModel {
  final Map<String, List<ColorTokenItem>> _groups;

  ColorTokensModel(this._groups);

  List<ColorTokenItem> operator [](String key) => _groups[key] ?? [];

  Map<String, List<ColorTokenItem>> get all => _groups;

  factory ColorTokensModel.fromTheme(BuildContext context, OudsThemeContract theme) {
    return ColorTokensModel({
      context.l10n.app_tokens_color_action_label: [
        ColorTokenItem(name: 'actionDisabled', value: theme.colorsScheme(context).actionDisabled),
        ColorTokenItem(name: 'actionEnabled', value: theme.colorsScheme(context).actionEnabled),
        ColorTokenItem(name: 'actionFocus', value: theme.colorsScheme(context).actionFocus),
        ColorTokenItem(name: 'actionHighlighted', value: theme.colorsScheme(context).actionHighlighted),
        ColorTokenItem(name: 'actionHover', value: theme.colorsScheme(context).actionHover),
        ColorTokenItem(name: 'actionLoading', value: theme.colorsScheme(context).actionLoading),
        ColorTokenItem(name: 'actionNegativeEnabled', value: theme.colorsScheme(context).actionNegativeEnabled),
        ColorTokenItem(name: 'actionNegativeFocus', value: theme.colorsScheme(context).actionNegativeFocus),
        ColorTokenItem(name: 'actionNegativeHover', value: theme.colorsScheme(context).actionNegativeHover),
        ColorTokenItem(name: 'actionNegativeLoading', value: theme.colorsScheme(context).actionNegativeLoading),
        ColorTokenItem(name: 'actionNegativePressed', value: theme.colorsScheme(context).actionNegativePressed),
        ColorTokenItem(name: 'actionPressed', value: theme.colorsScheme(context).actionPressed),
        ColorTokenItem(name: 'actionSelected', value: theme.colorsScheme(context).actionSelected),
        ColorTokenItem(name: 'actionSupportEnabled', value: theme.colorsScheme(context).actionSupportEnabled),
        ColorTokenItem(name: 'actionSupportFocus', value: theme.colorsScheme(context).actionSupportFocus),
        ColorTokenItem(name: 'actionSupportHover', value: theme.colorsScheme(context).actionSupportHover),
        ColorTokenItem(name: 'actionSupportLoading', value: theme.colorsScheme(context).actionSupportLoading),
        ColorTokenItem(name: 'actionSupportPressed', value: theme.colorsScheme(context).actionSupportPressed),
        ColorTokenItem(name: 'actionVisited', value: theme.colorsScheme(context).actionVisited),
      ],
      context.l10n.app_tokens_color_always_label: [
        ColorTokenItem(name: 'alwaysBlack', value: theme.colorsScheme(context).alwaysBlack),
        ColorTokenItem(name: 'alwaysOnBlack', value: theme.colorsScheme(context).alwaysOnBlack),
        ColorTokenItem(name: 'alwaysOnWhite', value: theme.colorsScheme(context).alwaysOnWhite),
        ColorTokenItem(name: 'alwaysWhite', value: theme.colorsScheme(context).alwaysWhite),
      ],
      context.l10n.app_tokens_color_background_label: [
        ColorTokenItem(name: 'bgEmphasized', value: theme.colorsScheme(context).bgEmphasized),
        ColorTokenItem(name: 'bgPrimary', value: theme.colorsScheme(context).bgPrimary),
        ColorTokenItem(name: 'bgSecondary', value: theme.colorsScheme(context).bgSecondary),
        ColorTokenItem(name: 'bgTertiary', value: theme.colorsScheme(context).bgTertiary),
      ],
      context.l10n.app_tokens_color_border_label: [
        ColorTokenItem(name: 'borderBrandPrimary', value: theme.colorsScheme(context).borderBrandPrimary),
        ColorTokenItem(name: 'borderDefault', value: theme.colorsScheme(context).borderDefault),
        ColorTokenItem(name: 'borderEmphasized', value: theme.colorsScheme(context).borderEmphasized),
        ColorTokenItem(name: 'borderFocus', value: theme.colorsScheme(context).borderFocus),
        ColorTokenItem(name: 'borderFocusInset', value: theme.colorsScheme(context).borderFocusInset),
        ColorTokenItem(name: 'borderMuted', value: theme.colorsScheme(context).borderMuted),
        ColorTokenItem(name: 'borderOnBrandPrimary', value: theme.colorsScheme(context).borderOnBrandPrimary),
      ],
      context.l10n.app_tokens_color_content_label: [
        ColorTokenItem(name: 'contentBrandPrimary', value: theme.colorsScheme(context).contentBrandPrimary),
        ColorTokenItem(name: 'contentDefault', value: theme.colorsScheme(context).contentDefault),
        ColorTokenItem(name: 'contentDisabled', value: theme.colorsScheme(context).contentDisabled),
        ColorTokenItem(name: 'contentMuted', value: theme.colorsScheme(context).contentMuted),
        ColorTokenItem(name: 'contentOnActionDisabled', value: theme.colorsScheme(context).contentOnActionDisabled),
        ColorTokenItem(name: 'contentOnActionEnabled', value: theme.colorsScheme(context).contentOnActionEnabled),
        ColorTokenItem(name: 'contentOnActionFocus', value: theme.colorsScheme(context).contentOnActionFocus),
        ColorTokenItem(name: 'contentOnActionHighlighted', value: theme.colorsScheme(context).contentOnActionHighlighted),
        ColorTokenItem(name: 'contentOnActionHover', value: theme.colorsScheme(context).contentOnActionHover),
        ColorTokenItem(name: 'contentOnActionLoading', value: theme.colorsScheme(context).contentOnActionLoading),
        ColorTokenItem(name: 'contentOnActionPressed', value: theme.colorsScheme(context).contentOnActionPressed),
        ColorTokenItem(name: 'contentOnBrandPrimary', value: theme.colorsScheme(context).contentOnBrandPrimary),
        ColorTokenItem(name: 'contentOnOverlayEmphasized', value: theme.colorsScheme(context).contentOnOverlayEmphasized),
        ColorTokenItem(name: 'contentOnStatusEmphasized', value: theme.colorsScheme(context).contentOnStatusEmphasized),
        ColorTokenItem(name: 'contentOnStatusEmphasizedAlt', value: theme.colorsScheme(context).contentOnStatusEmphasizedAlt),
        ColorTokenItem(name: 'contentOnStatusMuted', value: theme.colorsScheme(context).contentOnStatusMuted),
        ColorTokenItem(name: 'contentStatusInfo', value: theme.colorsScheme(context).contentStatusInfo),
        ColorTokenItem(name: 'contentStatusNegative', value: theme.colorsScheme(context).contentStatusNegative),
        ColorTokenItem(name: 'contentStatusPositive', value: theme.colorsScheme(context).contentStatusPositive),
        ColorTokenItem(name: 'contentStatusWarning', value: theme.colorsScheme(context).contentStatusWarning),
      ],
      context.l10n.app_tokens_color_decorative_label: [
        ColorTokenItem(name: 'decorativeAccent1Default', value: theme.colorsScheme(context).decorativeAccent1Default),
        ColorTokenItem(name: 'decorativeAccent1Emphasized', value: theme.colorsScheme(context).decorativeAccent1Emphasized),
        ColorTokenItem(name: 'decorativeAccent1Muted', value: theme.colorsScheme(context).decorativeAccent1Muted),
        ColorTokenItem(name: 'decorativeAccent2Default', value: theme.colorsScheme(context).decorativeAccent2Default),
        ColorTokenItem(name: 'decorativeAccent2Emphasized', value: theme.colorsScheme(context).decorativeAccent2Emphasized),
        ColorTokenItem(name: 'decorativeAccent2Muted', value: theme.colorsScheme(context).decorativeAccent2Muted),
        ColorTokenItem(name: 'decorativeAccent3Default', value: theme.colorsScheme(context).decorativeAccent3Default),
        ColorTokenItem(name: 'decorativeAccent3Emphasized', value: theme.colorsScheme(context).decorativeAccent3Emphasized),
        ColorTokenItem(name: 'decorativeAccent3Muted', value: theme.colorsScheme(context).decorativeAccent3Muted),
        ColorTokenItem(name: 'decorativeAccent4Default', value: theme.colorsScheme(context).decorativeAccent4Default),
        ColorTokenItem(name: 'decorativeAccent4Emphasized', value: theme.colorsScheme(context).decorativeAccent4Emphasized),
        ColorTokenItem(name: 'decorativeAccent4Muted', value: theme.colorsScheme(context).decorativeAccent4Muted),
        ColorTokenItem(name: 'decorativeAccent5Default', value: theme.colorsScheme(context).decorativeAccent5Default),
        ColorTokenItem(name: 'decorativeAccent5Emphasized', value: theme.colorsScheme(context).decorativeAccent5Emphasized),
        ColorTokenItem(name: 'decorativeAccent5Muted', value: theme.colorsScheme(context).decorativeAccent5Muted),
        ColorTokenItem(name: 'decorativeBrandPrimary', value: theme.colorsScheme(context).decorativeBrandPrimary),
        ColorTokenItem(name: 'decorativeBrandSecondary', value: theme.colorsScheme(context).decorativeBrandSecondary),
        ColorTokenItem(name: 'decorativeBrandTertiary', value: theme.colorsScheme(context).decorativeBrandTertiary),
        ColorTokenItem(name: 'colorDecorativeNeutralEmphasizedHigher', value: theme.colorsScheme(context).colorDecorativeNeutralEmphasizedHigher),
        ColorTokenItem(name: 'colorDecorativeNeutralEmphasizedLow', value: theme.colorsScheme(context).colorDecorativeNeutralEmphasizedLow),
        ColorTokenItem(name: 'colorDecorativeNeutralEmphasizedLower', value: theme.colorsScheme(context).colorDecorativeNeutralEmphasizedLower),
        ColorTokenItem(name: 'colorDecorativeNeutralEmphasizedLowest', value: theme.colorsScheme(context).colorDecorativeNeutralEmphasizedLowest),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedHigh', value: theme.colorsScheme(context).colorDecorativeNeutralMutedHigh),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedHigher', value: theme.colorsScheme(context).colorDecorativeNeutralMutedHigher),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedHighest', value: theme.colorsScheme(context).colorDecorativeNeutralMutedHighest),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedLow', value: theme.colorsScheme(context).colorDecorativeNeutralMutedLow),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedLower', value: theme.colorsScheme(context).colorDecorativeNeutralMutedLower),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedLowest', value: theme.colorsScheme(context).colorDecorativeNeutralMutedLowest),
        ColorTokenItem(name: 'colorDecorativeNeutralMutedMedium', value: theme.colorsScheme(context).colorDecorativeNeutralMutedMedium),
        ColorTokenItem(name: 'decorativeSkinTint100', value: theme.colorsScheme(context).decorativeSkinTint100),
        ColorTokenItem(name: 'decorativeSkinTint200', value: theme.colorsScheme(context).decorativeSkinTint200),
        ColorTokenItem(name: 'decorativeSkinTint300', value: theme.colorsScheme(context).decorativeSkinTint300),
        ColorTokenItem(name: 'decorativeSkinTint400', value: theme.colorsScheme(context).decorativeSkinTint400),
        ColorTokenItem(name: 'decorativeSkinTint500', value: theme.colorsScheme(context).decorativeSkinTint500),
        ColorTokenItem(name: 'decorativeSkinTint600', value: theme.colorsScheme(context).decorativeSkinTint600),
        ColorTokenItem(name: 'decorativeSkinTint700', value: theme.colorsScheme(context).decorativeSkinTint700),
        ColorTokenItem(name: 'decorativeSkinTint800', value: theme.colorsScheme(context).decorativeSkinTint800),
        ColorTokenItem(name: 'decorativeSkinTint900', value: theme.colorsScheme(context).decorativeSkinTint900),
      ],
      context.l10n.app_tokens_color_overlay_label: [
        ColorTokenItem(name: 'overlayDefault', value: theme.colorsScheme(context).overlayDefault),
        ColorTokenItem(name: 'overlayDrag', value: theme.colorsScheme(context).overlayDrag),
        ColorTokenItem(name: 'overlayEmphasized', value: theme.colorsScheme(context).overlayEmphasized),
        ColorTokenItem(name: 'overlayModal', value: theme.colorsScheme(context).overlayModal),
      ],
      context.l10n.app_tokens_color_surface_label: [
        ColorTokenItem(name: 'surfaceBrandPrimary', value: theme.colorsScheme(context).surfaceBrandPrimary),
        ColorTokenItem(name: 'surfaceStatusAccentEmphasized', value: theme.colorsScheme(context).surfaceStatusAccentEmphasized),
        ColorTokenItem(name: 'surfaceStatusAccentMuted', value: theme.colorsScheme(context).surfaceStatusAccentMuted),
        ColorTokenItem(name: 'surfaceStatusInfoEmphasized', value: theme.colorsScheme(context).surfaceStatusInfoEmphasized),
        ColorTokenItem(name: 'surfaceStatusInfoMuted', value: theme.colorsScheme(context).surfaceStatusInfoMuted),
        ColorTokenItem(name: 'surfaceStatusNegativeEmphasized', value: theme.colorsScheme(context).surfaceStatusNegativeEmphasized),
        ColorTokenItem(name: 'surfaceStatusNegativeMuted', value: theme.colorsScheme(context).surfaceStatusNegativeMuted),
        ColorTokenItem(name: 'surfaceStatusNeutralEmphasized', value: theme.colorsScheme(context).surfaceStatusNeutralEmphasized),
        ColorTokenItem(name: 'surfaceStatusNeutralMuted', value: theme.colorsScheme(context).surfaceStatusNeutralMuted),
        ColorTokenItem(name: 'surfaceStatusPositiveEmphasized', value: theme.colorsScheme(context).surfaceStatusPositiveEmphasized),
        ColorTokenItem(name: 'surfaceStatusPositiveMuted', value: theme.colorsScheme(context).surfaceStatusPositiveMuted),
        ColorTokenItem(name: 'surfaceStatusWarningEmphasized', value: theme.colorsScheme(context).surfaceStatusWarningEmphasized),
        ColorTokenItem(name: 'surfaceStatusWarningMuted', value: theme.colorsScheme(context).surfaceStatusWarningMuted),
      ],
    });
  }
}
