//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_theme_contract/theme/tokens/material/ouds_material_color_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshMaterialColorTokens extends OudsMaterialColorTokens {
  const SoshMaterialColorTokens({
    super.backgroundDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.backgroundLight = ColorRawTokens.colorFunctionalWhite,
    super.errorContainerDark = ColorRawTokens.colorFunctionalScarlet900,
    super.errorContainerLight = ColorRawTokens.colorFunctionalScarlet100,
    super.errorDark = ColorRawTokens.colorFunctionalScarlet300,
    super.errorLight = ColorRawTokens.colorFunctionalScarlet600,
    super.inverseOnSurfaceDark = ColorRawTokens.colorFunctionalBlack,
    super.inverseOnSurfaceLight = ColorRawTokens.colorFunctionalWhite,
    super.inversePrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.inversePrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.inverseSurfaceDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.inverseSurfaceLight = ColorRawTokens.colorFunctionalGrayDark720,
    super.onBackgroundDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onBackgroundLight = ColorRawTokens.colorFunctionalBlack,
    super.onErrorContainerDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onErrorContainerLight = ColorRawTokens.colorFunctionalBlack,
    super.onErrorDark = ColorRawTokens.colorFunctionalBlack,
    super.onErrorLight = ColorRawTokens.colorFunctionalWhite,
    super.onPrimaryContainerDark = ColorRawTokens.colorFunctionalBlack,
    super.onPrimaryContainerLight = ColorRawTokens.colorFunctionalWhite,
    super.onPrimaryDark = ColorRawTokens.colorFunctionalBlack,
    super.onPrimaryFixedDark = ColorRawTokens.colorFunctionalWhite,
    super.onPrimaryFixedLight = ColorRawTokens.colorFunctionalWhite,
    super.onPrimaryFixedVariantDark = ColorRawTokens.colorOpacityWhite640,
    super.onPrimaryFixedVariantLight = ColorRawTokens.colorOpacityWhite640,
    super.onPrimaryLight = ColorRawTokens.colorFunctionalGrayLight160,
    super.onSecondaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onSecondaryContainerLight = ColorRawTokens.colorFunctionalBlack,
    super.onSecondaryDark = ColorRawTokens.colorFunctionalBlack,
    super.onSecondaryFixedDark = ColorRawTokens.colorFunctionalWhite,
    super.onSecondaryFixedLight = ColorRawTokens.colorFunctionalWhite,
    super.onSecondaryFixedVariantDark = ColorRawTokens.colorOpacityWhite640,
    super.onSecondaryFixedVariantLight = ColorRawTokens.colorOpacityWhite640,
    super.onSecondaryLight = ColorRawTokens.colorFunctionalGrayLight160,
    super.onSurfaceDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onSurfaceLight = ColorRawTokens.colorFunctionalBlack,
    super.onSurfaceVariantDark = ColorRawTokens.colorOpacityWhite640,
    super.onSurfaceVariantLight = ColorRawTokens.colorOpacityBlack680,
    super.onTertiaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onTertiaryContainerLight = ColorRawTokens.colorFunctionalBlack,
    super.onTertiaryDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.onTertiaryFixedDark = ColorRawTokens.colorFunctionalBlack,
    super.onTertiaryFixedLight = ColorRawTokens.colorFunctionalBlack,
    super.onTertiaryFixedVariantDark = ColorRawTokens.colorOpacityBlack680,
    super.onTertiaryFixedVariantLight = ColorRawTokens.colorOpacityBlack680,
    super.onTertiaryLight = ColorRawTokens.colorFunctionalBlack,
    super.outlineDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.outlineLight = ColorRawTokens.colorFunctionalBlack,
    super.outlineVariantDark = ColorRawTokens.colorOpacityWhite200,
    super.outlineVariantLight = ColorRawTokens.colorOpacityBlack200,
    super.primaryContainerDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.primaryContainerLight = ColorRawTokens.colorFunctionalBlack,
    super.primaryDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.primaryFixedDark = ColorRawTokens.colorFunctionalBlack,
    super.primaryFixedDimDark = ColorRawTokens.colorFunctionalBlack,
    super.primaryFixedDimLight = ColorRawTokens.colorFunctionalBlack,
    super.primaryFixedLight = ColorRawTokens.colorFunctionalBlack,
    super.primaryLight = ColorRawTokens.colorFunctionalBlack,
    super.scrimDark = ColorRawTokens.colorFunctionalBlack,
    super.scrimLight = ColorRawTokens.colorFunctionalBlack,
    super.secondaryContainerDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.secondaryContainerLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.secondaryDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.secondaryFixedDark = ColorRawTokens.colorFunctionalBlack,
    super.secondaryFixedDimDark = ColorRawTokens.colorFunctionalBlack,
    super.secondaryFixedDimLight = ColorRawTokens.colorFunctionalBlack,
    super.secondaryFixedLight = ColorRawTokens.colorFunctionalBlack,
    super.secondaryLight = ColorRawTokens.colorFunctionalBlack,
    super.surfaceBrightDark = ColorRawTokens.colorFunctionalGrayDark640,
    super.surfaceBrightLight = ColorRawTokens.colorFunctionalWhite,
    super.surfaceDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.surfaceDimDark = ColorRawTokens.colorFunctionalBlack,
    super.surfaceDimLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfaceLight = ColorRawTokens.colorFunctionalWhite,
    super.surfaceTintDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfaceTintLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfaceVariantDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfaceVariantLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfContainerDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfContainerHighDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfContainerHighestDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfContainerHighestLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfContainerHighLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfContainerLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.surfContainerLowDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfContainerLowestDark = ColorRawTokens.colorFunctionalGrayDark720,
    super.surfContainerLowestLight = ColorRawTokens.colorFunctionalWhite,
    super.surfContainerLowLight = ColorRawTokens.colorFunctionalWhite,
    super.tertiaryContainerDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.tertiaryContainerLight = ColorRawTokens.colorFunctionalWhite,
    super.tertiaryDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.tertiaryFixedDark = ColorRawTokens.colorFunctionalWhite,
    super.tertiaryFixedDimDark = ColorRawTokens.colorFunctionalGrayLight80,
    super.tertiaryFixedDimLight = ColorRawTokens.colorFunctionalGrayLight80,
    super.tertiaryFixedLight = ColorRawTokens.colorFunctionalWhite,
    super.tertiaryLight = ColorRawTokens.colorFunctionalWhite,
  });
}
