name: ouds_theme_white_label
description: 'Customizable white-label theme for OUDS, enabling branding adjustments with design tokens.'
version: 0.3.0

environment:
  sdk: ^3.6.0
  flutter: '>=1.17.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ouds_core: ^0.3.0
  ouds_global_raw_tokens: ^0.3.0
  ouds_theme_contract: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/oswald.ttf

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono.ttf

# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
