//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Tokens version 0.5.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_decorative_semantic_tokens.dart';
import 'package:ouds_theme_white_label/raw/white_label_color_raw_tokens.dart';

class WhiteLabelColorDecorativeSemanticTokens extends OudsColorDecorativeSemanticTokens {
  const WhiteLabelColorDecorativeSemanticTokens({
    super.decorativeAccent1DefaultLight = ColorRawTokens.colorDecorativeEmerald500,
    super.decorativeAccent1EmphasizedLight = ColorRawTokens.colorDecorativeEmerald700,
    super.decorativeAccent1MutedLight = ColorRawTokens.colorDecorativeEmerald200,
    super.decorativeAccent1DefaultDark = ColorRawTokens.colorDecorativeEmerald500,
    super.decorativeAccent1EmphasizedDark = ColorRawTokens.colorDecorativeEmerald700,
    super.decorativeAccent1MutedDark = ColorRawTokens.colorDecorativeEmerald200,
    super.decorativeAccent2DefaultLight = ColorRawTokens.colorDecorativeSky400,
    super.decorativeAccent2EmphasizedLight = ColorRawTokens.colorDecorativeSky700,
    super.decorativeAccent2MutedLight = ColorRawTokens.colorDecorativeSky200,
    super.decorativeAccent2DefaultDark = ColorRawTokens.colorDecorativeSky400,
    super.decorativeAccent2EmphasizedDark = ColorRawTokens.colorDecorativeSky700,
    super.decorativeAccent2MutedDark = ColorRawTokens.colorDecorativeSky200,
    super.decorativeAccent3DefaultLight = ColorRawTokens.colorFunctionalSun500,
    super.decorativeAccent3EmphasizedLight = ColorRawTokens.colorDecorativeAmber500,
    super.decorativeAccent3MutedLight = ColorRawTokens.colorFunctionalSun200,
    super.decorativeAccent3DefaultDark = ColorRawTokens.colorFunctionalSun500,
    super.decorativeAccent3EmphasizedDark = ColorRawTokens.colorDecorativeAmber500,
    super.decorativeAccent3MutedDark = ColorRawTokens.colorFunctionalSun200,
    super.decorativeAccent4DefaultLight = ColorRawTokens.colorDecorativeAmethyst400,
    super.decorativeAccent4EmphasizedLight = ColorRawTokens.colorDecorativeAmethyst800,
    super.decorativeAccent4MutedLight = ColorRawTokens.colorDecorativeAmethyst200,
    super.decorativeAccent4DefaultDark = ColorRawTokens.colorDecorativeAmethyst400,
    super.decorativeAccent4EmphasizedDark = ColorRawTokens.colorDecorativeAmethyst800,
    super.decorativeAccent4MutedDark = ColorRawTokens.colorDecorativeAmethyst200,
    super.decorativeAccent5DefaultLight = ColorRawTokens.colorDecorativeShockingPink200,
    super.decorativeAccent5EmphasizedLight = ColorRawTokens.colorDecorativeShockingPink300,
    super.decorativeAccent5MutedLight = ColorRawTokens.colorDecorativeShockingPink100,
    super.decorativeAccent5DefaultDark = ColorRawTokens.colorDecorativeShockingPink200,
    super.decorativeAccent5EmphasizedDark = ColorRawTokens.colorDecorativeShockingPink300,
    super.decorativeAccent5MutedDark = ColorRawTokens.colorDecorativeShockingPink100,
    super.decorativeBrandPrimaryLight = WhiteLabelColorRawTokens.colorBlue500,
    super.decorativeBrandSecondaryLight = ColorRawTokens.colorFunctionalBlack,
    super.decorativeBrandTertiaryLight = ColorRawTokens.colorFunctionalWhite,
    super.decorativeBrandPrimaryDark = WhiteLabelColorRawTokens.colorBlue500,
    super.decorativeBrandSecondaryDark = ColorRawTokens.colorFunctionalBlack,
    super.decorativeBrandTertiaryDark = ColorRawTokens.colorFunctionalWhite,
    super.decorativeNeutralEmphasizedHigherLight = ColorRawTokens.colorFunctionalDarkGray640,
    super.decorativeNeutralEmphasizedLowLight = ColorRawTokens.colorFunctionalDarkGray400,
    super.decorativeNeutralEmphasizedLowerLight = ColorRawTokens.colorFunctionalDarkGray320,
    super.decorativeNeutralEmphasizedLowestLight = ColorRawTokens.colorFunctionalDarkGray240,
    super.decorativeNeutralEmphasizedHigherDark = ColorRawTokens.colorFunctionalDarkGray640,
    super.decorativeNeutralEmphasizedLowDark = ColorRawTokens.colorFunctionalDarkGray400,
    super.decorativeNeutralEmphasizedLowerDark = ColorRawTokens.colorFunctionalDarkGray320,
    super.decorativeNeutralEmphasizedLowestDark = ColorRawTokens.colorFunctionalDarkGray240,
    super.decorativeNeutralMutedHighLight = ColorRawTokens.colorFunctionalLightGray400,
    super.decorativeNeutralMutedHigherLight = ColorRawTokens.colorFunctionalLightGray800,
    super.decorativeNeutralMutedHighestLight = ColorRawTokens.colorFunctionalLightGray960,
    super.decorativeNeutralMutedLowLight = ColorRawTokens.colorFunctionalLightGray240,
    super.decorativeNeutralMutedLowerLight = ColorRawTokens.colorFunctionalLightGray160,
    super.decorativeNeutralMutedLowestLight = ColorRawTokens.colorFunctionalLightGray80,
    super.decorativeNeutralMutedMediumLight = ColorRawTokens.colorFunctionalLightGray320,
    super.decorativeNeutralMutedHighDark = ColorRawTokens.colorFunctionalLightGray400,
    super.decorativeNeutralMutedHigherDark = ColorRawTokens.colorFunctionalLightGray800,
    super.decorativeNeutralMutedHighestDark = ColorRawTokens.colorFunctionalLightGray960,
    super.decorativeNeutralMutedLowDark = ColorRawTokens.colorFunctionalLightGray240,
    super.decorativeNeutralMutedLowerDark = ColorRawTokens.colorFunctionalLightGray160,
    super.decorativeNeutralMutedLowestDark = ColorRawTokens.colorFunctionalLightGray80,
    super.decorativeNeutralMutedMediumDark = ColorRawTokens.colorFunctionalLightGray320,
    super.decorativeSkinTint100Light = ColorRawTokens.colorDecorativeDeepPeach100,
    super.decorativeSkinTint200Light = ColorRawTokens.colorDecorativeDeepPeach200,
    super.decorativeSkinTint300Light = ColorRawTokens.colorDecorativeDeepPeach300,
    super.decorativeSkinTint400Light = ColorRawTokens.colorDecorativeDeepPeach400,
    super.decorativeSkinTint500Light = ColorRawTokens.colorDecorativeDeepPeach500,
    super.decorativeSkinTint600Light = ColorRawTokens.colorDecorativeDeepPeach600,
    super.decorativeSkinTint700Light = ColorRawTokens.colorDecorativeDeepPeach700,
    super.decorativeSkinTint800Light = ColorRawTokens.colorDecorativeDeepPeach800,
    super.decorativeSkinTint900Light = ColorRawTokens.colorDecorativeDeepPeach900,
    super.decorativeSkinTint100Dark = ColorRawTokens.colorDecorativeDeepPeach100,
    super.decorativeSkinTint200Dark = ColorRawTokens.colorDecorativeDeepPeach200,
    super.decorativeSkinTint300Dark = ColorRawTokens.colorDecorativeDeepPeach300,
    super.decorativeSkinTint400Dark = ColorRawTokens.colorDecorativeDeepPeach400,
    super.decorativeSkinTint500Dark = ColorRawTokens.colorDecorativeDeepPeach500,
    super.decorativeSkinTint600Dark = ColorRawTokens.colorDecorativeDeepPeach600,
    super.decorativeSkinTint700Dark = ColorRawTokens.colorDecorativeDeepPeach700,
    super.decorativeSkinTint800Dark = ColorRawTokens.colorDecorativeDeepPeach800,
    super.decorativeSkinTint900Dark = ColorRawTokens.colorDecorativeDeepPeach900,
  });
}
