//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Generate manually using Orange tokens. This package will be soon removed and replaced by Sosh.

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_decorative_semantic_tokens.dart';
import 'package:ouds_theme_white_label/raw/white_label_color_raw_tokens.dart';

class WhiteLabelColorDecorativeSemanticTokens extends OudsColorDecorativeSemanticTokens {
  const WhiteLabelColorDecorativeSemanticTokens({
    super.decorativeEmerald100 = const Color(0xffe5f5ed),
    super.decorativeEmerald200 = const Color(0xffc0e8d4),
    super.decorativeEmerald300 = const Color(0xff9bdaba),
    super.decorativeEmerald400 = const Color(0xff75cca1),
    super.decorativeEmerald500 = const Color(0xff50be87),
    super.decorativeEmerald600 = const Color(0xff3ba06e),
    super.decorativeEmerald700 = const Color(0xff2e7b54),
    super.decorativeEmerald800 = const Color(0xff20563b),
    super.decorativeEmerald900 = const Color(0xff123021),
    super.decorativeSky100 = const Color(0xffd2ecf9),
    super.decorativeSky200 = const Color(0xffa5daf3),
    super.decorativeSky300 = const Color(0xff79c7ec),
    super.decorativeSky400 = const Color(0xff4ab4e6),
    super.decorativeSky500 = const Color(0xff1fa2e0),
    super.decorativeSky600 = const Color(0xff1982b3),
    super.decorativeSky700 = const Color(0xff136186),
    super.decorativeSky800 = const Color(0xff0c415a),
    super.decorativeSky900 = const Color(0xff06202d),
    super.decorativeAmber100 = const Color(0xfffff0cc),
    super.decorativeAmber200 = const Color(0xffffe199),
    super.decorativeAmber300 = const Color(0xffffd266),
    super.decorativeAmber400 = const Color(0xffffc333),
    super.decorativeAmber500 = const Color(0xffffb400),
    super.decorativeAmber600 = const Color(0xffcc9000),
    super.decorativeAmber700 = const Color(0xff996c00),
    super.decorativeAmber800 = const Color(0xff664800),
    super.decorativeAmber900 = const Color(0xff332400),
    super.decorativeAmethyst100 = const Color(0xfff1ecf9),
    super.decorativeAmethyst200 = const Color(0xffe0d4f2),
    super.decorativeAmethyst300 = const Color(0xffc5ade6),
    super.decorativeAmethyst400 = const Color(0xffa885d8),
    super.decorativeAmethyst500 = const Color(0xff8d60cd),
    super.decorativeAmethyst600 = const Color(0xff5b2f98),
    super.decorativeAmethyst700 = const Color(0xff432371),
    super.decorativeAmethyst800 = const Color(0xff2c174a),
    super.decorativeAmethyst900 = const Color(0xff150b23),
    super.decorativeShockingPink100 = const Color(0xffffe5f6),
    super.decorativeShockingPink200 = const Color(0xffffb4e6),
    super.decorativeShockingPink300 = const Color(0xffff80d4),
    super.decorativeShockingPink400 = const Color(0xffff4dc3),
    super.decorativeShockingPink500 = const Color(0xffff1ab2),
    super.decorativeShockingPink600 = const Color(0xffe50099),
    super.decorativeShockingPink700 = const Color(0xffb20077),
    super.decorativeShockingPink800 = const Color(0xff800055),
    super.decorativeShockingPink900 = const Color(0xff4d0033),
    super.decorativeDeepPeach100 = const Color(0xfffbebdf),
    super.decorativeDeepPeach200 = const Color(0xfff4cfb2),
    super.decorativeDeepPeach300 = const Color(0xffe3b591),
    super.decorativeDeepPeach400 = const Color(0xffc19372),
    super.decorativeDeepPeach500 = const Color(0xffcf7e3f),
    super.decorativeDeepPeach600 = const Color(0xffaa6631),
    super.decorativeDeepPeach700 = const Color(0xff7e4f2a),
    super.decorativeDeepPeach800 = const Color(0xff553720),
    super.decorativeDeepPeach900 = const Color(0xff2e2014),
    super.decorativeBrandPrimary = WhiteLabelColorRawTokens.colorBlue500,
    super.decorativeBrandPrimaryMuted = const Color(0x00ff0000),
    super.decorativeBrandPrimaryEmphasized = const Color(0x00ff0000),
    super.decorativeBrandSecondary = ColorRawTokens.colorFunctionalBlack,
    super.decorativeBrandSecondaryMuted = const Color(0x00ff0000),
    super.decorativeBrandSecondaryEmphasized = const Color(0x00ff0000),
    super.decorativeBrandTertiary = ColorRawTokens.colorFunctionalWhite,
    super.decorativeBrandTertiaryMuted = const Color(0x00ff0000),
    super.decorativeBrandTertiaryEmphasized = const Color(0x00ff0000),
    super.decorativeNeutralMutedLowest = ColorRawTokens.colorFunctionalGrayLight80,
    super.decorativeNeutralMutedLower = ColorRawTokens.colorFunctionalGrayLight160,
    super.decorativeNeutralMutedLow = ColorRawTokens.colorFunctionalGrayLight240,
    super.decorativeNeutralMutedMedium = ColorRawTokens.colorFunctionalGrayLight320,
    super.decorativeNeutralMutedHigh = ColorRawTokens.colorFunctionalGrayLight400,
    super.decorativeNeutralMutedHigher = ColorRawTokens.colorFunctionalGrayLight800,
    super.decorativeNeutralMutedHighest = ColorRawTokens.colorFunctionalGrayLight960,
    super.decorativeNeutralEmphasizedLowest = ColorRawTokens.colorFunctionalGrayDark240,
    super.decorativeNeutralEmphasizedLower = ColorRawTokens.colorFunctionalGrayDark320,
    super.decorativeNeutralEmphasizedLow = ColorRawTokens.colorFunctionalGrayDark400,
    super.decorativeNeutralEmphasizedMedium = const Color(0x00ff0000),
    super.decorativeNeutralEmphasizedHigh = const Color(0x00ff0000),
    super.decorativeNeutralEmphasizedHigher = ColorRawTokens.colorFunctionalGrayDark640,
    super.decorativeNeutralEmphasizedHighest = const Color(0x00ff0000),
    super.decorativeAccent1Muted = WhiteLabelColorRawTokens.colorDecorativeEmerald200,
    super.decorativeAccent1Default = WhiteLabelColorRawTokens.colorDecorativeEmerald500,
    super.decorativeAccent1Emphasized = WhiteLabelColorRawTokens.colorDecorativeEmerald700,
    super.decorativeAccent2Muted = WhiteLabelColorRawTokens.colorDecorativeSky200,
    super.decorativeAccent2Default = WhiteLabelColorRawTokens.colorDecorativeSky400,
    super.decorativeAccent2Emphasized = WhiteLabelColorRawTokens.colorDecorativeSky700,
    super.decorativeAccent3Muted = ColorRawTokens.colorFunctionalSun200,
    super.decorativeAccent3Default = ColorRawTokens.colorFunctionalSun500,
    super.decorativeAccent3Emphasized = WhiteLabelColorRawTokens.colorDecorativeAmber500,
    super.decorativeAccent4Muted = WhiteLabelColorRawTokens.colorDecorativeAmethyst200,
    super.decorativeAccent4Default = WhiteLabelColorRawTokens.colorDecorativeAmethyst400,
    super.decorativeAccent4Emphasized = WhiteLabelColorRawTokens.colorDecorativeAmethyst800,
    super.decorativeAccent5Muted = WhiteLabelColorRawTokens.colorDecorativeShockingPink100,
    super.decorativeAccent5Default = WhiteLabelColorRawTokens.colorDecorativeShockingPink200,
    super.decorativeAccent5Emphasized = WhiteLabelColorRawTokens.colorDecorativeShockingPink300,
    super.decorativeSkinTint100 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach100,
    super.decorativeSkinTint200 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach200,
    super.decorativeSkinTint300 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach300,
    super.decorativeSkinTint400 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach400,
    super.decorativeSkinTint500 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach500,
    super.decorativeSkinTint600 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach600,
    super.decorativeSkinTint700 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach700,
    super.decorativeSkinTint800 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach800,
    super.decorativeSkinTint900 = WhiteLabelColorRawTokens.colorDecorativeDeepPeach900,
  });
}
