//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_overlay_semantic_tokens.dart';
import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';

class SoshColorOverlaySemanticTokens extends OudsColorOverlaySemanticTokens {
  const SoshColorOverlaySemanticTokens({
    super.overlayDefaultDark = ColorRawTokens.colorOpacityWhite80,
    super.overlayDefaultLight = ColorRawTokens.colorFunctionalWhite,
    super.overlayDragDark = ColorRawTokens.colorOpacityWhite200,
    super.overlayDragLight = ColorRawTokens.colorOpacityBlack40,
    super.overlayEmphasizedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.overlayEmphasizedLight = SoshColorRawTokens.colorBlueDuckDark880,
    super.overlayModalDark = ColorRawTokens.colorFunctionalBlack, // Error
    super.overlayModalLight = ColorRawTokens.colorFunctionalWhite, // Error
  });
}
