//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_border_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorBorderSemanticTokens extends OudsColorBorderSemanticTokens {
  const SoshColorBorderSemanticTokens({
    super.borderBrandPrimaryDark = SoshColorRawTokens.colorRaspberry300,
    super.borderBrandPrimaryLight = SoshColorRawTokens.colorRaspberry500,
    super.borderBrandSecondaryDark = SoshColorRawTokens.colorLochmaraLight640,
    super.borderBrandSecondaryLight = SoshColorRawTokens.colorLochmaraDark240,
    super.borderBrandTertiaryDark = SoshColorRawTokens.colorTurbo300,
    super.borderBrandTertiaryLight = SoshColorRawTokens.colorTurbo500,
    super.borderDefaultDark = SoshColorRawTokens.colorOpacityWhite200,
    super.borderDefaultLight = SoshColorRawTokens.colorOpacityBlack200,
    super.borderEmphasizedDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.borderEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.borderFocusDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.borderFocusInsetDark = SoshColorRawTokens.colorFunctionalGrayDark880,
    super.borderFocusInsetLight = ColorRawTokens.colorFunctionalWhite,
    super.borderFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.borderMinimalDark = SoshColorRawTokens.colorOpacityWhite40,
    super.borderMinimalLight = SoshColorRawTokens.colorOpacityBlack40,
    super.borderMutedDark = SoshColorRawTokens.colorOpacityWhite120,
    super.borderMutedLight = SoshColorRawTokens.colorOpacityBlack120,
    super.borderOnBrandPrimaryDark = SoshColorRawTokens.colorLochmaraDark960,
    super.borderOnBrandPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.borderOnBrandSecondaryDark = SoshColorRawTokens.colorLochmaraDark960,
    super.borderOnBrandSecondaryLight = ColorRawTokens.colorFunctionalWhite,
    super.borderOnBrandTertiaryDark = SoshColorRawTokens.colorLochmaraDark960,
    super.borderOnBrandTertiaryLight = ColorRawTokens.colorFunctionalBlack,
    super.borderStatusAccentDark = SoshColorRawTokens.colorRaspberry300,
    super.borderStatusAccentLight = SoshColorRawTokens.colorRaspberry500,
    super.borderStatusInfoDark = SoshColorRawTokens.colorLochmaraLight400,
    super.borderStatusInfoLight = SoshColorRawTokens.colorLochmaraDark240,
    super.borderStatusNegativeDark = ColorRawTokens.colorFunctionalScarlet300,
    super.borderStatusNegativeLight = ColorRawTokens.colorFunctionalScarlet600,
    super.borderStatusPositiveDark = ColorRawTokens.colorFunctionalMalachite300,
    super.borderStatusPositiveLight = ColorRawTokens.colorFunctionalMalachite750,
    super.borderStatusWarningDark = SoshColorRawTokens.colorTurbo300,
    super.borderStatusWarningLight = SoshColorRawTokens.colorTurbo500,
  });
}
