//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_bg_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorBgSemanticTokens extends OudsColorBgSemanticTokens {
  const SoshColorBgSemanticTokens({
    super.bgEmphasizedDark = SoshColorRawTokens.colorBlueDuckDark720,
    super.bgEmphasizedLight = SoshColorRawTokens.colorBlueDuckDark880,
    super.bgPrimaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.bgPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.bgSecondaryDark = SoshColorRawTokens.colorBlueDuckDark880,
    super.bgSecondaryLight = SoshColorRawTokens.colorBlueDuckLight80,
    super.bgTertiaryDark = SoshColorRawTokens.colorCitrine950,
    super.bgTertiaryLight = SoshColorRawTokens.colorCitrine50,
  });
}
