//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_action_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorActionSemanticTokens extends OudsColorActionSemanticTokens {
  const SoshColorActionSemanticTokens({
    super.actionDisabledDark = SoshColorRawTokens.colorOpacityWhite200,
    super.actionDisabledLight = SoshColorRawTokens.colorOpacityBlack200,
    super.actionEnabledDark = SoshColorRawTokens.colorLochmaraLight640,
    super.actionEnabledLight = SoshColorRawTokens.colorRaspberry500,
    super.actionFocusDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.actionFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.actionHighlightedDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.actionHighlightedLight = SoshColorRawTokens.colorLochmaraDark240,
    super.actionHoverDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.actionHoverLight = ColorRawTokens.colorFunctionalBlack,
    super.actionLoadingDark = SoshColorRawTokens.colorTurbo300,
    super.actionLoadingLight = SoshColorRawTokens.colorLochmaraDark240,
    super.actionNegativeEnabledDark = ColorRawTokens.colorFunctionalScarlet300,
    super.actionNegativeEnabledLight = ColorRawTokens.colorFunctionalScarlet600,
    super.actionNegativeFocusDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeFocusLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeHoverDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeHoverLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeLoadingDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativeLoadingLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionNegativePressedDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativePressedLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionPressedDark = SoshColorRawTokens.colorTurbo300,
    super.actionPressedLight = SoshColorRawTokens.colorLochmaraDark240,
    super.actionReadOnlyPrimaryDark = SoshColorRawTokens.colorFunctionalGrayLight160,
    super.actionReadOnlyPrimaryLight = ColorRawTokens.colorFunctionalBlack,
    super.actionReadOnlySecondaryDark = SoshColorRawTokens.colorOpacityWhite200,
    super.actionReadOnlySecondaryLight = SoshColorRawTokens.colorOpacityBlack200,
    super.actionSelectedDark = SoshColorRawTokens.colorLochmaraLight640,
    super.actionSelectedLight = SoshColorRawTokens.colorRaspberry500,
    super.actionSupportDisabledDark = SoshColorRawTokens.colorOpacityWhite40,
    super.actionSupportDisabledLight = SoshColorRawTokens.colorOpacityBlack40,
    super.actionSupportEnabledDark = SoshColorRawTokens.colorOpacityWhite40,
    super.actionSupportEnabledLight = SoshColorRawTokens.colorOpacityBlack40,
    super.actionSupportFocusDark = SoshColorRawTokens.colorOpacityWhite80,
    super.actionSupportFocusLight = SoshColorRawTokens.colorOpacityBlack80,
    super.actionSupportHoverDark = SoshColorRawTokens.colorOpacityWhite80,
    super.actionSupportHoverLight = SoshColorRawTokens.colorOpacityBlack80,
    super.actionSupportLoadingDark = SoshColorRawTokens.colorOpacityWhite120,
    super.actionSupportLoadingLight = SoshColorRawTokens.colorOpacityBlack120,
    super.actionSupportPressedDark = SoshColorRawTokens.colorOpacityWhite120,
    super.actionSupportPressedLight = SoshColorRawTokens.colorOpacityBlack120,
    super.actionVisitedDark = ColorRawTokens.colorFunctionalAmethyst400,
    super.actionVisitedLight = ColorRawTokens.colorFunctionalAmethyst600,
  });
}
