//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_content_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorContentSemanticTokens extends OudsColorContentSemanticTokens {
  const SoshColorContentSemanticTokens({
    super.contentBrandPrimaryDark = SoshColorRawTokens.colorMagenta300,
    super.contentBrandPrimaryLight = SoshColorRawTokens.colorMagenta500,
    super.contentBrandSecondaryDark = SoshColorRawTokens.colorBlueDuckLight800,
    super.contentBrandSecondaryLight = SoshColorRawTokens.colorBlueDuckDark400,
    super.contentBrandTertiaryDark = SoshColorRawTokens.colorCitrine300,
    super.contentBrandTertiaryLight = SoshColorRawTokens.colorCitrine500,
    super.contentDefaultDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentDefaultLight = ColorRawTokens.colorFunctionalBlack,
    super.contentDisabledDark = ColorRawTokens.colorOpacityWhite200,
    super.contentDisabledLight = ColorRawTokens.colorOpacityBlack200,
    super.contentMutedDark = ColorRawTokens.colorOpacityWhite640,
    super.contentMutedLight = ColorRawTokens.colorOpacityBlack680,
    super.contentOnActionDisabledDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionDisabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionEnabledDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionEnabledLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionFocusDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionFocusLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHighlightedDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionHighlightedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionHoverDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionHoverLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionLoadingDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionLoadingLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionPressedDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionPressedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnActionSelectedDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnActionSelectedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnBrandPrimaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnBrandPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnBrandSecondaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnBrandSecondaryLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnBrandTertiaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnBrandTertiaryLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnOverlayEmphasizedDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.contentOnOverlayEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusAccentEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusAccentEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusAccentMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusAccentMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusInfoMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusInfoMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNegativeEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNegativeEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusNegativeMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusNegativeMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNeutralEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusNeutralEmphasizedLight = ColorRawTokens.colorFunctionalWhite,
    super.contentOnStatusNeutralMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusNeutralMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusPositiveMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusPositiveMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningEmphasizedDark = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentOnStatusWarningMutedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.contentOnStatusWarningMutedLight = ColorRawTokens.colorFunctionalBlack,
    super.contentStatusAccentDark = SoshColorRawTokens.colorMagenta500,
    super.contentStatusAccentLight = SoshColorRawTokens.colorMagenta500,
    super.contentStatusInfoDark = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusInfoLight = ColorRawTokens.colorFunctionalDodgerBlue500,
    super.contentStatusNegativeDark = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusNegativeLight = ColorRawTokens.colorFunctionalScarlet600,
    super.contentStatusPositiveDark = ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusPositiveLight = ColorRawTokens.colorFunctionalMalachite500,
    super.contentStatusWarningDark = ColorRawTokens.colorFunctionalSun500,
    super.contentStatusWarningLight = ColorRawTokens.colorFunctionalSun500,
  });
}
