//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_opacity_semantic_tokens.dart';

class SoshColorOpacitySemanticTokens extends OudsColorOpacitySemanticTokens {
  const SoshColorOpacitySemanticTokens({
    super.opacityLowerDark = SoshColorRawTokens.colorOpacityWhite80,
    super.opacityLowerLight = SoshColorRawTokens.colorOpacityBlack80,
    super.opacityLowestDark = SoshColorRawTokens.colorOpacityWhite40,
    super.opacityLowestLight = SoshColorRawTokens.colorOpacityBlack40,
    super.opacityTransparentDark = SoshColorRawTokens.colorOpacityWhite0,
    super.opacityTransparentLight = SoshColorRawTokens.colorOpacityBlack0,
  });
}
