//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.2.0
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_overlay_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorOverlaySemanticTokens extends OudsColorOverlaySemanticTokens {
  const SoshColorOverlaySemanticTokens({
    super.overlayDragDark = ColorRawTokens.colorOpacityWhite80,
    super.overlayDragLight = ColorRawTokens.colorOpacityBlack40,
    super.overlayDropdownDark = ColorRawTokens.colorFunctionalGrayDark560,
    super.overlayDropdownLight = ColorRawTokens.colorFunctionalWhite,
    super.overlayModalDark = SoshColorRawTokens.colorBlueDuckDark720,
    super.overlayModalLight = ColorRawTokens.colorFunctionalWhite,
    super.overlayTooltipDark = ColorRawTokens.colorFunctionalGrayDark560,
    super.overlayTooltipLight = ColorRawTokens.colorFunctionalGrayDark720,
  });
}
