//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.6.0
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_ai_semantic_tokens.dart';

class SoshColorAiSemanticTokens extends OudsColorAiSemanticTokens {
  const SoshColorAiSemanticTokens({
    super.aiPrimaryDark = SoshColorRawTokens.colorRaspberry300,
    super.aiPrimaryLight = SoshColorRawTokens.colorLochmaraDark240,
    super.aiQuaternaryDark = SoshColorRawTokens.colorLochmaraLight640,
    super.aiQuaternaryLight = SoshColorRawTokens.colorRaspberry500,
    super.aiSecondaryDark = SoshColorRawTokens.colorTurbo300,
    super.aiSecondaryLight = SoshColorRawTokens.colorTurbo500,
    super.aiTertiaryDark = SoshColorRawTokens.colorTurbo300,
    super.aiTertiaryLight = SoshColorRawTokens.colorTurbo500,
  });
}
