//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_action_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorActionSemanticTokens extends OudsColorActionSemanticTokens {
  const SoshColorActionSemanticTokens({
    super.actionDisabledDark = ColorRawTokens.colorOpacityWhite200,
    super.actionDisabledLight = ColorRawTokens.colorOpacityBlack200,
    super.actionEnabledDark = SoshColorRawTokens.colorBlueDuckLight800,
    super.actionEnabledLight = SoshColorRawTokens.colorMagenta500,
    super.actionFocusDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.actionFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.actionHighlightedDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.actionHighlightedLight = SoshColorRawTokens.colorBlueDuckDark400,
    super.actionHoverDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.actionHoverLight = ColorRawTokens.colorFunctionalBlack,
    super.actionLoadingDark = SoshColorRawTokens.colorCitrine300,
    super.actionLoadingLight = SoshColorRawTokens.colorBlueDuckDark400,
    super.actionNegativeEnabledDark = ColorRawTokens.colorFunctionalScarlet300,
    super.actionNegativeEnabledLight = ColorRawTokens.colorFunctionalScarlet600,
    super.actionNegativeFocusDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeFocusLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeHoverDark = ColorRawTokens.colorFunctionalScarlet200,
    super.actionNegativeHoverLight = ColorRawTokens.colorFunctionalScarlet700,
    super.actionNegativeLoadingDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativeLoadingLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionNegativePressedDark = ColorRawTokens.colorFunctionalScarlet100,
    super.actionNegativePressedLight = ColorRawTokens.colorFunctionalScarlet800,
    super.actionPressedDark = SoshColorRawTokens.colorCitrine300,
    super.actionPressedLight = SoshColorRawTokens.colorBlueDuckDark400,
    super.actionSelectedDark = SoshColorRawTokens.colorBlueDuckLight800,
    super.actionSelectedLight = SoshColorRawTokens.colorMagenta500,
    super.actionSupportEnabledDark = ColorRawTokens.colorOpacityWhite40,
    super.actionSupportEnabledLight = ColorRawTokens.colorOpacityBlack40,
    super.actionSupportFocusDark = ColorRawTokens.colorOpacityWhite80,
    super.actionSupportFocusLight = ColorRawTokens.colorOpacityBlack80,
    super.actionSupportHoverDark = ColorRawTokens.colorOpacityWhite80,
    super.actionSupportHoverLight = ColorRawTokens.colorOpacityBlack80,
    super.actionSupportLoadingDark = ColorRawTokens.colorOpacityWhite120,
    super.actionSupportLoadingLight = ColorRawTokens.colorOpacityBlack120,
    super.actionSupportPressedDark = ColorRawTokens.colorOpacityWhite120,
    super.actionSupportPressedLight = ColorRawTokens.colorOpacityBlack120,
    super.actionVisitedDark = SoshColorRawTokens.colorCitrine300,
    super.actionVisitedLight = SoshColorRawTokens.colorCitrine500,
  });
}
