//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Sosh brand tokens version 2.0.1
// Generated by Tokenator

import 'package:ouds_theme_sosh/raw/sosh_color_raw_tokens.dart';
import 'package:ouds_theme_contract/theme/tokens/semantic/ouds_color_border_semantic_tokens.dart';
import 'package:ouds_global_raw_tokens/color_raw_tokens.dart';

class SoshColorBorderSemanticTokens extends OudsColorBorderSemanticTokens {
  const SoshColorBorderSemanticTokens({
    super.borderBrandPrimaryDark = SoshColorRawTokens.colorMagenta300,
    super.borderBrandPrimaryLight = SoshColorRawTokens.colorMagenta500,
    super.borderBrandSecondaryDark = SoshColorRawTokens.colorBlueDuckLight800,
    super.borderBrandSecondaryLight = SoshColorRawTokens.colorBlueDuckDark400,
    super.borderBrandTertiaryDark = SoshColorRawTokens.colorCitrine300,
    super.borderBrandTertiaryLight = SoshColorRawTokens.colorCitrine500,
    super.borderDefaultDark = ColorRawTokens.colorOpacityWhite200,
    super.borderDefaultLight = ColorRawTokens.colorOpacityBlack200,
    super.borderEmphasizedDark = ColorRawTokens.colorOpacityWhite920,
    super.borderEmphasizedLight = ColorRawTokens.colorFunctionalBlack,
    super.borderFocusDark = ColorRawTokens.colorFunctionalGrayLight160,
    super.borderFocusInsetDark = ColorRawTokens.colorFunctionalGrayDark880,
    super.borderFocusInsetLight = ColorRawTokens.colorFunctionalWhite,
    super.borderFocusLight = ColorRawTokens.colorFunctionalBlack,
    super.borderMutedDark = ColorRawTokens.colorOpacityWhite80,
    super.borderMutedLight = ColorRawTokens.colorOpacityBlack80,
    super.borderOnBrandPrimaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.borderOnBrandPrimaryLight = ColorRawTokens.colorFunctionalWhite,
    super.borderOnBrandSecondaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.borderOnBrandSecondaryLight = ColorRawTokens.colorFunctionalWhite,
    super.borderOnBrandTertiaryDark = SoshColorRawTokens.colorBlueDuckDark960,
    super.borderOnBrandTertiaryLight = ColorRawTokens.colorFunctionalBlack,
    super.borderStatusAccentDark = SoshColorRawTokens.colorMagenta300,
    super.borderStatusAccentLight = SoshColorRawTokens.colorMagenta500,
    super.borderStatusInfoDark = ColorRawTokens.colorFunctionalDodgerBlue300,
    super.borderStatusInfoLight = ColorRawTokens.colorFunctionalDodgerBlue700,
    super.borderStatusNegativeDark = ColorRawTokens.colorFunctionalScarlet300,
    super.borderStatusNegativeLight = ColorRawTokens.colorFunctionalScarlet600,
    super.borderStatusPositiveDark = ColorRawTokens.colorFunctionalMalachite300,
    super.borderStatusPositiveLight = ColorRawTokens.colorFunctionalMalachite750,
    super.borderStatusWarningDark = ColorRawTokens.colorFunctionalSun300,
    super.borderStatusWarningLight = ColorRawTokens.colorFunctionalSun500,
  });
}
