//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Orange Compact brand tokens version 2.3.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_bulletList_tokens.dart';

class OrangeCompactBulletListTokens extends OudsBulletListTokens {
  final OudsProvidersTokens providersTokens;

  OrangeCompactBulletListTokens(this.providersTokens);

  @override
  double get spaceColumnGapBodyLarge => providersTokens.spaceTokens.columnGapSmall;
  @override
  double get spaceColumnGapBodyMedium => providersTokens.spaceTokens.columnGapSmall;
  @override
  double get spacePaddingBlockBodyLarge => providersTokens.spaceTokens.paddingBlock2xsmall;
  @override
  double get spacePaddingBlockBodyMedium => providersTokens.spaceTokens.paddingBlock2xsmall;
  @override
  double get spacePaddingInlineLevel0 => DimensionRawTokens.dimension50;
  @override
  double get spacePaddingInlineLevel1 => DimensionRawTokens.dimension450;
  @override
  double get spacePaddingInlineLevel2 => DimensionRawTokens.dimension850;
}
