//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.5.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_global_raw_tokens/font_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_listItem_tokens.dart';

/// TODO: This version is 2.6.0 Tmp - To Be Deleted
class WireframeListItemTokens extends OudsListItemTokens {
  final OudsProvidersTokens providersTokens;

  WireframeListItemTokens(this.providersTokens);

  @override
  double get borderRadiusCurrentIndicator =>
      providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusDefault => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderRadiusMedia => providersTokens.borderTokens.radiusNone;
  @override
  double get borderRadiusMediaRounded =>
      providersTokens.borderTokens.radiusSmall;
  @override
  double get borderRadiusRounded => providersTokens.borderTokens.radiusDefault;
  @override
  double get borderWidthCurrentPage => providersTokens.borderTokens.widthMedium;
  @override
  double get borderWidthDefault => providersTokens.borderTokens.widthDefault;
  @override
  Color get colorBgBadgeSafetyArea => providersTokens.colorScheme.bgPrimary;
  @override
  Color get colorBgCurrentDisabled =>
      providersTokens.colorScheme.actionDisabled;
  @override
  Color get colorBgCurrentEnabled => providersTokens.colorScheme.actionSelected;
  @override
  Color get colorBgCurrentFocus => providersTokens.colorScheme.actionFocus;
  @override
  Color get colorBgCurrentHover => providersTokens.colorScheme.actionHover;
  @override
  Color get colorBgCurrentPressed => providersTokens.colorScheme.actionPressed;
  @override
  Color get colorContentCurrentDisabled =>
      providersTokens.colorScheme.contentOnActionDisabled;
  @override
  Color get colorContentCurrentEnabled =>
      providersTokens.colorScheme.contentOnActionSelected;
  @override
  Color get colorContentCurrentFocus =>
      providersTokens.colorScheme.contentOnActionFocus;
  @override
  Color get colorContentCurrentHover =>
      providersTokens.colorScheme.contentOnActionHover;
  @override
  Color get colorContentCurrentPressed =>
      providersTokens.colorScheme.contentOnActionPressed;
  @override
  double get fontLetterSpacingAvatarInitialXlarge =>
      FontRawTokens.fontLetterSpacing450;
  @override
  double get fontLineHeightAvatarInitialXlarge =>
      FontRawTokens.fontLineHeight650;
  @override
  double get fontSizeAvatarInitialXlarge => FontRawTokens.fontSize450;
  @override
  double get opacityCurrentDivider => providersTokens.opacityTokens.invisible;
  @override
  double get opacityCurrentIndicator => providersTokens.opacityTokens.invisible;
  @override
  double get sizeAssetLarge => DimensionRawTokens.dimension500;
  @override
  double get sizeAssetMedium =>
      providersTokens.sizeTokens.iconWithLabelLargeSizeMedium;
  @override
  double get sizeAssetSmall =>
      providersTokens.sizeTokens.iconWithLabelLargeSizeSmall;
  @override
  double get sizeAssetXlarge => DimensionRawTokens.dimension700;
  @override
  double get sizeControlIndicator =>
      providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeCurrentIndicatorWidth => DimensionRawTokens.dimension50;
  @override
  double get sizeFlagHeight =>
      providersTokens.sizeTokens.iconWithLabelLargeSizeXsmall;
  @override
  double get sizeMaxWidth => DimensionRawTokens.dimension4000;
  @override
  double get sizeMinHeightDefault => DimensionRawTokens.dimension750;
  @override
  double get sizeMinHeightSmall =>
      providersTokens.sizeTokens.minInteractiveArea;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension2000;
  @override
  double get spaceColumnGap => providersTokens.spaceTokens.columnGapMedium;
  @override
  double get spacePaddingBlockBottomSlotListItemContainer =>
      providersTokens.spaceTokens.paddingBlockLarge;
  @override
  double get spacePaddingBlockBottomSlotTextContainer =>
      providersTokens.spaceTokens.paddingBlock3xsmall;
  @override
  double get spacePaddingBlockDefault =>
      providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingBlockSmall =>
      providersTokens.spaceTokens.paddingBlockXsmall;
  @override
  double get spacePaddingBlockTopAlignmentTopCounterweightDefault =>
      providersTokens.spaceTokens.paddingBlockSmall;
  @override
  double get spacePaddingBlockTopAlignmentTopCounterweightSmall =>
      providersTokens.spaceTokens.paddingBlockXsmall;
  @override
  double get spacePaddingBlockTopAlignmentTopTextContainerDefault =>
      providersTokens.spaceTokens.paddingBlock4xsmall;
  @override
  double get spacePaddingBlockTopAlignmentTopTextContainerSmall =>
      providersTokens.spaceTokens.paddingBlockNone;
  @override
  double get spacePaddingBlockTopHelperText =>
      providersTokens.spaceTokens.paddingBlockXsmall;
  @override
  double get spacePaddingInline =>
      providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spaceRowGap => providersTokens.spaceTokens.rowGapNone;
}
