//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.6.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_progressIndicatorMono_tokens.dart';
import 'package:ouds_theme_wireframe/raw/wireframe_color_raw_tokens.dart';

class WireframeProgressIndicatorMonoTokens extends OudsProgressIndicatorMonoTokens {
  final OudsProvidersTokens providersTokens;

  WireframeProgressIndicatorMonoTokens(this.providersTokens);

  @override
  Color get colorContentIndicator => providersTokens.colorScheme.lightDark(providersTokens.colorScheme.repositoryNeutralEmphasizedBlack, providersTokens.colorScheme.repositoryNeutralMutedWhite);
  @override
  Color get colorContentTrackDark => WireframeColorRawTokens.colorFunctionalGrayDark480;
  @override
  Color get colorContentTrackLight => WireframeColorRawTokens.colorFunctionalGrayLight320;
}
