//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.6.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_accordion_tokens.dart';

class WireframeAccordionTokens extends OudsAccordionTokens {
  final OudsProvidersTokens providersTokens;

  WireframeAccordionTokens(this.providersTokens);

  @override
  double get spacePaddingBlockBottomExpandContainerDefault => providersTokens.spaceTokens.paddingBlock3xlarge;
  @override
  double get spacePaddingBlockBottomExpandContainerSmall => providersTokens.spaceTokens.paddingBlock2xlarge;
  @override
  double get spacePaddingBlockTopExpandContainer => providersTokens.spaceTokens.paddingBlockXsmall;
}
