//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.0.0
// Generated by Tokenator

import 'package:flutter/material.dart';
import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_controlItem_tokens.dart';

class WireframeControlItemTokens extends OudsControlItemTokens {
  final OudsProvidersTokens providersTokens;

  WireframeControlItemTokens(this.providersTokens);

  @override
  double get borderRadius => providersTokens.borderTokens.radiusNone;
  @override
  double get borderRadiusItemOnly => providersTokens.borderTokens.radiusDefault;
  @override
  Color get colorBgFocus => providersTokens.colorScheme.actionSupportFocus;
  @override
  Color get colorBgHover => providersTokens.colorScheme.actionSupportHover;
  @override
  Color get colorBgLoading => providersTokens.colorScheme.actionSupportLoading;
  @override
  Color get colorBgPressed => providersTokens.colorScheme.actionSupportPressed;
  @override
  Color get colorContentLoader => providersTokens.colorScheme.actionLoading;
  @override
  double get sizeIcon => providersTokens.sizeTokens.iconWithLabelLargeSizeMedium;
  @override
  double get sizeListItemSizeMinHeightText => providersTokens.sizeTokens.iconWithLabelLargeSizeMedium;
  @override
  double get sizeLoader => providersTokens.sizeTokens.iconWithLabelLargeSizeSmall;
  @override
  double get sizeMaxHeightAssetsContainer => DimensionRawTokens.dimension1200;
  @override
  double get sizeMaxWidth => DimensionRawTokens.dimension4000;
  @override
  double get sizeMinHeight => DimensionRawTokens.dimension650;
  @override
  double get sizeMinWidth => DimensionRawTokens.dimension2000;
  @override
  double get spaceColumnGap => providersTokens.spaceTokens.columnGapMedium;
  @override
  double get spacePaddingBlock => providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingInline => providersTokens.spaceTokens.paddingInlineLarge;
  @override
  double get spaceRowGap => providersTokens.spaceTokens.rowGapNone;
}
