//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.6.0
// Generated by Tokenator

import 'package:ouds_global_raw_tokens/dimension_raw_tokens.dart';
import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_textArea_tokens.dart';

class WireframeTextAreaTokens extends OudsTextAreaTokens {
  final OudsProvidersTokens providersTokens;

  WireframeTextAreaTokens(this.providersTokens);

  @override
  double get sizeMaxHeightAssetsContainer => DimensionRawTokens.dimension1100;
  @override
  double get sizeMaxHeightInput => DimensionRawTokens.dimension2500;
  @override
  double get sizeMaxWidth => DimensionRawTokens.dimension6000;
  @override
  double get sizeMinHeightInput => DimensionRawTokens.dimension900;
  @override
  double get spacePaddingBlock => providersTokens.spaceTokens.paddingBlockSmall;
  @override
  double get spacePaddingBlockEmptyTrailingContainer => providersTokens.spaceTokens.paddingBlock2xsmall;
  @override
  double get spacePaddingBlockTopEmpty => providersTokens.spaceTokens.paddingBlockMedium;
  @override
  double get spacePaddingBlockTrailingContainer => providersTokens.spaceTokens.paddingBlockXsmall;
}
