//
// Software Name: OUDS Flutter
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Flutter library of reusable graphical components
//

// Wireframe brand tokens version 2.7.0
// Generated by Tokenator

import 'package:ouds_theme_contract/ouds_tokens_provider.dart';
import 'package:ouds_theme_contract/theme/tokens/components/ouds_alertMessage_tokens.dart';

class WireframeAlertMessageTokens extends OudsAlertMessageTokens {
  final OudsProvidersTokens providersTokens;

  WireframeAlertMessageTokens(this.providersTokens);

  @override
  double get borderWidth => providersTokens.borderTokens.widthThin;
  @override
  double get spaceRowGapBullet => providersTokens.spaceTokens.rowGapNone;
}
