name: Deploy Dartdoc with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  read-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Setup Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
        with:
          sdk: stable
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Setup Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: 3.3.4
      - name: Build with Dartdoc
        run: |
          cd ouds_core
          dart pub get
          dart doc .
      - name: Move DartDoc output
        run: |
          mkdir -p ./docs
          mv ouds_core/doc/api/* ./docs
      - name: Copy images files (orange logo and banner)
        run: |
          mkdir -p ./docs/assets
          cp ouds_core/assets/doc/orange_logo.svg ./docs/assets/
          cp ouds_core/assets/doc/banner.png ./docs/assets/
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: github-pages

      - name: List files in current directory (to verify artifact)
        run: |
          ls -la

      - name: Create docs directory if not exists
        run: |
          mkdir -p ./docs

      - name: Extract artifact into docs directory
        run: |
          tar -xvf artifact.tar -C ./docs
          ls -la ./docs

      - name: Commit changes and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout gh-pages || git checkout -b gh-pages
          git rm -rf .
          echo "flutter.unified-design-system.orange.com" > docs/CNAME
          git add ./docs/*
          commit_message="doc: deploy site to GitHub Pages - Version $(date +%Y%m%d)"
          git commit -m "$commit_message" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

